### ISSUE TITLE
Buildings being created on top of each other causing flickering.

### ISSUE THREAD

**Issue by NerbzHub** [mapbox/mapbox-unity-sdk#1000]
* Unity version: [2017.3.0f3]
* Mapbox SDK version: 1.4.5

* The platform you're building to: Windows

* A description of what you're trying to do:
The issue is that the building places two meshes on top of each other, causing the textures to flicker between the two textures. 

Steps to recreate the bug if appropriate:
* Abstract Map add buildings features
* Modelling: 
* Primitive Type: Polygon
* Extrusion Type: Property Height
* Geometry Type: Roof and Side
* Property Name: height
* Scale Factor: More than 0
* Snap To Terrain: yes
* Combine Meshes: yes
* Collider Type: Mesh Collider
* Texturing: 
* Style Type: Realistic

It has occurred with other options but these are currently the ones I have.

* Links to your logs are also helpful: 
This is a gif to show what is happening.
![doublemesh](https://user-images.githubusercontent.com/23629988/45273190-c54d5680-b4f4-11e8-8168-7c6a68ff7d53.gif)

**Comment by jordy-isaac** [comment]
@NerbzHub Thanks for the ticket. This is a known issue with Z fighting. There is a workaround for it. Please try adding the `RemoveZFighting` `NoiseOffsetModifier` that can be found in the SDK. You can add it by clicking `Add Existing` in the `Game Object Modifiers` section. It will open a selection dialogue to choose the modifier from the list.

<img width="352" alt="screen shot 2018-09-10 at 9 08 41 am" src="https://user-images.githubusercontent.com/33474236/45309709-2404d700-b4d9-11e8-8f80-7b32c9c83be5.png">

**Comment by NerbzHub** [comment]
Thank you for your reply. 

I implemented RemoveZFighting and it minimised the number of occurrences but there are still some occurrences. The buildings it is occurring on are changing though. I'm assuming it is due to the random value being created inside RemoveZFighting.

Is there something else you recommend trying? 

Otherwise, I'll try to find a workaround.

**Comment by highpockets** [comment]
BUMP...

This is still clearly an issue. Is there a reliable fix for this yet??

I have applied the NoiseOffsetModifier and it is not helping. My issue is that the roof of the buildings that are being duplicated are flickering between the roof textures of each of the duplicate buildings. This is less than optimal for UX.

I made my own hack to try to get around it by randomly varying the height of the buildings, but meshes cannot be combined for it to work and if there are lots of buildings around, this turns into 600+ batches and the performance hit is insane.

Does anyone know of a way to avoid duplicate buildings?? That is really the underlying issue here.
