### ISSUE TITLE
Set specific heights/zoom levels for adding/removing sublayers/features

### ISSUE THREAD

**Issue by josh-windsor** [mapbox/mapbox-unity-sdk#1010]
Hi, not too sure if I have missed something in the documentation or if this is a noob question (sorry ;) ) but I would like to set the buildings feature to only appear at certain zoom levels, is this at all possible. Have tried the following:

`	
if (Map.Zoom >= 19.0f)
{
	if (!Map.VectorData.LayerProperty.vectorSubLayers.Contains(_buildingsLayer))
	{
		Map.VectorData.AddVectorLayer(_buildingsLayer);
	}
}
else
{
	if (Map.VectorData.LayerProperty.vectorSubLayers.Contains(_buildingsLayer))
	{
		Map.VectorData.RemoveVectorLayer(0);
	}
}
`
As well as trying to set the layer inactive with the following:
`
_buildingsLayer.coreOptions.isActive = false;
`
Where buildings layer = 
`		_buildingsLayer = Map.VectorData.LayerProperty.vectorSubLayers[0];
`
The first method kind of works but is unstable and only works some of the time, often generating buildings at slightly lower zoom levels or not generating at significantly higher zoom levels.

Could someone direct me to the appropriate way to dealing with this!
Thanks, Josh
PS. a discord or slack server would work wonders for small questions like this!

**Comment by jordy-isaac** [comment]
@josh-windsor Have you tried using a LayerModifier or TagModifier? You can add one in the `Behavior Modifiers` > `Game Object Modifiers` section of the `AbstractMap.cs`. That approach would probably be the best way to go. Here I added a TagModifier and a AddMonoBehavior modifier to disable the GameObjects with the tag `Buidling` given a zoom level. This is hacky and you'll need to reload the map to get the buildings to re-enable if you want to toggle back. However, it should give you an idea on how to set it up.

<img width="421" alt="screen shot 2018-09-13 at 1 36 48 pm" src="https://user-images.githubusercontent.com/33474236/45514446-38a3d200-b75a-11e8-8ecf-c66f1ebb7fdf.png">


 Make sure to add the tag in the Tag Manager, too, so that the modifier can make use of it.
<img width="450" alt="screen shot 2018-09-13 at 1 36 55 pm" src="https://user-images.githubusercontent.com/33474236/45514435-2f1a6a00-b75a-11e8-9655-e50529e6a4aa.png">

Open the `AddMonoBehavioursModifer` and an element to the array to hold your script

<img width="444" alt="screen shot 2018-09-13 at 1 39 37 pm" src="https://user-images.githubusercontent.com/33474236/45514556-7d2f6d80-b75a-11e8-8c2b-071242a2a27f.png">

Create a new script and assign it. I just wrote some thing simple for demo's sake

```using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Mapbox.Unity.Map;

public class ZoomToggle : MonoBehaviour
{
    [SerializeField]
    AbstractMap _map;
    void Start()
    {
        if (_map == null)
        {
            _map = FindObjectOfType<AbstractMap>();
        }

    }

    void Update()
    {

        if (_map.Zoom > 19.0f)
        {
            gameObject.SetActive(false);
        }
    }
}
```
Press play and you'll see that all the buildings now have the tag and if you move the zoom beyond 19, the game objects will be disabled:

![modifiers](https://user-images.githubusercontent.com/33474236/45516251-5fb0d280-b75f-11e8-918a-5a1e866bdb03.gif)

**Comment by jordy-isaac** [comment]
If you're not looking to make the change at runtime. you can specify the zoom range for the [building layer](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#building) on your [custom style](https://www.mapbox.com/unity-sdk/maps/overview/custom-maps/#use-a-custom-style) and bring it into Unity. 

<img width="565" alt="screen shot 2018-09-13 at 4 39 37 pm" src="https://user-images.githubusercontent.com/33474236/45521630-ab6d7700-b773-11e8-8cd4-6212ec6dd961.png">

**Comment by josh-windsor** [comment]
Hi I am trying to implement this today, thanks for the quick reply.

 For note, If Mapbox is installed in a sub-directory ie Assets/Plugins/Mapbox rather than Assets/Mapbox Unity fires a UnityException: Creating asset at path  failed. here is console dump (https://pastebin.com/Z6kRSnsz) if this is an issue otherwise I have solved this by just moving it to the root directory.

**Comment by josh-windsor** [comment]
Hi again, I have tried both of your suggested solutions and both have problems. 

With the first solution, this does indeed work at hiding the buildings but still loads & places them before disabling, not removing the load times I am trying too (If this is the only solution then this is viable but could be better). 

The second solution using the style editor doesn't seem to change anything. I can see that the image layer loads the building's outlines at a higher zoom but the 3D feature does not change, still loading the 3D mesh for the buildings at zoom 15 rather than the specified 17 (making navigation in VR lag from zoom 15-17). I am wondering if it is related to the 'mapbox.3d-buildings,mapbox.mapbox-streets-v7' Data Source section.

Thanks again for the help and I look forward to continuing development with your tool.

**Comment by lunix15** [comment]
Hi, seem like:
1.    _map load layers data only when the map is created (or after reset) 
2.   _map looks at layers only when "whole number zoom" is reached (so zoom < 18.5 will work only as zoom < 18).

So I solved in this way:
- resetting the map the first time your layer go on (if you start with layer off this will help a lot)
- switching off the global "sourceOptions" too

Be careful: this solution work fine with one layer, I don't know way it becomes messy with more layers or if you reset the map many times.

```` c#
 private bool switchLayer () {
    //limit layers visibility by zoom
    bool outOfZoom = false;
    if (_map.Zoom < MIN_ZOOM_LAYERS || _map.Zoom > MAX_ZOOM_LAYERS) outOfZoom = true;

    //update layers
    foreach (VectorSubLayerProperties layer in _map.VectorData.LayerProperty.vectorSubLayers) {
        if (layer.coreOptions.isActive != !outOfZoom) {

            //switch on off
            layer.coreOptions.isActive = !outOfZoom;
            _map.VectorData.LayerProperty.sourceOptions.isActive = !outOfZoom;

            //debug
            if (verboseDebug) {
                if (outOfZoom) Debug.Log ("layer now is off");
                else Debug.Log ("layer now is on");
            }

            //if isActive changed map needs to reload layer's stuff
            if (once) {
                _map.ResetMap ();
                once = false;
            }
        }
    }

    return !outOfZoom;
}
````

**Comment by josh-windsor** [comment]
Thanks for the reply Lunix. Every time I call a reset map, I get a null reference exception in the TerrainFactory([](https://pastebin.com/QmsXAtcm)). This occurs in the example scenes as well as my own. Any ideas what this could be?

**Comment by amit-pnkfrg** [comment]
> If you're not looking to make the change at runtime. you can specify the zoom range for the [building layer](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#building) on your [custom style](https://www.mapbox.com/unity-sdk/maps/overview/custom-maps/#use-a-custom-style) and bring it into Unity.
> 
> <img alt="screen shot 2018-09-13 at 4 39 37 pm" width="565" src="https://user-images.githubusercontent.com/33474236/45521630-ab6d7700-b773-11e8-8cd4-6212ec6dd961.png">

Just want to add that this solution worked for me. Thanks!
