### ISSUE TITLE
Question: How can I make a 2D map view?

### ISSUE THREAD

**Issue by Flameshot** [mapbox/mapbox-unity-sdk#1017]
Hello everyone and a big thumb up for people who created this sdk. I am looking to generate a 2D map with details like roads and buildings. Something like 3D but in 2D, like a puzzle or how is openstreetmap made. Mainly thing is to have every piece separated not just a plane object with map generated. Is there any way I can make this with mapbox, or a hackfix, walkthrough. Furthermore if I could do this with Mapbox Streets it would be awesome. Any ideas are welcome. I hope I posted in the right place, if not, please guide me to the right place.

Demo photo: https://imgur.com/a/gOZZBpC

I want every thing separated like 3D because I want to select the buildings and streets.

**Comment by jordy-isaac** [comment]
Hi @Flameshot Depending on your use case, one think you might try is adding the vector layers that you want but not extruding them in the [Modeling](https://www.mapbox.com/unity-sdk/maps/overview/map-features/#modeling) section.

<img width="671" alt="screen shot 2018-09-21 at 9 22 44 am" src="https://user-images.githubusercontent.com/33474236/45893492-44a61a00-bd80-11e8-8f1b-3117b813c087.png">

You can set up your layers manually on the map, or even just use the `CitySimulatorMap` prefab as a starting point and change the `Extrusion Type` of the roads and buildings that have already been setr up. This will render the features, but they will be flat/low profile.

You'll also likely want to use flat terrain rather than elevation, and position your camera so the view is the top down feel that you're looking for.

**Comment by Flameshot** [comment]
Hello, @jordy-isaac and thanks for your response. I have made the changes you told me, the only problem i find is that using flat terrain is causing flickering in scene mode of the buildings.

**Comment by jordy-isaac** [comment]
@Flameshot Glad to hear it! Sure, no problem. Feel free to re-open this one of cut a new one. Whatever is best for you.

**Comment by Flameshot** [comment]
Hello, @jordy-isaac and have a nice week. I need a start point for some features which I saw mapbox has but I don't find documentation for them for unity.

The first one is Highlight buildings feature ( I saw the script, I saw how to add it on buldings but it seems I didn't set something right so it doesn't work)
The second one: I'm looking to draw lines on the map, like rectengulars around the building or street or circles and somehow to save the position of drawings (this will be made using server). I explained everything detailed so maybe you know to give me a start point of doing this.

Have a nice day.
