### ISSUE TITLE
Better map tile blending, navigation, zoom. QuadTreeCameraMovement potential improvements? 

### ISSUE THREAD

**Issue by brianchasalow** [mapbox/mapbox-unity-sdk#1135]
Hey there- curious if this has seen any recent improvement or if there are plans on your roadmap. Looks like there are several issues that need addressing.

1) Loading tiles are really bad, and obvious. You need to blend between the loaded tile and the next tile to be loaded. 
2) The QuadTreeCameraMovement.cs script should be using the Canvas UI instead of Input.mousePosition and Input.touches, so that input plays nicely with UI objects. It should use the IDragHandler/IEventSystemHandler callbacks.
3) Zooming with a scrollwheel should center on the mouse position. (i.e., the zoom center should a selectable target)
4) Similarly, pinch to zoom should center on the midpoint between the two fingers.
5) Zoom should smoothly lerp between zoom levels as you zoom in/out. This should be internal to the script, with a flag if you want to disable it, but default should be lerp = on. 
6) Double tap on the map should zoom in a level and focus on where you clicked, similar to how it does in Mapbox JS.

I thought about implementing parts of this, but this is really core to the Mapbox product so you guys should do it (and it would take a lot less time for someone who deeply understands the API)
Thanks.

_Originally posted by @brianchasalow in https://github.com/mapbox/mapbox-unity-sdk/issues/584#issuecomment-437103393_

**Comment by nilsk123** [comment]
hear hear

**Comment by zogster** [comment]
Hi!

Is there a roadmap/timeline for these features mentioned above?
Most important for us:
1) Smooth blending between tiles and less flickering wenn different tiles are loaded. Right now it seems to jump between "locations" when a other tile-detail-level is loaded.
2) Better/Smoother input handling.

Because if not we might have to start working on this ourselves.

Thanks!

**Comment by brianchasalow** [comment]
Hey there- just checking in on the status of this 4 months later. How's it coming along?

**Comment by zogster** [comment]
FYI: In our Unity tech demo, we used this with Mapbox: https://assetstore.unity.com/packages/tools/integration/online-maps-13261
You might wanna give it a shot. 
You can configure smooth zooming panning etc (the settings are there, you just have to find em ;) )

**Comment by brnkhy** [comment]
Hello @brianchasalow @zogster @nilsk123 ,
I'm really sorry for late reply, my bad.
All your points are good and valid. Admittedly our camera work isn't really polished at the moment and we tend to leave that to developers as it changes a lot for their needs and use cases. For example, I tend to build all my demos with scroll/pinch focusing on the camera center instead of mouse/pinch position.

On some individual points;
`Loading tiles are really bad, and obvious. You need to blend between the loaded tile and the next tile to be loaded.`
I'm afraid this is the most difficult one in short term. That behaviour was kind of a design decision back in the days but now I agree it doesn't really look pretty. It takes a lot more than camera work though so it'll probably stay like this for short term.

`Zoom should smoothly lerp between zoom levels as you zoom in/out.`
Isn't this the behaviour on ZoomableMap demo scene? Or did I get it wrong?

**Comment by AdrianLazar** [comment]
Hi brnkhy,
Just wanted to add my point that the current behaviour for when loading different tiles is a dealbreaker, do you have any kind of ETA for the fix?
I will keep an eye on the development and return to mapbox once the issue has been addressed.

Best,
-Adrian

**Comment by brnkhy** [comment]
@AdrianLazar I'm afraid we won't be able to change that behavious in short term Adrian, I'm sorry :(

**Comment by brianchasalow** [comment]
Hi- @brnkhy! It's been 6 months since I posted this issue so I haven't been super close to the problem area for a bit, but let me see if I can answer some of the questions.

> Zoom should smoothly lerp between zoom levels as you zoom in/out.
> Isn't this the behaviour on ZoomableMap demo scene? Or did I get it wrong?

A good ground truth for how it should feel is the Mapbox GL JS example when you double click on a location on the map. The Unity example doesn't have feature parity for the feel of the GL JS example when you double click to zoom into a location on the map, or when you use the scroll wheel. 

> The QuadTreeCameraMovement.cs script should be using the Canvas UI instead of Input.mousePosition and Input.touches
> I think I don't get this one, can you explain a little more? Do you mean like using 2d (UI) movement instead of raycasting?

The source for input to the script could be the IEventSystemHandler callbacks, so that it can play nicely with other UI elements. Let's say you have a UI button in front of the map- you would want the button's input to prevent input to the clicking of the map.  It looks like you started to try to do that kind of thing via EventSystem.current.IsPointerOverGameObject(), but that doesn't really work for native UI.

Using UI event callbacks would allow for this to work natively in a Unity UI-centric way. You can use the callbacks on a UI element- [IPointerDownHandler](https://docs.unity3d.com/ScriptReference/EventSystems.IPointerDownHandler.html), IDragHandler, etc. You can get the equivalent of Input.mousePosition via [PointerEventData](https://docs.unity3d.com/ScriptReference/EventSystems.PointerEventData.html)'s position property, returned from those callbacks.

As to your question, one might want it to also work in 3d, so it's fine if it raycasts if it's a 3d map. However, the initial mouse button drag event input presses should probably be fed from the UI system. In fact- if you wrote this in a more event-driven way, you could pretty easily replace UnityUI mouse input with Input.mousePosition and it should still work.

Feel free to contact me directly if you would like to discuss this.

**Comment by smxthereisonlyone** [comment]
So how is the status on these super basic UX fixes?

**Comment by rbyjoswald** [comment]
Following up that the (lack of) transition between different zoom levels is a deal-braker. Any news on this issue?
