### ISSUE TITLE
Self hosting

### ISSUE THREAD

**Issue by BruceKristelijn** [mapbox/mapbox-unity-sdk#1139]
Hi! Is there a way to use my own tilemap server with the sdk? I am using Mapbox gl for the online platform of the app without a problem with our own server but now I want to know if and how it is possible to do this? I suppose it is possible since the whole sdk is opensource.

Kind regards,
Bruce

**Comment by jordy-isaac** [comment]
It's possible but it would likely be no small task and the implementation would be up to you. We also have [Atlas](https://blog.mapbox.com/ar-and-3d-in-a-secure-environment-2cf6068d6d51) for these types of use cases, but generally speaking, it's suited for larger projects. If you'd like more info, please let us know and our sales team can reach out.

**Comment by twelch** [comment]
@BruceKristelijn take a look at hosting your own style document and tile service.  You would point the SDK at the style doc -- https://www.mapbox.com/help/unity-custom-map-style/. You can find a lot of info on the building blocks out there in this doc -- https://github.com/mapbox/awesome-vector-tiles

Here's a similar question over on the react-native SDK repo -- https://github.com/mapbox/react-native-mapbox-gl/issues/630

Hope that helps.  Cheers

**Comment by SamuelObvious** [comment]
Hi! 

I wanted the same issue than @BruceKristelijn. In need to call my own tile-map server with the SDK. The reason once the project is deploy, the station won't have any connection to internet because of security issue. 

So it must work offline all the time. 

I also interested by our atlas solution but we need to try it, if it can work with your unity SDK. whoever the two must work without internet.  

Thanks for the help. 

Samuel

**Comment by douglasg14b** [comment]
Also interested in this, though completely from a cost standpoint. For a GeoLocation based mobile game, the MAU & vector tile requests (Ie. for offline tiles) are prohibitively expensive. ESPECIALLY for transient users.

I'd want to serve up my own tiles when possible, and refer to Mapbox for a limited set of requests to control costs that would otherwise be as much or greater than my revenue...

For example, I can host OSM tiles that lets a user just download their entire state. On Mapbox that would cost me ~$300 for 1,425,362 tiles.....

I see posts around that individuals using the JS version of Mapbox can customize their tile providers. Can the Unity SDK do that?
