### ISSUE TITLE
Displaying POI Properties Information

### ISSUE THREAD

**Issue by hmaskat17** [mapbox/mapbox-unity-sdk#1147]
Hi! Sorry, i'm new to Unity and Mapbox. I have a similar issue. 

I am trying to use a custom data source to display 3d models over my map co-ordinates and display their properties information when the 3d prefabs are clicked on.

I succeeded in displaying the 3d models over the co-ordinates using a POI PrefabModifier.

I am not able to display the additional GeoJSON properties data of my custom dataset, similar to how multiple properties are shown together in the InteractiveStyledVectorMap. How is this done? I want a new panel, that shows a few of the properties data, to display when the 3d model is clicked on. Thanks.

_Originally posted by @hmaskat17 in https://github.com/mapbox/mapbox-unity-sdk/issues/1043#issuecomment-441305991_

**Comment by jordy-isaac** [comment]
@hmaskat17 Thanks for the ticket. What have you tried so far? Have you looked at how the `InteractiveSelectionCanvas` is implemented and the [FeatureUIMarker.cs](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Examples/Scripts/FeatureUiMarker.cs) script?

Also keep in mind that if your instantiating a custom prefab instead of using the building layer like the example does, you might have to do some additional work to make sure you can access the vector data when the user input is detected on the prefab.
