### ISSUE TITLE
Get map features within loaded tiles

### ISSUE THREAD

**Issue by xeon321** [mapbox/mapbox-unity-sdk#1150]
Hi, I have imported my own tileset into the map. How do I get the map features/my data within the loaded/active tiles? My map has a list of location which I need to instantiate buttons on them and make em clickable.  I tried using the PrefabModifier but its spawning them in 3D and I need them to be 2D UI in the Canvas. So I am trying to query the data within the loaded tiles and instantiate the buttons myself.

**Comment by jordy-isaac** [comment]
@xeon321 It sounds like you might be looking for [IVectorLayer](https://www.mapbox.com/mapbox-unity-sdk/api/unity/Mapbox.Unity.Map.IVectorDataLayer.html). Please let us know if this isn't what you need.

**Comment by xeon321** [comment]
Hi, thanks for the response. 
I modified the zoomable map example, right now what I need is some way to get the currently displayed tiles' point features

Q1. How do I get the currently displayed tiles? 
Should I use ILayer.IsLayerActive in IVectorLayer?

Q2. How do I get the currently displayed tiles' point features? 
I assume is this GetAllPointFeatureSubLayers()? And from there how do I get the point features' locations?

**Comment by brnkhy** [comment]
Hello @xeon321 ,
You should be able to get active tiles using `AbstractMap.MapVisualizer.ActiveTiles` but we do not keep list of features inside the tiles so that might not help with your question.
Best option here is to create a gameobject modifier and adding it to your poi layer. A gameobject modifier receives all features in the layer (unless filtered) and in that script, you can easily instantiate UI prefab for example and add it under a canvas, exactly like PrefabModifier is doing.
