### ISSUE TITLE
Fix holes in Globe projection 

### ISSUE THREAD

**Issue by JorgenEngenNapstad** [mapbox/mapbox-unity-sdk#1167]
* Mapbox SDK version: 2.0.0

Is there any clever way of closing the holes in the top/north and bottom/south poles of the Globe projection? 

![image](https://user-images.githubusercontent.com/35730930/49730374-742a3b80-fc78-11e8-9395-c048581640da.png)

**Comment by jordy-isaac** [comment]
@JorgenEngenNapstad It's mostly due to a lack of imagery/data for that area. You could use a sphere or mesh to cover it but it likely won't be easy. We might be able to come up with a solution, but I can't promise a timeframe for it. We'll keep this ticket open in the meantime so that we can have some visibility into a fix.
