### ISSUE TITLE
Loading Poi takes so much time. 

### ISSUE THREAD

**Issue by lucmanmani** [mapbox/mapbox-unity-sdk#1204]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3.1f1 
* Mapbox SDK version: 1.2.0
* The platform you're building to: Android

When we load the scene POI takes time to load and system hangs. FPS in unity decreases to 3FPS. If I remove the POI from scene FPS becomes normal on scene. This problem of loading POI only occurs when we load busy area on map like NEW YORK City.

Any help would be much appreciated. Thanks

**Comment by brnkhy** [comment]
@lucmanmani It's most likely because of the poi amount and creating a gameobject (prefab) for every single one of them in one frame. We don't have optimizations on that as it heavily depends on your usecase but I think I would suggest something like;
- create a custom game oject modifier, pretty much a clone of `prefab modifier`.
- but unlike `prefab modifier`, this new one will just cache the locations/features it receives or even better, just pass them to a monobehaviour on the scene (because monobehaviours have update method and we'll use that).
- that monobehaviour will cache all incoming points and create prefabs by some logic depending on your usecase, i.e. `certain range from player` or `10 prefabs per 5 frame`.

hope that helps!
