### ISSUE TITLE
Spawning objects (but not a lot of objects) along streets

### ISSUE THREAD

**Issue by 1701Tiberius** [mapbox/mapbox-unity-sdk#1205]
I am using FEATURES, Map Features, Data Layer (road) with a primitive type of custom and a GameObject Modifier of PrefabModifier to spawn my own custom prefabs at every road, but this results in a lot of prefabs. Is there any way to spawn only like every third one, or some other multiple?

Thanks!

**Comment by brnkhy** [comment]
Hello @1701Tiberius,
So you already have the correct idea there with using game object modifiers.  But when you use `Prefab modifier`, it will place that prefab on all data points, like all corners on roads and it'll get spammy on round corners as you noted.
What you should do is to create a custom gameobject modifier, very similar to `Prefab modifier` but instead of using all original data points, you should use an interval and place objects on line using that interval. That way you can easily have logic like; `place an object every 10 units` etc.
hope that helps!
