### ISSUE TITLE
Not working with Unity Lightweight Rendering Pipeline ?

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#1210]
Currently using Unity 2018.3.02f with mapbox sdk 1.3.0.

I lately introduced the Unity Lightweight Rendering Pipeline which should improve performance on mobile devices into my project... therefore i used the standard graphic settings for unity, with standard shaders...

Before changing to the pipeline, showing the map using the "BasicMap" script worked fine and effecient...

I occured following problem after the upgrade to the unity Lightweight rendering pipeline... the map shows when i play using the editor ... i can interact with it... its all fine...

Once i export my project for android i noticed that the map tiles dont show up... i just see the blue camera background color... before i changed my project to unity lightweight rendering pipeline, the map showed up...

Any ideas why that happens ? Did anyone ever tried that ? 

Heres the imgur link... first image shows in editor... second in the android build !
https://imgur.com/a/MgJzKwL

I hope for an fast response... its very important... thanks !

**Comment by brnkhy** [comment]
@generay I don't think anyone on team tried LWRP yet and to be honest I cannot imagine what can be the problem either. I mean sdk just generates the mesh afterall. Have you verified your lwrp setup works with regular objects on android?

**Comment by tjukic** [comment]
Why was this closed? Materials in MB cannot be used with LWRP (some including terrain, don't render well and fail conversion) making the SKD examples fail. Astronaut demo is also pink. (failing texturing for the ground and buildings).
 https://imgur.com/a/FmG1BX6

**Comment by brnkhy** [comment]
@tjukic probably closed by wrong ticket/id or something.
I still haven't tried LWRP but standard shaders doesn't work there out of box right? That's probably the issue here. I wonder if there's a conversion method or we have to rewrite them all 🤔

**Comment by tjukic** [comment]
> @tjukic probably closed by wrong ticket/id or something.
> I still haven't tried LWRP but standard shaders doesn't work there out of box right? That's probably the issue here. I wonder if there's a conversion method or we have to rewrite them all 🤔

They don't. Cars don't move, buildings are pink. You can auto-convert some, but not all.
The real issue is more about the maps - tiles don't load.

**Comment by derekdominoes** [comment]
I have been looking into this. LWRP does not support the call in UnityTile.cs: `MeshRenderer.material.mainTexture = _rasterData;`
This is because 'mainTexture' modifies the Shader property "_MainTex" which does not exist on any of the LWRP Shaders. 

Most LWRP Shaders use a Shader property called "_BaseMap" instead. So you need to explicitly call it.
`MeshRenderer.material.SetTexture( "_BaseMap", _rasterData );`

However, if you don't supply a Material with a explicit LWRP shader to be used for the Tile Material, it seems to default to the LWRP shader 'Lit'.  This shader will multiply a color with the given raster data and it does not seem to default that color to white but gray. Not the desired look for satellite data on the terrain.

Supplying a desired terrain raster Material configured with an explicit Shader is likely best. Mapbox could default to choosing one it provides if the user doesn't supply one in the Tile Material setting or make setting the Tile Material a required field that the user must configure.

This is likely an issue also for TextureModifier.cs when "_useSateliteTexture" is given too.

Instead of ensuring that all parameters of supplied LWRP shaders are correct in order to get the desired results, it is very easy with the ShaderGraphEditor to create a custom shader that does exactly what is desired with no mistakes. 
![image](https://user-images.githubusercontent.com/16954767/56951924-9a8b3d80-6b6b-11e9-9287-7846ab0a25ee.png)

This will produce a Shader that you can use in your material without mistakes:
![image](https://user-images.githubusercontent.com/16954767/56952046-e50cba00-6b6b-11e9-9d69-24f2528ad901.png)

Note the 'Reference' in the Shaders property is called '_BaseMap" so that code can access it like the built-in LWRP shaders. But I called the Properties Name "RasterData" to better fit what it will be used for as shows up in the Inspector.

Hope this helps everyone debug and figure out how to use the LWRP with Mapbox.

**Comment by brnkhy** [comment]
@derekdominoes nice catch and thanks for the writeup! 🙏 
I guess an optional texture name field would be the best solution, might look little ugly in the ui but would solve this problem even for custom shaders and texture field names.

**Comment by colin-young** [comment]
@derekdominoes thanks for the details. It took me a little bit to figure it all out, so I'm going to document the bits I had trouble with (I may be an experienced developer, but Unity is still new to me):

* create the shader in the ShaderGraphEditor
* Create a new material and select the new shader as its shader
* In your map Game Object, under General -> Others select your new material for the Tile Material (this is the bit I had trouble with -- I knew I needed to assign a material or shader _somewhere_ but until I made the connection between "Tile Shader" and figuring that's literally what it was called in the editor...)
* Open up Mapbox/Unity/MeshGeneration/Data/UnityTile.cs and update `SetRasterData`:

```
MeshRenderer.material.mainTexture = _rasterData;
MeshRenderer.material.SetTexture("_BaseMap", _rasterData); // new line
RasterDataState = TilePropertyState.Loaded;
```

This "works for me" but I have no idea what would happen if I went back to the original rendering pipeline, etc. It seems to me the ideal solution would be if Mapbox could automatically detect if you are using the LWRP and provide and auto-select a LWRP material.

**Comment by brnkhy** [comment]
`f Mapbox could automatically detect if you are using the LWRP and provide and auto-select a LWRP material.`
this indeed might be an option. I'm not sure if there's a way to detect hdrp/lwrp on top of my head but I guess there has to be one. still though, that wouldn't work if you use a custom shader with custom texture field name. Having a texture field name textbox in inspector would be the only solution for that I guess. Maybe we can do a mixture of both hmm....

**Comment by colin-young** [comment]
One possibility:

* https://forum.unity.com/threads/hdrp-lwrp-detection-from-editor-script.540642/

At least that way you would only need to expose the texture field name when necessary. I'd think that if you're using custom shaders and textures you probably know enough to know that you will need to plug it in somewhere. It's not all that difficult to do -- I managed to figure it out after all with the help provided here.

I do think it would be really nice to have out-of-the-box LWRP support in Mapbox. It would continue the really slick "just works" magic, and, on my system (an antique mid-2012 MacBook Pro with a non-operational discrete GPU -- no nVidia, Intel HD 4000 only), the LWRP made a noticeable difference in how smooth the UI is. Plus it's much easier to set up anti-aliasing and other settings.

**Comment by brnkhy** [comment]
@colin-young 
`on my system (an antique mid-2012 MacBook Pro with a non-operational discrete GPU -- no nVidia, Intel HD 4000 only), the LWRP made a noticeable difference in how smooth the UI is.`
Oh I had no idea, only used it for a very short time myself but very happy to hear performance gain is good. We focus more on mobile anyway so we should totally support and maybe even suggest it as default then.

**Comment by 78Star** [comment]
Have this same issue and it has been around for six months now.

**Comment by derekdominoes** [comment]
If mobile is the business focus, yes it is more than worth it to default to LWRP. The performance difference with it is noticeable. Even in development on my gaming laptop.

**Comment by 78Star** [comment]
I just read the main LWRP documentation which says ["According to your needs, select either Upgrade Project Materials to LightweightRP Materials or Upgrade Selected Materials to LightweightRP Materials." ](https://docs.unity3d.com/Packages/com.unity.render-pipelines.lightweight@6.7/manual/upgrading-your-shaders.html)

**Comment by heath3n** [comment]
@brnkhy LWRP is being renamed to URP (Universal Render Pipeline) from 2019.3 onward and will become the default going forward. As it will feature in the 2019.4 LTS release and given the focus on mobile, I think it would very much make sense for this SDK to work with it out of the box. The Unity team states it is production-ready

https://blogs.unity3d.com/2019/09/20/how-the-lightweight-render-pipeline-is-evolving/

**Comment by Makio64** [comment]
URP Is recommended for mobile game now by unity and it would be great the SDK came with support out of the box, its a bad experience to came here after only 10minuts of using the SDK and realizing the materials have problems...

**Comment by Streamweaver** [comment]
> I just read the main LWRP documentation which says ["According to your needs, select either Upgrade Project Materials to LightweightRP Materials or Upgrade Selected Materials to LightweightRP Materials." ](https://docs.unity3d.com/Packages/com.unity.render-pipelines.lightweight@6.7/manual/upgrading-your-shaders.html) Also note for mobile that a lot of the VR platforms aren't supported yet.

This removes the pink material but I just get the black matrix on any map when it actually runs.  It's been awhile since there was an update to the SDK, is this dead?

**Comment by tjukic** [comment]
> > I just read the main LWRP documentation which says ["According to your needs, select either Upgrade Project Materials to LightweightRP Materials or Upgrade Selected Materials to LightweightRP Materials." ](https://docs.unity3d.com/Packages/com.unity.render-pipelines.lightweight@6.7/manual/upgrading-your-shaders.html) Also note for mobile that a lot of the VR platforms aren't supported yet.
> 
> This removes the pink material but I just get the black matrix on any map when it actually runs. It's been awhile since there was an update to the SDK, is this dead?

I don't think they're developing it any more. It's been stuck for quite a while now.

**Comment by brnkhy** [comment]
Rendering pipelines are simply hard to work with at the moment due to shader/material compatibility. If I change SDK to work with URP, it'll break all standard pipeline and URP is only default in 2020 builds which is not even out of beta yet. I don't find it reasonable to break all existing projects and everything for an unfinished and non-backward compatible feature of Unity. 

We'll probably officially switch when 2020 is the most used version and/or there is a way to check which pipeline is in use or something. 

I wrote a blog post about it recently; you can read about the issue and find a fix there; http://barankahyaoglu.com/dev/mapbox-unity-sdk-with-urp/
