### ISSUE TITLE
In Unity Worldscale AR Project SpawnOnMap script 3d object not positioning on specific lat. long. coordinates. How to perfect align map with spawned object?

### ISSUE THREAD

**Issue by dhruvmodhapp** [mapbox/mapbox-unity-sdk#1219]
* Unity version: 2018.2.16f1
  * Scripting Runtime Version: 
  * Scripting Backend: Visual Studio
  * API Compatibility Level: iOS 12.1
* Mapbox SDK version: v2.0.0
* The platform you're building to: iOS
- Hi, I am developing AR game with unity mapbox WorldScaleAR. I have an issue regarding a position of spawning 3d object. I am spawning 3d object with SpawnOnMap script on ARAlignedMap.

issue is the Positioning of my 3d object are different from given lat. long. coordinates. May be issue is happen due to map alignment.
Please help to solve this issue.

-  If in start of app iPad direction is towards the north(0), all object spawned at the correct location.
Sometimes map aligned with spawned object perfectly.

**Comment by jordy-isaac** [comment]
We've made some improvements to placing objects in AR space. We have branch up called `ar-foundation-port` up that you might want to check out. It uses ARFoundation instead of the deprecated ARInterface. Please note that this is a WIP branch. You may have to do some custom work to implement it how you want.

You'll also need to install ARFoundation as well as ARCore/ARKit from from Unity's package manager.

**Comment by dhruvmodhapp** [comment]
WorldscaleAR-ARF example inside `ar-foundation-port `branch, will work good with placing object in AR space? Can we achieve good alignment with WorldscaleAR-ARF? @jordy-isaac
