### ISSUE TITLE
Is still mapbox alive?

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1293]
Its more than a month ( almost two) that no new commits are done. Viewing history project every 2/3 months a new release is out...seems 5/6 months since latest release..

Thanks

**Comment by roura-12** [comment]
Mapbox is used in different applications and use cases ; many developers are interested by it (see issues branch) and there are modifications in v 2.1.0 
[https://github.com/mapbox/mapbox-unity-sdk/blob/develop/documentation/docs/05-changelog.md](url)

**Comment by jordy-isaac** [comment]
Hi @ejgutierrez74 We're very much alive. We have a release coming out soon which will include the ability to preview maps in the editor without entering play mode as well as other improvements. 

Is there something, in particular, you're looking for?

**Comment by ejgutierrez74** [comment]
@jordy-isaac  Well as ive told you im writing my thesis in video game using Mapbox, so i was worried about lack of movement these days. Im waiting for this new feature to preview maps in editor.

Also there are some bugs or things, like Flat terrain reported and updating my additions to Open Street Maps..

**Comment by MarjanPl** [comment]
ahem, no offence, but it is your responsibility to check for loading status before your game even starts.  Mapbox cannot help you with this - besides providing callbacks for status.

However i am also looking for an update - hoping for a working AR Worldscale demo in Europe.

**Comment by ejgutierrez74** [comment]
@MarjanPl  is there a way to check loading status before the game starts ? In tutorials i ve not seen anything similar, if you can pass me a link or an example. I use a CitySimulator based game with abstract map...

**Comment by dhruvmodhapp** [comment]
@jordy-isaac Please try to solve the issue regarding Worldscale-AR(Automatic Align) example for place object in the real world. Alignment should be work perfect. The current version of world-scale-ar having a big issue of alignment. Please, @jordy-isaac make sure it will solve.
- If the next version of world scale-ar with perfect alignment will help many developers to solve all pending project which is due to lack of perfect alignment in placing an object in the real world.
- @jordy-isaac now you and your teammate will be hope for us

**Comment by jordy-isaac** [comment]
Alignment is something that we're actively working on but it's also a current limitation of AR at large.
