### ISSUE TITLE
Characters falls becuse map not loaded fast enough

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1299]
@MarjanPl @jordy-isaac  is there a way to check loading status before the game starts ? 
So perhaps initizlize abstract map in awake instead of start...or a boolean or something that i can use, and dont put the character till i  "have a floor" to place it...

If not then could be a "enhancement" or "feature request", an option or something to load the abstract game before all the objects in the game.

In tutorials i ve not seen anything similar, if you can pass me a link or an example. I use a CitySimulator based game with abstract map...

Thanks
Related #1296

**Comment by roura-12** [comment]
I think that the map is not loaded fast because of an internet problem or because of the citysimulator map so try to use the map prefab instide 
the character is placed at design time and the map is loaded at run time ; I think that your character falls because you add a rigidbody and the gravity is checked 
you can see the location based game exemple and mapbox tutorials to see how to use characters
[https://www.youtube.com/watch?v=RhG1kfDBhgM&list=PL86WBCjNmqh4bDQycScKKlP0ETkjo39gG](url)
