### ISSUE TITLE
Two GameObjects in one scene (Astronaut game)

### ISSUE THREAD

**Issue by SophMue** [mapbox/mapbox-unity-sdk#1309]
The Issue:
My GameObject is following a path, provided by the EditorLocationArray. I want to make two GameObjects follow two different paths in one scene and at the same time to compare them. Is this possible? And if yes, how? If I just duplicate the scene or GameObject (in the Unity Editor) it doesn't work at all.
Do I have to make changes in the Scripts?

This is how it looks like in Unity with one GameObject:
![screenshot1](https://user-images.githubusercontent.com/47993460/54166887-998d3800-4467-11e9-866e-323d73031dbc.png)
![screenshot2](https://user-images.githubusercontent.com/47993460/54166897-a6119080-4467-11e9-94dc-82ee90082ebd.png)
at runtime with one GameObject:
![sceenshot3](https://user-images.githubusercontent.com/47993460/54166918-b6c20680-4467-11e9-9010-d3a1bde4fcb1.png)

If you don't understand my problem or need any further information, please ask.
I would be so thankful if anyone could help me.

Thank you in advance!

**Comment by jordy-isaac** [comment]
Can you provide a bit more info about what you're building? The EditorLocationProvider is meant to spoof the device location in the unity editor for debugging purposes.

**Comment by brnkhy** [comment]
@SophMue are you trying to move objects on roads or something? Because as @jordy-isaac said, 'EditorLocationProvider' isn't a good class for such use. I would suggest checking road layers in example scenes and see if a custom mesh modifier or game object modifier would help with your case. In example, mesh modifiers gets original and mesh data so you can put objects on roads using a custom modifier you write.
