### ISSUE TITLE
Use local position for feature placement

### ISSUE THREAD

**Issue by brnkhy** [mapbox/mapbox-unity-sdk#131]
We're currently using transform.position for feature placement, which I believe, makes unity to calculate position of all its anestors till the root and causing huge performance hit.
We're already using local position for everything inside tiles and we can get tile position easily (when/if necessary) anyway so this should be easy to change and probably save lots of performance.

**Comment by derekdominoes** [comment]
I would vote on in favor of issues 131.
I have translucent volumes extruded from polyline features. They have been cut up because of segmenting into tiles. But I don't want internal tile bounds walls to be seen or generated. So to remove them by looking for segments that run precisely E-W or N-S. Then I have to see if these segments match the tile's boundary coordinates. This last test must be done casting things to int. Works great but it did seem like int would be a more nature value for all of the work.
![image](https://user-images.githubusercontent.com/16954767/27587146-c5bfea76-5b75-11e7-8f2c-4e938a470d2c.png)

**Comment by brnkhy** [comment]
I did some quick tests and realized we actually don't have this problem as everything inside a tile rests at origin (local) and vertices are relative to that point so there's no placement going on anyway. (so building gameobject is in the middle of the tile but actual vertices and walls are in totally some other place in tile)

We will have to be careful for this when/if we change that. It'll probably be more useful if we change buildings to have their center where the actualy building is (not tile center), but it'll also be extra calculations (juuust a little bit though).

@derekdominoes your problem is a little different I believe, I'm planning to fix that by doing exactly what you suggested, not creating walls ontile edges but I'll do that after changing all mesh gen math to integer (from float) based system so it might take a while.
