### ISSUE TITLE
Navmesh from tiles

### ISSUE THREAD

**Issue by specsdhdeveloper** [mapbox/mapbox-unity-sdk#1320]
* Unity version: 2018.3.6f1
* Mapbox SDK version: 2.0.0
* Building to: Windows

I'm trying to build a navmesh from the mapbox tiles. My use case is for a static set of tiles (The extent of the area is fixed for the whole time the app is used).

I took a look at #122 to understand how to do it, however it seems to be for another version of the SDK and I'm unsure how to hook a custom `Terrain Factory` or a `AddMonoBehavioursModifier` to my `AbstractMap` since this is no longer documented.

How would you recommend I proceed ?
thanks

**Comment by brnkhy** [comment]
@specsdhdeveloper It has been a long time since I last did nav mesh generation but if I remember correct, I was able to do it by attaching a monobehaviour to target planes and system automatically did it. I guess this was the unity repo for that; https://github.com/Unity-Technologies/NavMeshComponents

As you said you'll need a way to add that script on tiles though. If it's a fixed sized region and you only need terrain, I guess easiest way would be interjecting tile stuff after generation. 
One way would be registering to map finstate changed event (in abstract map visualizer I think) and then go add that script to all of them. 
Another way would be getting tile events (just merged into dev branch yesterday), and adding script to tiles on finished events.
But I think first one make much more sense (and much easier) for fixed area maps.
