### ISSUE TITLE
API for another tileset REST web service

### ISSUE THREAD

**Issue by victtersh** [mapbox/mapbox-unity-sdk#1335]
I want to get access to tilesets (raster) uploaded to a different backend,  at the same time with tilesets from Mapbox backend. I would blend two(or more) textures and project them on a plane.
As I understood Mapbox.Map.TileResource is mostly responsible for building URLs to Mapbox backend and it's definitely not extendable. Am I right that I need to implement my own way to get tilesets from another backend and Mapbox API  doesn't provide such functionality?

**Comment by heath3n** [comment]
I hate to be the "+1" guy but it's unclear how issues get prioritized here so I'll add my voice to this ticket. This is similar to my use case where users should be able to create buildings and have them saved as GeoJSON to be visible to other users (co-existing with current Mapbox buildings).

**It would be really great to be able to add multiple data sources to a map in the form of URLs that we would have to ensure returned data in a Mapbox-specified format.**

Failing that, I think @brnkhy's tile events PR (https://github.com/mapbox/mapbox-unity-sdk/pull/1325) could be used in order to detect when tiles are being loaded so we can know when to retrieve our own data, but rendering that to the map is something I wish were clearer.

**Comment by brnkhy** [comment]
Hey @victtersh and @heath3n 
If we're talking about another tile map source, I think best solution is hooking up to tile events as @heath3n suggested. With that branch, you'll get tile registered and tile finished events so you can get registered tile id, query your own server using it and process your custom data.
Other than that, I think it wouldn't make too much sense for Mapbox SDK to support third party servers and data.
@heath3n about rendering custom data; you're right it's really not obvious/intuitive at the moment but you can use existing modifiers to visualize custom vector data, outside of the SDK structure. You can find a small example of it in `TrafficAndDirections` demo scene. `DirectionsFactory` class there uses loft modifier to create path mesh. You can always do something similar even with multiple modifiers.

**Comment by victtersh** [comment]
@brnkhy Thanks a lot and a great work you have done with Mapbox SDK!
