### ISSUE TITLE
Micro lags while working with tile layers.

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#1341]
Using Unity 2018.3.51f and mapbox 2.0.0...

I experienced a "massive" fps drop when using the tile layer feature ( Streets tile set ) in the abstract map class... currently im using it to determine the water/waterways... so i attach a custom but pretty simple script to the water tiles for just referencing the colliders... no update methods, just a simple start method...

When i disable those features, map scrolling is fine and doesnt lag... once i start using the feature i will receive micro lags regulary while scrolling...

Any ideas how to prevent this ? Or is there a way to just run this once on startup to determine the water tiles without doing it during map scrolling ? Using this, it would only micro lag on start and not while scrolling...

Any help is welcome !

**Comment by brnkhy** [comment]
Hey @genaray ,
If I understand it correct, you're generating colliders on water/waterways on their creation right? Collider initialization might be the problem here as it's a costly operation. As far as I remember, object mesh is passed to collider, it's all registered to physics modules etc etc. And since it's all unity and even worse, physics, it's not possible to thread these kind of stuff.
First of all, have you checked profiler to see if there's anything else is causing this it? That's still a possibility of course.
If not, and your region has a lot of water/waterway to cause these hiccups, I guess only thing I can suggest is caching them and adding colliders slowly in a certain time frame, like N colliders per frame etc.
