### ISSUE TITLE
Any ETA to new release ?

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1368]
All of the releases in mabox-unity-sdk looking to the releases history are delayed between 1-3 months at most. Now is more than 6 months from latest release....so any eta to new version ? Also seems not many movement and commits in master branch as used to be...

Thanks

**Comment by brnkhy** [comment]
Hey @ejgutierrez74!
We had some bad luck with the latest release. Indeed it was supposed to be release months and months ago but it kept getting delay for various and mostly non-technical issues. At the moment we're waiting for a few back-end related changes and we'll release new version compatible to those etc. I'm really hoping it'll be out in 1-2 weeks. We love frequent small releases but this one keeps getting bigger and bigger.

Since we were `just about to lunch` past few months, we've been pushing new stuff on a release branch instead of dev branch. Few weeks ago we decided to merge that release branch into dev so all new changes should be there now. There are lots of PRs merged in last few months but the bigger ones (that was supposed to be the thing in this version) was merged much before. Then we didn't want to get into another big thing before this one is out.  

Hope that explains it :)

**Comment by ejgutierrez74** [comment]
Thanks
@brnkhy at hope it would be included the multithread and offline map ( with a configure size). When i run my project in different computers, i get my character falling infinite as it doesnt touch with feet the ground ( character is falling from 50 units and using gravity to get to the map). Id try to send a mail to help@mapbox.com explaining the case....

**Comment by brnkhy** [comment]
@ejgutierrez74 Offline map or multithreading won't be in this version but you shouldn't need them for that problem anyway. Have you tried using map events? If I remember correct we have `Map.MapVisualizer.OnStateChanged` event which let's you know when map is finished so maybe you can start your logic/physics/player after that?

**Comment by ejgutierrez74** [comment]
Can you put an example of how to use it, i havent found anything similar ? I have another issue that if offline was  not possible, perhaps we could load our AbstractMap ( in my case) onAwake instead on onStart as of Unity's initialisation functions. 

Also would be nice to have something like boolean as you commented that returns true if map has been loaded and false in other case. 

`if ( myMap.isLoaded== true) {`
 begin( game)

Thanks for your help

**Comment by brnkhy** [comment]
@ejgutierrez74 I think `LoadingPanelController` class is using it to show/hide a ui gameobject for example. Should go something like;
```
var visualizer = _map.MapVisualizer;
visualizer.OnMapVisualizerStateChanged += (s) =>
{

}
```

I would strongly suggest not relying on awake/start order for anything and try to handle it using events and stuff.

**Comment by ejgutierrez74** [comment]
> Hey @ejgutierrez74!
> We had some bad luck with the latest release. Indeed it was supposed to be release months and months ago but it kept getting delay for various and mostly non-technical issues. At the moment we're waiting for a few back-end related changes and we'll release new version compatible to those etc. I'm really hoping it'll be out in 1-2 weeks. We love frequent small releases but this one keeps getting bigger and bigger.
> 
> Since we were `just about to lunch` past few months, we've been pushing new stuff on a release branch instead of dev branch. Few weeks ago we decided to merge that release branch into dev so all new changes should be there now. There are lots of PRs merged in last few months but the bigger ones (that was supposed to be the thing in this version) was merged much before. Then we didn't want to get into another big thing before this one is out.
> 
> Hope that explains it :)

Seem mapbox is not active, no commits or PR from two months...We have to be worried about mapbox for unity future ?

**Comment by brnkhy** [comment]
I guess we can close this now :)
