### ISSUE TITLE
Is the documentation updated?

### ISSUE THREAD

**Issue by Jorgee97** [mapbox/mapbox-unity-sdk#1372]
Hello everyone,

I'm working with mapbox on unity, but I was wondering if the unity documentation at this link https://docs.mapbox.com/unity/maps/overview/custom-maps/#use-custom-data is up to date? because I cannot see the "Add Visualizer" button or option anywhere.

these are the only options I can see on the map object that comes in the prefab folder of mapbox.
![image](https://user-images.githubusercontent.com/8935477/58068199-06067080-7b56-11e9-8153-d3da891e6de4.png)

**Comment by colin-young** [comment]
Those docs are a bit out of date I think. You need to add a feature, then you will have controls for modeling and texturing below. There is no "Add Visualizer" option in 2.0 that I can see. I think they have been replaced with Mesh and Game Object modifiers. I'm sure a Mapbox dev will chime in and provide a more detailed and accurate description, but this should get you going.

**Comment by brnkhy** [comment]
@Jorgee97 @colin-young 
I think some small sutff is a little bit outdated but `Add Visualizer` should be exact;y same button with current `Add Feature` I believe and only renamed because `feature` is a little more intuitive. 
Main class responsible for visualizing a given layer (feature type) is called `Layer Visualizer` in the SDK. i.e. one layer visualizer for buildings, one for roads etc. 
So technically it's a `visualizer` hence the old button text. But of course `visualizer` all alone doesn't say much so we changed it to `feature` as in `add new features (building, road etc) to the map`.

Hope that explains it! Sorry for the confusion 🙏 

cc @jordy-isaac

**Comment by Jorgee97** [comment]
Thank you both @colin-young and @brnkhy for your answers, it helped me a lot.
