### ISSUE TITLE
Route not aligned with map perfectly.

### ISSUE THREAD

**Issue by hsianchen** [mapbox/mapbox-unity-sdk#1373]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version:  2018.3.10f1
* Mapbox SDK version: 2.0.0
* The platform you're building to: Android
* A description of what you're trying to do: 
I'm working on a school project which is built with mapbox-unity-sdk. The project is based on the sample scene WorldScaleAR and I added Directions prefab to show the route. The ideal working process is when the users select a building, then the map shows the direction. The problem is that the map rotates so the route isn't on the correct place.  It's like when I turn the map rotates. How to stop the map(or directions route) from rotating? I've attached the video.
[Click Here](https://youtu.be/ZwjRg-k8MDA)

**Comment by brnkhy** [comment]
@hsianchen it looks like ar (device) is rotation the map (but not the whole world?) instead of the camera. I think the easier solutions would be changing directions factory to create road object under map OR (and even better) apply map rotation value to road object every update (so rotate road object itself). Would that help?

**Comment by hsianchen** [comment]
@brnkhy Thanks! I found the solution. I unchecked the `UpdateMapWithLocationProvider` script and it worked fine. But thanks for reply!
![update](https://user-images.githubusercontent.com/25290748/58486399-5ace6a80-8198-11e9-857f-9c63ddb7e972.jpg)
