### ISSUE TITLE
Velocity for player animation from a calculation from Mapbox.Unity.Location?

### ISSUE THREAD

**Issue by michaelcuneo** [mapbox/mapbox-unity-sdk#1387]
I have animations set up for my player... but the updates only happen about once a second so I can't seem to get any velocity to really affect the players animation states. 29 frames I have 0, then for one frame I get an update, as the player jumps from the old location to the new location..

Anyone solved how to move the player there fluidly, along with it's animation?

**Comment by brnkhy** [comment]
@michaelcuneo are we talking about player character animations for location based games? In that case I would suggest, attaching an empty gameobject to location updates instead of the player itself. This invisible object will jump around and you player character will slowly walk towards it (when distance is above a threshold) smoothly. At least that's what I used in the past. Hope that helps!

**Comment by michaelcuneo** [comment]
Ahh, so I make a GameObject MoveTarget, and use that for the Immediate Position and Rotate scripts, then script move the character to the MoveTarget... thanks. That would be perfect. I can probably leave root motion on now and it'll just calculate it all accordingly, way better solution. :)

**Comment by brnkhy** [comment]
I'm not sure about root motion but I don't know much about animations anyway. Just trying to say, gps is jumpy so let another invisible point jump and smoothly lerp you player to that jump point. I think Astronaut game demo scene does that actually, have you checked it?
