### ISSUE TITLE
Insane performance drop

### ISSUE THREAD

**Issue by levigeers** [mapbox/mapbox-unity-sdk#1395]
* Unity version: _Unity 2019.1.1f1_
  * Scripting Runtime Version: _.NET 4.x Equivalent_
  * Scripting Backend: _Mono_
  * Api Compatibility Level: _.NET 4.x_
* Mapbox SDK version: _2.0.0_
* The platform you're building to: _Windows_
* A description of what you're trying to do: _I am trying to make map with routing for a game. But when I move the map around I get insane lags. When I check the profiler I can see spikes of 10000ms (yes..10 seconds) and more. When I go down to check what it is it keeps pointing to the UpdateMap function in the AbstractMap. This somehow takes ages to execute. And its not just our scene, the demo scene is just as bad. Now the PCs we have are not that good at all for today's standards (i7-3k, gtx660 and 16gb ram), but our customers don't have a good PC either._

**Comment by brnkhy** [comment]
@levigeers It shouldn't be that slow but can't say anything with information you provided. Any chance your scene is loading too many tiles with too many buildings? Can you tell me which demo scene takes more than one second to `update`? Any chance there's a error log spam which is extremely slow in unity? 
If it's that bad, there's something obviously wrong but I'll need some more help to pin it down.

**Comment by levigeers** [comment]
No we were using the flat 2d map. It was a duplicate scene of one of the demo scenes (zoomable map). And no there is no console spam going on. The profiler keeps pointing to the UpdateMap function. Maybe you could see the problem there.

**Comment by brnkhy** [comment]
@levigeers I'm afraid you're not giving me anything at all to investigate. ZoomableMap demo scene is nowhere that slow, otherwise no one would have been able to use it at all with 10second freezes per tile load. There's something else wrong on you end/setting. If you enable Deep profile (which will slow down everything a lot more), you might be able to see what's wrong under `UpdateMap` as well.

**Comment by Markovicho** [comment]
Unity 2019.4.1f1
Mapbox v 2.1.1


At lest i can confirm that zooming / reloading tiles is causing large performance drops leading to an small application freeze (~1sec). Thats resulting in a very bad look and feel for interactive 2D Maps.

Using DeepProfiler i can trace back this peak to the loading of the tiles (refer to screenshot):

![image](https://user-images.githubusercontent.com/11967926/86372604-b19f5100-bc82-11ea-9ab4-1813efb8509e.png)

Maybe there is at least an workaround or the root of the problem is some kind of tileset/layer related problem ?

**Comment by brnkhy** [comment]
@Markovicho spikes indeed happen :( This is mostly due to texture operations. i.e. when you zoom in or out, all tiles change in a single frame which means loading 5-20 tiles depending on scale. For each image on that tile (satellite, elevation, style etc), we have to call `Texture2d.Load` which is strictly main thread and takes 30-40ms per image if I remember correct.
Unfortunately there is no easy solution to this. Unity simply doesn't have async texture operations. 
One solution is using a 3rd party library for image processing and then thread that. We do not prefer that because a third party dependency for a sdk is a bad-ish idea and ensuring its working on all platforms won't be easy.
Another solution is using a totally different system for image loading and doing some hacks. I'm working on it at the moment but I'm not sure when it'll be ready to release (or if ever, it's just experimental at this point).

**Comment by Markovicho** [comment]
@brnkhy 
Unfortunately the described performance drop is a pretty irritating issue in terms of usablity (look & feel) as well as draining the battery faster. 

But this could be at least sorted out a bit by this news:

`We optimized Texture2D loading for consoles in Unity 2020.1 by moving the texture swizzling offline and loading directly to GPU memory. Performance gains are up to 30% for a 2D texture load, depending on texture size and platform.`

refer to this article
https://blogs.unity3d.com/2020/09/21/new-performance-improvements-in-unity-2020-2/

**Comment by Markovicho** [comment]
Another pretty interesting investigation in want to share :

I made a testscene to switch between the zoomlevel 12 and 14 in two different ways:

```
AbstractMap map; // scene reference

map.SetZoom(zoomLevel) // Option 1
map.UpdateMap(Map.CenterLatitudeLongitude, zoomLevel); // Option 2
``

Screencast:

[https://drive.google.com/file/d/1dc22ANac6DZvUKD9vs7_4MtgkQ9EOLLU/view?usp=sharing](https://drive.google.com/file/d/1dc22ANac6DZvUKD9vs7_4MtgkQ9EOLLU/view?usp=sharing)

Calling SetZoom will freeze the application for several seconds. Using UpdateMap based on the current lon/lat with the desired zoom level runs much faster. The same way of zooming is used in the example scene "ZoomableMap". Maybe i was calling changes of the zoomLevel in a false way before and the biggest bottleneck is not in the Unity TextureLoading itself (?)

**Comment by Markovicho** [comment]
@brnkhy Maybe i can give this (closed) topic some relevance with a new investigation. It seems like Texture2d.Load is not the only bottleneck and maybe not the biggest. I took a second look into the profiler while struggling with huge performance issues on implementing a pretty basic automatic zoom feature. We already avoid using camera movements or locationswitches to reduce the spikes as for as possible. 

In the spikes the performance gets reduced by two bottlenecs:
**~30 % are spent into LoadImage
~40 % are spent into Decompression based on GZip**

Maybe switchting to a more efficient way of decompression could make the Unity related issue of loading textures more bearable. 

Sorry for persisting onto this topic but it's a very hard bottleneck which is causing technical feasibility problems on simple projects. At least we hope that we can provide some helpful informations to push the troubleshooting.
