### ISSUE TITLE
Implement floating origin

### ISSUE THREAD

**Issue by NinjaDanz3r** [mapbox/mapbox-unity-sdk#141]
Use case:
Player/camera/user moves from one part of the scene to another point far away.

Currently if using 1 to 1 scale moving too far away from origin will introduce floating point errors, and applying the floating point origin (http://wiki.unity3d.com/index.php?title=Floating_Origin) will only help so much when getting camera Lat/Lon through
 `Camera.main.transform.GetGeoPosition(map.CenterMercator, map.WorldRelativeScale);`.

Perhaps the floating point origin can be integrated into the MapBox Unity SDK in a way that makes it more internally consistent, i.e storing a lat/lon offset when transitioning.

I know that the problem can be partially resolved by scaling down the map, but I still would prefer to not have to do that.

Additional reference (including mentions of other GIS implementations):
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.471.7201&rep=rep1&type=pdf

**Comment by brnkhy** [comment]
@NinjaDanz3r we had similar plans by changing the reference point/tile as camera moves, which I implemented for MapzenGo project back in last year. I didn't know about that script though, if I'm not mistaken, it's fetching everything in one frame and will cause a huge freeze if your world is big & populated. Have you tried that out?
I totally understand the issue and need for it though and our structure should be quite suitable for it as well.

**Comment by NinjaDanz3r** [comment]
@brnkhy Correct, it's not terribly optimized for a large number of objects but it works decently. I'm still working on a solution that offsets the world position but I believe that a little stuttering every 100km (the approximate amount of Unity units until floating point errors occur) is acceptable.

**Comment by brnkhy** [comment]
@NinjaDanz3r you can easily fix that hiccup as well by simply not using `FindObjectsOfType`. You can find the list of existing tiles under `MapVisualizer` and you can simply move them as they parent everything else anyway. Or even better you can move the root object I guess. But don't forget to update reference point or new tiles will be placed wrong.

**Comment by david-rhodes** [comment]
Partially completed in `develop` with the new `DynamicZoom` example/implementation!

**Comment by skyspy** [comment]
@ NinjaDanz3r @brnkhy I have been reviewing implementations of floating origin and have a question about your implementation of http://wiki.unity3d.com/index.php?title=Floating_Origin.
@brnkhy mentioned the execution of the script every frame: do you execute it every frame or every time the user moves/changes viewpoint. i.e. if it is every frame then when the player is not interacting - just starting at screen - is it still being executed?

**Comment by brnkhy** [comment]
@skyspy oh wow this is an old ticket :D
We're not doing this anymore actually. Currently, most regular maps (demo scenes) simply doesn't take floating point limitation into account but because of the scaling, it will be very hard to reach that point anyway.
Only ZoomableMap demo scenes has a different positioning logic where map is always located at the origin so you'll never be able to reach that limit and can travel around the world with ease.

**Comment by skyspy** [comment]
Thanks baran.
I have just stumbled on mailbox and from the little i have seen it looks
impressive. I will not be able to take a closer look for a while, but would
like to get an idea of what method us used on zoomable maps. Just at a high
level, anyway. Is it ok I email you a question or two?

**Comment by skyspy** [comment]
I mean mapbox: autocorrect is a problem sometimes

**Comment by brnkhy** [comment]
@skyspy Other demo scenes keep starting point unchanged and add new stuff relative to that starting point. `Zoomable map` scene however moves that starting point (almost exactly like floating origin really but with more focus on camera and its frustrum) so world moves occasionally and new tiles are always in a certain (small) range of the world origin.

Using slack for questions would be much better if you can abstract questions to pure technical level and leave private business stuff out, as everyone can see&answer them before me as well. 
Otherwise, sure you can always mail me; baran.kahyaoglu@mapbox.com
