### ISSUE TITLE
Blur satellite image when using worldscale in ZoomableMap example

### ISSUE THREAD

**Issue by jernkuan** [mapbox/mapbox-unity-sdk#1421]
Unity Version : 2018.4.2f1
Mapbox SDK version : 2.0.0

Platform building : Windows

I'm trying to use mapbox in world scale on a desktop environment. Loading up mapbox example ZoomableMap and changing the map scaling options to WorldScale cause the map to be not loaded properly, but rather just fuzzy at all zoom levels.

Is WorldScale supposed to work on non AR environment?

**Comment by brnkhy** [comment]
zoomable map demo shows a very large area which wouldn't work well with world scale settings due to floating point precision and texture resolutions. World scale would work better with smaller areas on higher zoom levels. Fuzzyness is probably due to 512x512 texture being stretched to a huge mesh/plane as well. Why do you want to use world scale for a non-ar app in the first place?
