### ISSUE TITLE
Place object at certain altitude above ground.

### ISSUE THREAD

**Issue by huvarda** [mapbox/mapbox-unity-sdk#1447]
Is there a way to place a 3D object at a certain altitude in meters above the terrain? I have looked for this for a while but all I could find was how to access the elevation of a point on the map, rather than above.

**Comment by brnkhy** [comment]
Hello @huvarda!
I never tried that I believe but shouldn't be too hard. Once you have the point, you can query for elevation. Then using the `pointElevation + tile.TileScale * AltitudeYouWant`, you should be able put it where you want. Critical thing here is TileScale, that's how you convert real world meters to unity space units.

**Comment by huvarda** [comment]
How exactly do I find the tile scale?

**Comment by brnkhy** [comment]
@huvarda I assumed you're working on a tile initially but if you're not, since all tiles use same scale at the moment, you can just get any tiles scale `AbstractMap.MapVisualizers.ActiveTiles[0].TileScale` should work.
Proper way of course would be finding current tile you're working on, with something like;
```
MapVisualizer.ActiveTiles.TryGetValue(Conversions.LatitudeLongitudeToTileId(latlong.x, latlong.y, (int)Zoom), out tile);
```
