### ISSUE TITLE
Is it possible to get Scalebar in Unity?

### ISSUE THREAD

**Issue by ta-cpc** [mapbox/mapbox-unity-sdk#1451]
Not a bug, is it possible to get a scalebar in the Unity version of the SDK? Skimmed through the API but couldn't find anything

Thanks

**Comment by brnkhy** [comment]
Hey @ta-cpc !
Can you elaborate what do you mean by `Scalebar`? I'm afraid I'm not familiar with it :(

**Comment by ta-cpc** [comment]
Hello @brnkhy

So the thing I was mean to say was linear scale (https://en.wikipedia.org/wiki/Linear_scale), you know the little bars you find on maps that tells you the distance i.e. 1cm = 10km

**Comment by brnkhy** [comment]
@ta-cpc Ah I see. There isn't one available in SDK at the moment but it shouldn't be too hard to calculate the value.
Meter to unity space distance will change for each tile because of the mercator projection but for any tile, you can get tile edge size (iirc in meters) using `tile.Rect.Size.x`. Then you also know the tile size set in AbstractMap inspector, which is 100 by default.
So very roughly,
`AbstractMap.MapVisualizer.ActiveTiles.FirstOrDefault().Value.Rect.Size.x / 100`
should give you a reasonable value.
Hope that helps!

**Comment by brnkhy** [comment]
Heey  I did this a while ago, probably forgot to post here; https://github.com/mapbox/mapbox-unity-sdk/tree/scaleBar

**Comment by SheZii00** [comment]
@brnkhy Hi
I'm trying the same thing but still couldn't find a way to do so in Mapbox Unity SDK. And the link you provided doesn't work. Maybe you could update the link or guide me on how to have that ScaleBar.

I have tried the information you provided about tile sizes, but that doesn't work. It doesn't update for each zoom level, but it only updates when tile sizes change.

Thanks in advance

**Comment by OozoraCielo** [comment]
@SheZii00 Hello
Were you able to do it? I also need to do make a scalebar for Mapbox Unity SDK

@brnkhy Can you please update the link

Thank you!
