### ISSUE TITLE
How to track building meshes split between tiles?

### ISSUE THREAD

**Issue by Laguland** [mapbox/mapbox-unity-sdk#1453]
* Unity version: 2019.1.8f1
* Mapbox SDK version: 2.0
* The platform you're building to: Windows

Hi!
I wrote a feature modifier which changes color of specific buildings depending on their lat long but I have noticed that if building is on the border of the tiles the color will apply only to one side. Is there any way to track split building or even prevent them from dividing? For example by some kind of id so I can apply color to objects with given id?

**Comment by brnkhy** [comment]
@Laguland You can change vector tileset to `streets with building ids` which will prevent buildings getting cut at tile edges all together and probably fix your problem. Hope that helps!

**Comment by Laguland** [comment]
Hi, thanks for an answer but it didn't fix my problem. 
This is how my building modifier looks like:
![1](https://user-images.githubusercontent.com/9934539/64428293-aeaff000-d0b3-11e9-8b98-48a29102c44e.PNG)

And here is how it looks on the map:
![2](https://user-images.githubusercontent.com/9934539/64428324-bf606600-d0b3-11e9-8201-660fe5d28848.PNG)


I have selected data source "Mapbox Streets With Building Ids". I have tried to experiment with VectorEntity.Feature.Data.Id but it seems to be unique only within the tile.

**Comment by Laguland** [comment]
I can add that selecting "Buildings with unique Id" under Behavior Modifiers (while using mapbox streets with building ids) only makes all buildings disappear.

**Comment by brnkhy** [comment]
@Laguland that's probably due to wrong setting, that checkbox should only be selected if building id tileset is selected as seen below;
![AsPowerBar_2019-09-09_18-36-53](https://user-images.githubusercontent.com/1465390/64545190-f8f1d500-d330-11e9-9354-be3d43a6a8f5.png)
notice data source at top and then the checkbox in the settings. Have you tried like this?

**Comment by Laguland** [comment]
@brnkhy yes, I have selected it. 

Settings with Ids:
![1](https://user-images.githubusercontent.com/9934539/64598384-ed95bc80-d3b7-11e9-8699-cc4052df98c6.PNG)

Settings without Ids:
![2](https://user-images.githubusercontent.com/9934539/64598397-f1c1da00-d3b7-11e9-8a9b-908f25f1eacf.PNG)

I also tried to clear cache.

**Comment by highpockets** [comment]
> @Laguland that's probably due to wrong setting, that checkbox should only be selected if building id tileset is selected as seen below;
> ![AsPowerBar_2019-09-09_18-36-53](https://user-images.githubusercontent.com/1465390/64545190-f8f1d500-d330-11e9-9354-be3d43a6a8f5.png)
> notice data source at top and then the checkbox in the settings. Have you tried like this?

@Laguland is correct, the suggested fix does not work all of the time. I have my setup like so:

![Screen Shot 2020-12-31 at 3 14 23 PM](https://user-images.githubusercontent.com/3467943/103413678-dfeee200-4b7a-11eb-8c46-c22d950a1f54.png)

In particular there is an issue where smaller "buildings" (rooftop structures is what they are really) from one tile will be placed on top of a building from another tile. I was trying to find the base building below the rooftop structure, but, because of this issue, if the base building was not found by testing renderer extents radius of each of the tile's buildings to see if the structure was within the bounds, I had to iterate through the tiles to find the closest four tiles to the rooftop structure and then iterate through the child buildings to find the one that had the structure within renderer bounds extents radius. I don't want to use colliders because it would be the only thing I need them for which seems a little overkill even if I were to disable them after finding the said buildings with a raycast. It would be helpful to have all rooftop structures on the same tile as the base buildings which the structures sit.
