### ISSUE TITLE
Object is spawned at player position

### ISSUE THREAD

**Issue by eko111** [mapbox/mapbox-unity-sdk#1474]
Hello,

I'm using spawn script to spawn objects at some coordinates. Spawning is working but when I run the game for some reason my object is in the beginning spawned at the place of player and then is moved to a given coordinate. This is problem because player and spawned object are colliding. I want that object is spawned far from my player. 
![saveGame](https://user-images.githubusercontent.com/54671121/65578757-bc4feb80-df76-11e9-835e-8b74df8571b0.jpg)

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3.0f3
* Mapbox SDK version: 1.4
* The platform you're building to: Android

**Comment by brnkhy** [comment]
@eko111 this is probably because map isn't loaded at first so everything snaps to zero until map loaded and all necessary coordinates are calculated etc.
You can register to `AbstractMap.MapVisualizer.OnMapVisualizerStateChanged` event for map loaded signal for example and start spawning objects after that.
