### ISSUE TITLE
Raycast on object

### ISSUE THREAD

**Issue by ukeOnFire** [mapbox/mapbox-unity-sdk#1483]
I am trying to select an object/unity tile that has been spawned onto the map with a dataset. 
It seems that the raycast never returns a hit. 

Without much further ado, here's my current code I am using to project the raycast: 
`RaycastHit hit;

            Ray ray = _camera.ScreenPointToRay(Input.mousePosition);
            if (Physics.Raycast(ray, out hit)) {
                Transform objectHit = hit.transform;
                
                Debug.Log($"HIT");

                // Do something with the object that was hit by the raycast.
            }`

This is happening in the TouchCamera-Script which is assigned to the MapCamera in the WorldAlignmentKit-prefab.
The property LocationProvider of the script TouchCamera is unassigned.

Any hints, questions and solutions are much appreciated!

**Comment by ukeOnFire** [comment]
In case it is relevant: I disabled the DebugCanvas.

**Comment by brnkhy** [comment]
@ukeOnFire I'm afraid this can be caused but a number of different things. First thing comes to my mind is, if the object has collider for example.
I'm not sure how TouchCamera works but rays might be off because of a different camera setup as well. I'm afraid I won't be able to help much with this but I can assure you, SDK simply places a prefab on world space so raycast should work normally (so there's no fancy magic going on there).

**Comment by supergra** [comment]
I have a similar problem, but specifically on a simulation startup. A raycast won't work for the first 1-2 time steps after loading the map, but then it will start working. There may be something going on with colliders, but I couldn't figure it out. I eventually had to add hacky code to wait until the raycast returned a sensible result and then start using it.

**Comment by brnkhy** [comment]
@supergra can't really say much here :( I mean if tiles are loaded and they have colliders, it should at least hit the tiles.
closing this for now but please feel free to reopen if necessary.
