### ISSUE TITLE
How to create Navmesh in new version

### ISSUE THREAD

**Issue by wangguanmusic** [mapbox/mapbox-unity-sdk#1506]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: Unity 2019.1
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: v2.1.1
* The platform you're building to: IOS

Hi, I am trying to create a scene that 3d objects could be wandering along the street in Mapbox. I know that Navmesh could be a good way to do it. I tried to follow some of the instructions in medium but it seems they are using the old mapbox version. So could someone tell me how to create navmesh in the new Mapobox version? Thank you so much

**Comment by abhishektrip** [comment]
@wangguanmusic You can still use the instructions to create `RoadNavMeshModifier` mentioned in this blog https://blog.mapbox.com/placing-ar-portals-all-over-the-world-pt-2-1470b0f70281

To add Modifiers to a layer, use `Behavior Modifiers` section instead of adding them to stack. 
![image](https://user-images.githubusercontent.com/32286016/68902115-50733f00-06ec-11ea-95e7-8f87e550208f.png)

**Comment by richieprice** [comment]
@wangguanmusic 
hi! did you figure this out? i have been trying the exact same thing with no success...
