### ISSUE TITLE
Mapbox Studio vs Mapbox Unity SDK quality differences

### ISSUE THREAD

**Issue by anolan23** [mapbox/mapbox-unity-sdk#1511]
In Unity, we want to recreate the quality of maps shown in Mapbox Studio or even similar to the Simple Map example shown on your website:

https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

One issue is that the label sizes are resizing perfectly on your website examples, but are not smoothly resizing in Unity. Are there scripts that I am missing or settings I am not checking? It’s a little misleading

**Comment by brnkhy** [comment]
@anolan23 that's because we don't support labels in th SDK (out of box)  at the moment and you're using them through a mapbox styles and raster images. I'm afraid this is inevitable with raster images unless you restric camera movement (prevent it coming too close etc).
You can also create your own system to create labels in unity and align them with roads/splines but and it shouldn't be too hard but unfortunately label placement logic isn't that trivial (which oneto show, where to place them etc).
