### ISSUE TITLE
error: MissingComponentException: There is no 'MeshRenderer' attached to the "6/12/25" game object, but a script is trying to access it.

### ISSUE THREAD

**Issue by veyvin** [mapbox/mapbox-unity-sdk#153]
In branch  origin/editor-turnstile and develop(time 2017-7-11) , MapVisualizer.cs  maybe have problem.please watch this video https://drive.google.com/file/d/0B7C4MTFgUulkeHk1MWlnN3lsSEk/view?usp=sharing,  online will maybe blurry,download it.

**Comment by brnkhy** [comment]
@veyvin interesting but actually by design terrain factory should always go before image factory. unfortunately we do not have custom inspector to check & fix that at the moment.
Can you reproduce this with terrain factory being the first in the list as well?

**Comment by david-rhodes** [comment]
@veyvin @brnkhy is correct. `TerrainFactory` is responsible for attaching the mesh renderer to the tile gameobject itself, so it needs to be placed first in the list of factories. We should probably just make this a lazy `AddComponent`, however.

Thanks for posting this issue. FWIW, this is really only noticeable since we have added disk caching (data is available before terrain is generated). 😏

**Comment by david-rhodes** [comment]
@veyvin Please let us know if our suggestions did not help with this problem. Thanks!
