### ISSUE TITLE
Assembly reference missing with new version of unity?

### ISSUE THREAD

**Issue by StarKing777** [mapbox/mapbox-unity-sdk#1584]
I am using Unity 2020.1.0b4.3439

and it is now giving me 4 compile errors

Assets\Mapbox SDK\UnityARInterface\Scripts\ARKitInterface.cs(26,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)

Assets\Mapbox SDK\GoogleARCore\SDK\Scripts\ARCoreBackgroundRenderer.cs(43,17): error CS0246: The type or namespace name 'ARBackgroundRenderer' could not be found (are you missing a using directive or an assembly reference?)

Shader error in 'Unlit/ARKitLWRPBackground': failed to open source file: 'Packages/com.unity.render-pipelines.lightweight/ShaderLibrary/Core.hlsl' at line 29 (on d3d11)

Compiling Fragment program
Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS

Shader error in 'Unlit/ARKitURPBackground': failed to open source file: 'Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl' at line 29 (on d3d11)

Compiling Vertex program
Platform defines: UNITY_NO_DXT5nm UNITY_ENABLE_REFLECTION_BUFFERS

no idea how to fix this

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 
  * Scripting Runtime Version: 
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 
* The platform you're building to:
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by horatiu665** [comment]
Do you need AR functionality? otherwise they advise deleting the AR part of mapbox sdk... in any case it is using an old implementation instead of the newest ARFoundation, so it is of not much use.

**Comment by StarKing777** [comment]
> Do you need AR functionality? otherwise they advise deleting the AR part of mapbox sdk... in any case it is using an old implementation instead of the newest ARFoundation, so it is of not much use.

Hey thanks  a lot for the response.

I am actually going to require AR functionality later down the line.

have you got any suggestions on what  should do?

should I wait for a newer implementation of AR Foundation.

**Comment by horatiu665** [comment]
Depending on required platforms. If you want to do it cross platform, it will be easier to build it yourself using ARFoundation and without mapbox's implementation, else you need to make a wrapper, provided you get it to work. So if it's a later functionality maybe start with mapbox minus AR. It doesn't seem like they made something particularly fancy. I worked on my project with a separate project just with mapbox SDK (incl AR) so I can get inspired.

If you want only one of the platforms you can try using their samples using ARCore and ARKit. Beware, they use outdated plugins, I'm not sure but doesn't seem compatible with latest from unity package manager.

I wouldn't hold my breath for a newer implementation from unity or mapbox because things seem to be moving slow. I'm a bit sad, latest AR mapbox stuff seems to be 2018. Let's hope this changes, I'd like to be wrong on this one :)

**Comment by brnkhy** [comment]
@StarKing777 SDK currently doesn't support ARFoundation but since Unity moved some classes to that package (which used to be in unity core), our implementation now requires ` ArFoundation` package to be installed. And I'm not sure about timeline but indeed ArFoundation changes for our SDK might not be released soon.
