### ISSUE TITLE
Enable/Disable POIs with button

### ISSUE THREAD

**Issue by unidorno** [mapbox/mapbox-unity-sdk#1597]
Hello, I want to disable or enable POIs with UI button. To do this, I tried to get VectorSubLayerProperties and make it equal to FindPointsofInterestSubLayerWithName(). Here is my button's script: 

```
VectorLayer vectorlayer = new VectorLayer();
VectorSubLayerProperties myprop2 = new VectorSubLayerProperties();

public void TurnOffPoi()
    {
        myprop2 = vectorlayer.FindPointsofInterestSubLayerWithName("Food");

        myprop2.SetActive(false);
    }
```

But after using this I get the error: 

> NullReferenceException: Object reference not set to an instance of an object

So it tells that I can make it Inactive because it does not have any value. I checked, "vectorlayer.FindPointsofInterestSubLayerWithName("Food")" returns nothing, not error or 0, just nothing. 

Maybe I wrote POIs name wrong, but it is the one that is in my POIs list.

![image](https://user-images.githubusercontent.com/42489432/79359711-bcd8bf80-7f64-11ea-9db7-82416a3f0086.png)

**Comment by unidorno** [comment]
I hope you don’t close issue until I get answer?

**Comment by brnkhy** [comment]
Hey @unidorno! 
This kinda depends on your application and how frequently you think this button will be used, but enabling/disabling layer might not be the best idea as it'll reprocess and create all pois from scratch every time.
I think another approach would be, creating a custom prefab modifier almost exactly same as the existing one. Then keep track of all poi objects created. then enable/disable those objects on button toggle. Of course when they are disabled, you'll have to disable new ones as soon as they are created as well.

also in the code snippet you're creating a new vactor layer yourself instead of using the one inside map object. You should be using `AbstractMap.VectorData`.

Hope that helps!
