### ISSUE TITLE
Latest Functional Unity Compatible Version?

### ISSUE THREAD

**Issue by michaelcuneo** [mapbox/mapbox-unity-sdk#1614]
Hey guys,

Just picking up an old project, and wanted to use some features and functionality of some of the newer Unity builds. What is the very last fully supported Unity Build that i could use before I start to see errors? if that's possibly known? I can't make MapBox work in the latest Unity Build, or the one before. ... just trying to find out which one I have to go back to rather than sitting here reinstalling Unity all night to work it out myself.

**Comment by brnkhy** [comment]
@michaelcuneo I'm not sure if I understand it correct.
Oldest version we fully support is 2017.4. Everything should work but some prefabs and scenes might be broken due to backwards compatibility and we might have missed it (at worst case).
If you mean the opposite, I'm generally working with 2019.3 without any problems. I haven't tried out 2020 yet. There are some issues you may run into though, like if you want to use AR, you'll need ArFoundation package installed (and if not you have to delete those folders). Or if you use lwrp or hdrp, we use `material.mainTexture` in `UnityTile.cs` and it doesn't work on those. It should be replaced by `material.SetTexture("_MainTex", texture)` or something similar.

**Comment by michaelcuneo** [comment]
Well, I have installed Unity 2019.3.4f1, and I've opened up an old project that I was working on at work, but from home. I have full access to internet here, 100mb/s, fast enough. I can add a map, open any demos, but no map loads... and if I search for location in the search window, nothing pops up as a result. Tested this on other machines and it's works fine, but not this one. Hmm. It's just the default blue square 'no texture' all over.

**Comment by michaelcuneo** [comment]
I've double checked to make sure I haven't accidentally not allowed Catalina to access the file structure, and I've also double checked my firewalls, to make sure Catalina isn't blocking the MapBox sdk from accessing the internet... but still, no maps.

**Comment by brnkhy** [comment]
@michaelcuneo I'm not sure what's up with that. Are you getting any errors at all? Any any changes in scene hierarchy? Where does it get blocked anyway, have you tried settings up a few breakpoints in code?
