### ISSUE TITLE
Unity Mapbox Location Based Game Demo Location Log

### ISSUE THREAD

**Issue by jjd114** [mapbox/mapbox-unity-sdk#1618]
Unity Version 2019.3
Mapbox SDK V 2.1.1

I'm attempting to setup a location based game starting with the demo provided by mapbox. I'm able to type in Longitude/Latitude of a desired location where I'd like to start/place the character, but upon hitting play, it's reseting to the default coordinates as provided by what seems to be a log file that points to a place in Helsinki. Can these defaults be overridden? I've tried deleting the log but it's seemed to have spawned more issues. 

Apologies if there is an easy solution here. I'm following along with the tutorial but it doesn't cover this and I'm new to Mapbox and Unity.

Thank you!

**Comment by Markovicho** [comment]
Unfortunately the documentation is pretty short for that important case:
https://docs.mapbox.com/unity/maps/examples/location-based-game/

you will find a better explanation in that video : https://www.youtube.com/watch?v=KX3chBZOa2A&list=PL86WBCjNmqh4bDQycScKKlP0ETkjo39gG&index=7 


**Approach for your issue**

Mapbox needs some kind of simulated Location-Input for your Desktop-Device. You can configure which one to use in the LocationProviderFactory Component which is part of the Prefab you have imported into your scene.
In the default case Mapbox is using a location-logfile from Helsinki like you experienced. You can switch that one to the "EditorLocationProviderArray" where you can simply enter other lon/lat values to simulate:
![image](https://user-images.githubusercontent.com/11967926/83108415-08cc6780-a0c0-11ea-9d96-0964468cf14d.png)

If you only want the application to stay at one point you should do something like this:
![image](https://user-images.githubusercontent.com/11967926/83108466-25689f80-a0c0-11ea-9740-47011880b463.png)

The AbstractMap itself should update itself to that destination if your LocationbasedGame is configured properly. Otherwise check out the component "UpdateMapWithLocationProvider".

best regards :-)

**Comment by jjd114** [comment]
Replacing the logfile with the array solved my issue! Thank you for
providing a detailed explanation.

**Comment by brnkhy** [comment]
Thanks a lot for the help @Markovicho! Really appreciate the detailed explanation and images :)
Closing this if there are no further issue @jjd114.
