### ISSUE TITLE
How to change Style into Tileset?

### ISSUE THREAD

**Issue by rampagedog12** [mapbox/mapbox-unity-sdk#1623]
I want to add my custom Style into Map Layers section in Abstract Map in Unity.  Map Layers only accepts Tileset Id. I know how to change my custom map in Style to Tileset Id.... I need some helps... More, any advanced tutorials for Map Features... I watch the tutorial videos posted in Youtube, but there are still many things I don't figure out how they work in Features section. I want to add some trees or grass on the Map. SpawnInsideModifier works fine, but the result is not good... For example, I want to rotate the grass to be normal to the surface...

**Comment by brnkhy** [comment]
@rampagedog12 
A style is an image result so we use that in `image` section.
Map layers uses vector data, also known as `tileset`.
so tileset is the raw data, style is something on top of it to produce image results from that data.

Adding decorations is just a difficult task, that's why we only have some basic functionalities (like SpawnInsideModifier) as example. I'm afraid you'll have to do anything extra yourself on top of that. You can create custom mesh/gameobject modifiers so achieve similar effect.

**Comment by rampagedog12** [comment]
@brnkhy I use Terrain V2 as data source for Tileset. I use landcover as a layer and my own modifiers to put trees and grass on it... It is working...
