### ISSUE TITLE
Preload tiles

### ISSUE THREAD

**Issue by vladyslavshcherbaiev** [mapbox/mapbox-unity-sdk#1625]
I saw an [example](https://docs.mapbox.com/mapbox-gl-js/example/flyto/) for Mapbox under the web when a flight is made from point to point, and it is not visible which map is being loaded. Is it possible to make such functionality for Unity? By the fact that you can see how the tiles are loaded and this distorts the whole effect or for example leave the previous texture on them until a new one is loaded? Or may be preload future zoom levels?
I am using satellite map view.
Thx.

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.2.15f
  * Scripting Runtime Version: 
  * Scripting Backend:  LL2CP
  * Api Compatibility Level: .NET 4.x
* Mapbox SDK version: 2.0.1
* The platform you're building to: Android 
* A description of what you're trying to do:
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
Hey @vladyslavshcherbaiev!
Unfortunately loading images from web is a slow process due to scrictly main thread texture operations (i.e. texture2d.load) of Unity. I am working on improving that and you can see an example of work in progress here; https://twitter.com/brnkhy/status/1258273391829831682?s=20
that being said, it's just an experiment for now. I might not be able to finalize and release it. Even if I do, it will probably take some time.

preloading downloading tiles wouldn't help too much as you would still need to load them from sql cache. You would probably need a solution where you load and keep them in scene but it might not be trivial either.
