### ISSUE TITLE
Mapbox SDK for unity on Hololens2

### ISSUE THREAD

**Issue by katsuwo** [mapbox/mapbox-unity-sdk#1644]
Hello.
Has anyone run Mapbox sdk for unity on Hololens2?
My test project is working correctly in the Unity Editor, but the
A CS0104 error occurs during the build phase.
From [here ](https://github.com/mapbox/mapbox-unity-sdk/issues/734)I learned that MapBox SDK for unity does not support IL2CPP, is this situation still the same?
Is there a way to run mapboxsdk in Hololens2?

Thank you.

unity version:2019.2.21f1
map box sdk version:2.1.1
he platform you're building to: UWP.
Target Device: HoloLens.
Build Type: D3D.

**Comment by brnkhy** [comment]
I never used Hololens myself so won't be able to answer but just to clarify; 
`MapBox SDK for unity does not support IL2CPP`
I believe this is just for Hololens builds. IL2CPP shouldn't be a problem on other platforms.

**Comment by jasonhbartlett** [comment]
Hi @katsuwo 
Yes, we have Mapbox running on HL2.  We're using:
 - Unity 2018.4
 - .Net scripting backend
 - Mixed Reality Toolkit 2.3.0

For our setup:

Using Mapbox SDK version 2.1.1 from [mapbox.com/install/unity](https://www.mapbox.com/install/unity/) we import just: 
 - Mapbox
 - ThirdpartyAssets

Note: If we had imported Mapbox from Github dev branch rather than the official release, we had to delete the Tests folder under Mapbox\Unity\. This is related to ISSUE #1610 

After building with Target as HoloLens and Architecture ARM, and then opening the Visual Studio solution, you then have to also add a reference to Sqlite
You can use either:
 - the version found by searching Nuget (which is older)
or
 - You can install the Visual Studio Extension "Visual Studio for Universal Windows Platform" and then add a reference to that. (this is what we're doing)

**Comment by katsuwo** [comment]
Hi brnkhy and jasonhbartlett 
I am grateful for your advice.
I didn't understand that IL2CPP is not suitable for building mapbox sdk.
Also, it seems that I was a little confused about how to make MRTK V2 and mapbox coexist.

Now, through my Hololens2, the Japanese archipelago is drawn on the floor of my room.
I can move my project forward.
Thank you

**Comment by jasonhbartlett** [comment]
Hi @katsuwo Glad to have helped.

One other cool thing I found recently is using a Clipping Primitive from the MRTK to mask out areas of the map you don't want to display.  So for example I wanted to have the 3D terrain map appear as a "circular" sand table, so I used the ClippingSphere.cs from MRTK to mask out everything outside the sphere.  Checkout the documentation here:  [MRTK Clipping Primitive](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Rendering/ClippingPrimitive.html)

There are 3 key thing that are important to make this work:
1. You have to change the Mapbox terrain material to use the Mixed Reality Standard Shader (not the Standard Shader)
2. You have to check enable "Use On Pre Render"
3. You need to add a script that will subscribe to abstractMap's OnTileFinished event and add those tiles Renderer to the ClippingSphere.cs or ClippingBox.cs AddRenderer() method at runtime.

![image](https://user-images.githubusercontent.com/22244576/88192164-36d6af80-cc0a-11ea-8896-acdb33d5f782.png)

![image](https://user-images.githubusercontent.com/22244576/88192205-435b0800-cc0a-11ea-9784-18608a62362c.png)

![image](https://user-images.githubusercontent.com/22244576/88192292-5bcb2280-cc0a-11ea-8871-60a77998cbca.png)

```csharp
using Mapbox.Unity.Map;
using Microsoft.MixedReality.Toolkit.Utilities;
using UnityEngine;

public class ClippingManager : MonoBehaviour
{
    [SerializeField]
    private AbstractMap abstractMap3D;

    public bool isCube;

    private void Awake()
    {
        abstractMap3D.OnTileFinished += AbstractMap3D_OnTileFinished;
    }

    private void AbstractMap3D_OnTileFinished(Mapbox.Unity.MeshGeneration.Data.UnityTile obj)
    {
        if (isCube)
        {
            GetComponent<ClippingBox>().AddRenderer(obj.gameObject.GetComponent<Renderer>());
        }
        else
        {
            GetComponent<ClippingSphere>().AddRenderer(obj.gameObject.GetComponent<Renderer>());
        }
    }
}
```

![image](https://user-images.githubusercontent.com/22244576/88192654-cb411200-cc0a-11ea-83ac-99b0048e6312.png)

**Comment by olemid** [comment]
Hi @jasonhbartlett. I've come across this issue while trying to get Mapbox onto our Hololens 2, and your posts have been very useful. We need to build with ARM64 and I'm running into the issue that SQLite does apparently not have an ARM64 version for UWP. When you did your tests was that with ARM? I've been trying to figure out what I need to get but I haven't had any luck so far.

Ole

**Comment by katsuwo** [comment]
hi
I'm currently away from my PC so I can't see the details.
In my memory, after I built the project on Unity,
I installed the ARM version of SQLite using Nuget in Visual Studio

**Comment by AdrianSngular** [comment]
Hi, I'm having the same trouble than @olemid. If I try to add the SQLite Nuget I get an error saying I'm trying to install it as 'native,Version=v0.0' I'm guessing because That's a .net project, while the project that Unity creates is C++
I've looked under extensions for the  "Visual Studio for Universal Windows Platform" that @jasonhbartlett was referencing but I can't find anything similar. I installed an SQLite for UWP extension that I found there but there is not difference at all. So All I can get is an error when MapBox loads on Holo Emulator saying that there is not reference to sqlite3.dll
@katsuwo did you just installed SQLite Nuget?

**Comment by katsuwo** [comment]
hi
@AdrianSngular 

>the project that Unity creates is C++

are you using IL2CPP?
You probably need to use .net for your Scripting backend.

The following is an article I wrote.
It can be found at https://qiita.com/katsuwo/items/36ca7e2b288d8a000f75
It is written in Japanese, but you may be able to get some information by using Google Translate.

The attached image is the Nuget package management screen for VS2019.
It looks like I installed SQLite.Universal with Nuget

![e6fb0f2e9d37e119cf1c79c60998a0fa](https://user-images.githubusercontent.com/3500030/94804372-ae546680-0425-11eb-911c-cb16d377e44f.png)

**Comment by axteroide** [comment]
Thanks @katsuwo in the end I could solve the trouble thanks to this #1627 I downloaded the SQLite extension but needed to set the reference too. Thanks for your answer anyways! ありがとうございます。

**Comment by mertusta1996** [comment]
[https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-](url)

**Comment by mertusta1996** [comment]
For Hololens-2 and Mapbox in Unity UWP, try this repo ;
https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-
