### ISSUE TITLE
Map Layer being cut off when using height map

### ISSUE THREAD

**Issue by JonFaull** [mapbox/mapbox-unity-sdk#1662]
Hi, I am trying to display a map layer (in the abstract map script) on top of a map. I can get it to display appear ok but it glitches out and flickers a lot when using the flat terratin and gets cut off when using the terrain with elevation. I would like to be able to display it on top of the terrain with elevation layer type with out having some of it cut off. 
 
I have tried adding the Snap Terrain mesh modifier to it from the behavior modifer menu and while it does work, there is a gap between the layer and the map. Any help would be great. thanks!

**Comment by brnkhy** [comment]
@JonFaull SDK currently doesn't have a way to overlay polygons on elevated terrain. It only works on flat tiles. 
Flickering you're getting on flat tiles is most likely z-fight and it's happening because everything is on same elevation. 
![Unity_2020-08-12_04-15-34](https://user-images.githubusercontent.com/1465390/89964310-7b29fe00-dc52-11ea-9796-4dec1f2a9884.png)
this settings for example will push your layer polygons one unit up, so it won't collide with terrain itself. If you have multiple layers, you should order them using height property here.
Again it won't work with elevation though and there's no easy way to make that happen at the moment.
hope that helps!

**Comment by JonFaull** [comment]
> @JonFaull SDK currently doesn't have a way to overlay polygons on elevated terrain. It only works on flat tiles.
> Flickering you're getting on flat tiles is most likely z-fight and it's happening because everything is on same elevation.
> ![Unity_2020-08-12_04-15-34](https://user-images.githubusercontent.com/1465390/89964310-7b29fe00-dc52-11ea-9796-4dec1f2a9884.png)
> this settings for example will push your layer polygons one unit up, so it won't collide with terrain itself. If you have multiple layers, you should order them using height property here.
> Again it won't work with elevation though and there's no easy way to make that happen at the moment.
> hope that helps!

Ah ok, I didn't know it wasn't possible at the moment, thanks for the help, very useful.
