### ISSUE TITLE
POIs are not in the correct location. All the AR features of Mapbox is useless it doesnt work and the tracking is very poor.

### ISSUE THREAD

**Issue by shubhamp41** [mapbox/mapbox-unity-sdk#1675]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3
  * Scripting Runtime Version: MONO
  * Scripting Backend: 
  * Api Compatibility Level: 
* Mapbox SDK version: 2.1.1
* The platform you're building to:
* A description of what you're trying to do: TRYING TO CREATE POIs 
* Steps to recreate the bug if appropriate: RUN THE SAMPLE POI SCENE
* Links to your logs are also helpful:

**Comment by brnkhy** [comment]
Thanks for the report 🙏

**Comment by shubhamp41** [comment]
Why did you close it

**Comment by shubhamp41** [comment]
Can you atleast tell me how can I fix the tracking or port the project to latest AR SDK

**Comment by shubhamp41** [comment]
Seriosuly you're just gonna ignore the fact that the sdk is useless @brnkhy

**Comment by brnkhy** [comment]
I closed it because I didn't understand it. There was no question or anything in the original post. What was I supposed to say? 
Yes our AR support isn't working too well at the moment and I'm not able to work on AR at the moment so it'll probably be like that for a while. If you have questions/problems though, I can leave the ticket open for sure and some other dev might be able to help as it happened in many other tickets.
