### ISSUE TITLE
Buildings overlap after zooming and panning

### ISSUE THREAD

**Issue by rbyjoswald** [mapbox/mapbox-unity-sdk#1698]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2019.4.4
  * Scripting Runtime Version: Editor: .NET 4.x, Mobile: .NET Standard 2.0
  * Scripting Backend: Editor: Mono, Mobile: IL2CPP
  * Api Compatibility Level: API level 24, iOS: 10
* Mapbox SDK version: 2.1.1
* The platform you're building to Editor, Android, iOS
* A description of what you're trying to do:

When adding buildings to a zoomable map and then zooming and panning around the camera I rather consistently manage to somehow make buildings overlap, spawn inside lakes, or have tiles without any buildings. Note that I have applied the fix from thread #1557. That fixed the floating buildings, but they still start overlapping. This may or may not be more frequent when panning around fast. Could be that the results of a building spawn operation are spawned in the wrong tile or at the wrong position?!

* Steps to recreate the bug if appropriate:

Just enable buildings on the Features layer and zoom and pan around in the gameworld. At some point buildings appear strangely overlapping.

* Links to your logs are also helpful: 

![mapbox_broken_building_03](https://user-images.githubusercontent.com/20922523/96571981-98232300-12cc-11eb-99c7-f7f6535f71c9.JPG)
![mapbox_broken_building_04](https://user-images.githubusercontent.com/20922523/96571982-98232300-12cc-11eb-9922-bc0352de0201.JPG)

**Comment by brnkhy** [comment]
@rbyjoswald It must be leaking objects from an old tile.
Can you try this quick changes please? I think this hasn't been merged into dev yet and definitely not in the release package.

![msedge_5cSp9OESpS](https://user-images.githubusercontent.com/1465390/99389406-108afd00-28e8-11eb-8357-2f535d4f538b.png)

**Comment by Markovicho** [comment]
@brnkhy the fix seems to be working and cross related to the issue i reported yesterday 

https://github.com/mapbox/mapbox-unity-sdk/issues/1728

**Comment by Markovicho** [comment]
@brnkhy 

![image](https://user-images.githubusercontent.com/11967926/104971265-88f86200-59ee-11eb-8b6a-e61c1e3be3dc.png)

Are you sure the fix sorts everything out ? Still not working at all for me. Moving around on the map will always lead to unrecycled buildings -_-

**Comment by Markovicho** [comment]
It seems that this is happening especially when you are manually jumping from location to location. Running smoothly through the world (real world gps scenario) seems to be okay. But in the end it looks like this bug is not fixed and only reduced due to better circumstances ... It should be no problem to jump to another location without producing unrecycled tiles.

**Comment by Markovicho** [comment]
@brnkhy 
I made a little testscene based on the locationbasedgame prefab which is moving by the builtin location-log provider fromn helsinki. 
It seems like tiles duplicated already from the creation. the result are these z-fighting buildings with broken shaders for the duplicate ones. This was something i was wondering about since the first usage of Mapbox unity sdk and now it's getting clear that the isse behind it is even much bigger.

![floating_building_1](https://user-images.githubusercontent.com/11967926/107967496-76e9ef00-6fad-11eb-8c6b-30338825921a.JPG)

I attached the testscene. Maybe it will help out while debugging this issue.
[FloatingBuildingsTicket_1698.zip](https://github.com/mapbox/mapbox-unity-sdk/files/5982671/FloatingBuildingsTicket_1698.zip)

It's only a scene-assset configured to show the issue. Should be working within a unity-sdk project 2.1.1. / 2.1.2

sadly it's another basic feature which is not usable in production -_-

**Comment by Markovicho** [comment]
Update: Finally i get rid of this issue. I will do some more testing and try to figure out which change in the map configuration helped in the end :-)

**Comment by brnkhy** [comment]
Hey @Markovicho !
Sorry I missed this 🤦‍♂️ 
I haven't run into this duplicate issue for a while and I was sure that fix would have worked really. Vector layer might really not be production ready at the moment. Bugs can be fixed but I feel like performance isn't really there.

**Comment by Markovicho** [comment]
No worries. I hope i can provide a little report next week. In the end it seems at least related to some specific configurations on AbstractMap .

**Comment by kroltan** [comment]
Hi @Markovicho, sorry to bother you, did you find a solution? I have a similar problem where buildings load in incorrect positions (often floating, even though I've "snap to terrain" enabled). This only happens to tiles that load after the initial load, so when panning.

![Demonstration of the issue](https://user-images.githubusercontent.com/978042/120131763-6dbd1080-c19f-11eb-959e-d80184d150cf.png)

Kind of feels like some code that should run is not doing so, since if I change any setting in the inspector, the buildings move to their correct locations.

My map's extent options are set to "Range Around Transform"

**Comment by gruedisueli** [comment]
I was experiencing the same issues. Incorporating the changes from branch "AddRecycleCheck" seems to have resolved problems!
