### ISSUE TITLE
Getting the slope of terrain and direction at a given lat/long

### ISSUE THREAD

**Issue by harry-levick** [mapbox/mapbox-unity-sdk#1725]
What is the best way to get the slope of the terrain at a given latitude and longitude? So far I am getting the latitude and longitude of a mouse click:

```
mousePosScreen.z = cam.transform.localPosition.y;
var mousePosTerrain = cam.ScreenToWorldPoint(mousePosScreen);
var latLongDelta = map.WorldToGeoPosition(mousePosTerrain);
```

But I don't know which is the best way to get the slope of the terrain at this point? I know that there is a `AbstractMap.QueryElevationInMetersAt(Vector2d latlong)`, so I could use this and get the elevation in all directions and use this to calculate the slope, but are there any other methods that would make this easier?

Thank you for your help

**Comment by brnkhy** [comment]
@Hlev1 oh this is interesting!
Normally mesh normal gives the slopes easy way but in most cases, map mesh will be much lower resolution than the elevation data itself.
I don't know the theory of it (terrain slope calculation) really but yes that method will check the full resolution data so maybe you can query 9 points (3x3 grid) and find it. That method should be as fast and precise as it gets but I would still suggest sanity checking the values returned because of real world/unity world conversions might cause some confusion.

**Comment by harry-levick** [comment]
I'm new to unity, to start with this resolution shouldn't be too much of an issue. How can I get the mesh normal for a point?

**Comment by harry-levick** [comment]
I've got it, I was getting confused with the ray casting because I hadn't selected `add collider`
