### ISSUE TITLE
Is mapbox for unity project dead ?

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1734]
No new release since october 2019 and no commits since febrary 20. Seems project is dead.

Thanks

**Comment by brnkhy** [comment]
No it's not.
Yes there hasn't been new merges to dev branch for a long time but it's mostly because I created this behemoth of changes dependent on each other and I'll push them as a one huge package. Very not ideal, I'm fully aware but just to answer your question, we are still working on the SDK.

**Comment by RomanAtBrief** [comment]
Are there any updates coming for Unity 2019 LTS and 2020 ?

**Comment by CHaP235** [comment]
Yes, I'm also curious since Google just announced to shut down their Map SDK for Unity by the end of 2022.
[(https://developers.google.com/maps/documentation/gaming/overview_musk)](https://developers.google.com/maps/documentation/gaming/overview_musk)

Might be a good chance to rise and shine with the next Mapbox SDK come back / update.  :)

**Comment by cperos** [comment]
Hopefully, I am trying to do a location based unity game for a school project but cant figure it out with google going down and mapbox not seeming to work for unity2020....

**Comment by ssshake** [comment]
I will point out here that I hope this project stays alive but it's not receiving some crucial fixes.

The two most apparent are:

1) MapboxMobileEvents failed to run on iOS simulator because the only included library is for arm64. Can't you just offer an x86 version to make this work? I know that mapbox for react native works on ios simulator so that x86 version of the telemetry library must exist

2) The deprecated build target error that unity throws as reported on other issues here. It's a one line change and would have people a lot of trouble.

**Comment by ANDREYDEN** [comment]
[Here](https://github.com/mapbox/mapbox-unity-sdk/issues/644#issuecomment-639172514) is the one line change from the previous comment☝️. It is mentioned in #644.
