### ISSUE TITLE
Unity 2019 LTS and URP problems

### ISSUE THREAD

**Issue by RomanAtBrief** [mapbox/mapbox-unity-sdk#1740]
Does this project still in development? Is there going to be any updates to support Unity 2019 and 2020?
Still funny  annoying problems with URP. Mapbox still uses old standard shader!

**Comment by PowZone** [comment]
Same request. Do you plan to support at least Unity 2019 LTS?

**Comment by brnkhy** [comment]
Indeed it's still using the old render pipeline. The problem is mostly the main texture field naming in the URP/HDRP shaders. I wrote a blog post about it but I'm afraid even that might be outdated now as both libraries are moving fast. still it might give an idea; http://barankahyaoglu.com/dev/mapbox-unity-sdk-with-urp/
