### ISSUE TITLE
Spawn gameobjects at hardcoded coordinates

### ISSUE THREAD

**Issue by abobakrd** [mapbox/mapbox-unity-sdk#1809]
I have a list of real world coordinates where i want gameobjects (treasures to be collected players) to be spawned at. I'm using the `Camera Bounds` extent options on `AbstractMap` script where only maptiles visible to the camera are generated. 

I dont want to spawn treasures if the treasure coordinates are not on the generated map or far away from it obviously, but how do i figure this out? Is there a way to find out if the treasure coordinates are within the generated maptiles?

If there was a dataset with generated coordinate points that you could query by coordinate points as key, it would be good for performance but maybe there are better methods. Kinda hard to find any info on this in the docs, hence why i ask here.

Also, what is the best performing way of instantiating maps, at runtime (Camera Bounds) or at application start (Range around center/transform)?

**Comment by Markovicho** [comment]
Hey @abobakrd 

you will have to calculate the northeast and southwest coordinates of the current map extent. this will give you a bounding box where you could check containing points.

**Comment by abobakrd** [comment]
I did something similar except i converted the hardcoded geo coordinates to unity world positions and checked if they where inside the bounds of the mesh renderer belonging to the current mapbox map tile. Is this what you meant?

**Comment by Markovicho** [comment]
If the point is not inside the map extent (point in rectangle check where you can ignore the height) there is nothing more to check . 

You could also use this MapVisualizer function to do your check:
```
            UnityTile tile;
            Map.MapVisualizer.ActiveTiles.TryGetValue(Conversions.LatitudeLongitudeToTileId(latlong.x, latlong.y (int)Map.Zoom), out tile);

```

You only need to check this each time Map.OnUpdated (or alternatively LocationProvider.OnLocationUpadted) is fired. This will reduce your calculations already massively compared to checking it each frame. On the hand the calculation is nothing an modern cpu will lead into big trouble. Your performance peaks will most likely being caused by rendering stuff or loading map tiles. This is based on the assumption that you are not checking thousands of treasure coordinates in a high frequency. Anyways if that would be the case there a plenty approaches to filter those coordinates using cluster approaches. 
But first you should check out the unity-profiler if your calculation is appearing at all ;-)

**Comment by abobakrd** [comment]
I skipped the whole real-world coordinates thing and instead went with instantiating at POI's which worked out pretty well. However, I will probably use real-world coordinates for other use later on, so your code example comes in handy. 

Does `Map.OnUpdated` fire when a new tile is rendered? I currently used `Map.OnTileFinished` to check the coordinates within that tile because i use the `Camera Bounds` extent option that renders new tiles on the go depending on the camera position.

**Comment by Markovicho** [comment]
If OnTileFinished will cover your needs depends on your game. Most likely you want to get informed about any operations on the map like zoomchanges, locationchanges etc. while not all scenarios cause tile loadings :-)

**Comment by abobakrd** [comment]
Thank you for your tip. `Map.OnUpdated` seems like a better fit in this case.

**Comment by brnkhy** [comment]
Hey @abobakrd, sorry for joining the discussion late.

`OnUpdated` is called on each map update so it'll fire even if it moves a slight bit. If you only want to check your POI is in view, `OnTileFinished` might be a better idea I guess. It'll return tile coordinate and you can calculate bounds from that and check for collision. It'll fire a lot less so it'll hurt performance a lot less.
also a great idea would be convering your custom latlngs to tileId at the start, put them in a dictionary or something (key being tileId) so when a tile is loaded you can check if that tile contains any of your custom points in O(1).
Hope that helps!
