### ISSUE TITLE
GeoToWorldPosition introduces longitudinal inaccuracies

### ISSUE THREAD

**Issue by liquidbuddha** [mapbox/mapbox-unity-sdk#1841]
Using a very low zoom level, using the GeoToWorldPosition function results in placement of objects which is not matching the Abstract map.

Please see images where the Location changes to further South and the object placements become increasingly exaggerated/distored.
In the attached images, you can see the location used as the home / center
Thanks for the help in sorting this out. My users are giving me a lot of grief on this one!
![SkyGlass_220114-012420](https://user-images.githubusercontent.com/5150330/149570311-aed82aa2-8274-48a1-9522-75ade43eae94.png)
![SkyGlass_220114-012406](https://user-images.githubusercontent.com/5150330/149570328-2df6da3c-d4d6-408f-a715-fa0d33393521.png)
![SkyGlass_220114-012357](https://user-images.githubusercontent.com/5150330/149570334-9b8f3ccd-8d3a-47ea-bac6-e66368de8350.png)

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2020.3.21f1
  * Scripting Runtime Version:
  * Scripting Backend: Mono
  * Api Compatibility Level: 
* Mapbox SDK version: Mapbox 2.11
* The platform you're building to: Desktop/iOS/Adroid
* A description of what you're trying to do:
Accurately display objects based on lat/lon against map.
* Steps to recreate the bug if appropriate:
* Using a very low zoom level, GeoToWorldPosition function results in placement which is not matching the Abstract map.

**Comment by brnkhy** [comment]
Hey @liquidbuddha,
first of all, that looks like a REALLY cool app! Can I learn more about it? Is it an app on store?

I checked the images but I'm not sure how to read them. Is one of them supposed to be correct/wrong?
Also are markers on the `y=0` plane? Or do they have elevation?
I think (lat,lng) to (x,y) should be working reliably (unless there's something different going on with the map) but `latitude` also effects `elevation` and that might be the case. That effect shouldn't be too dramatic but since you said `south`, it might be something to check.
Another possibility would simply be a gameobject offset/scaling not taken into account.

one thing I would suggest is hand feeding data, like 50 points with same longitude but different latitude, so we can see the error better. would be even better if you can print out the output of `GeoToWorldPosition ` for each as well.

**Comment by liquidbuddha** [comment]
Hello,

Thanks for getting back to me. I’m VERY KEEN to sort out this issue.

I will try to sort out some test data. A grid of points doesn’t get to the
heart of it.. more accurate would be several known points along a souther
coast line so you can see the offset from the map image tile.

What I sent was three images. Each with a different home location for the
abstract map. The location is visible written in the top left.. Belize,
Miami etc. The issue is that the same data displays differently depending
on the home location. So which is correct or wrong is anyones guess. That
the problem that it’s not consistent although it should be right?

Thanks for your feedback. It’s a new 3D flight tracking app.
Www.Aviarlabs.com for
More. You can download the software and give it a spin on desktop now.
Happy to get you going as this would be a perfect way to show you.

FYI… the data is real time flight tracking data with altitude. The scale of
the aircraft is obvi simulated and for these images I sent the altitude is
to scale.

I am open to a quick zoom call to demonstrate if that would be helpful.

I’m hoping this could be a simple abstract map setup, but I’ve gone over
the docs, reviewed the setup in the demo files and all looks as it should…
still you may know more places to check.

This issue is my TOP PRIORITY… the only remaining bug of my 1500+ Users
beta test.  Launch is less than 40 days away. Love to figure this out.

Looking forward to hearing back from you soon.

Cheers,
Goa

**Comment by brnkhy** [comment]
@liquidbuddha I think we can fix this, shouldn't be a big issue.
I understand the issue better now and at the moment it looks more like a scaling/parenting issue.  It looks like all points are offset together in each screenshot. which makes me think; you probably creating and storing pins under a different unity gameobject and that gameobject might not have the same position and scaling with the map gameobject.
also there's an option in the map settings which moves map to center your map focus point for example. disabling that might be a good test as well.
shortly, my first guess is map object and pin container object not having same position/scale in runtime (runtime part is important here).

**Comment by liquidbuddha** [comment]
Hello Baran,

Thanks for getting back to me.

Good idea to check the parenting. I did and all looks normal. The hierarchy is shown below… the objects with the ICAO code name is each aircraft target. One is detailed. The Target Object pool and the Object Pools parent are all 1/1/1. 



 Here’s the abstract map setup if that helps.



Regarding Range around Transform or Range Around Center.. I have opted for Range around transform as this was a more natural UI for my setup. I’m not sure switching to this will make a difference but I am willing to test.

Any other ideas?

PS.. sorry for my delayed response. I caretake my elderly dad and this was a hard week. This case is of highest importance professionally speaking. Thanks

G

**Comment by brnkhy** [comment]
Hey @liquidbuddha,
First of all, I wish you and your father the best, I hope he's doing good and healthy.
I'm not able to see the images you posted, I'm not sure but it might be because you replied as mail (I think). They might help a lot.
Also the option I was talking about isn't the tile provider range but another one ( should be under `other` part I think) about map center location. And options should be exact location vs tile center. That setting also offsets things a little.

**Comment by liquidbuddha** [comment]
![Screen Shot 2022-01-20 at 9 23 08 AM](https://user-images.githubusercontent.com/5150330/150360220-116a84a3-8bd9 -4586-8e04-85b2788ed1ba.png)
![Screen Shot 2022-01-20 at 9 20 20 AM](https://user-images.githubusercontent.com/5150330/150360271-bea3b772-fc7f-4639-8932-e2864960f40b.png)

**Comment by liquidbuddha** [comment]
Thank you. Just uploaded the images on GitHub. I’ll be better about that, thx.

Thanks for your kindness.

Cheers,
G

**Comment by liquidbuddha** [comment]
![Screen Shot 2022-01-20 at 9 23 08 AM](https://user-images.githubusercontent.com/5150330/150360769-c3a85df1-c7c3-448f-9996-f8363ae42ddf.png)

**Comment by liquidbuddha** [comment]
For what it's worth, switching the Placement Options from At Location Center to "At Tile Center" seems to throw everything off more. This seems to break determining the lat/lon from a ray casted x/y.  If this is worth chasing down, I'll upload some screen shots... but this seems like a tangent. Please advise. Thanks.

**Comment by liquidbuddha** [comment]
Here's the whole abstract map editor settings.
![Screen Shot 2022-01-20 at 10 02 03 AM](https://user-images.githubusercontent.com/5150330/150364316-04937e74-91fd-44e2-bcec-6d30f294d452.png)

**Comment by brnkhy** [comment]
@liquidbuddha 
I'm afraid nothing catches my eye there and we'll need some debugging to understand what's going on.
I still think it's some kind of offset issue but we'll see.
One thing to try might be calling `Conversions.GeoToWorldPosition()` directly. It should be exactly same as the `AbstractMap.GeoToWorldPositionXZ` but still might trying. 
actually here is a better idea, I would create a small script that calls `AbstractMap.GeoToWorldPositionXZ` for a fixed position, let's say around the center of USA. then run app three times with those different center locations and run that script for each. Then check how the math goes line by line. We expect all three to return different values at this point. 
If all three returns different point for same input, that means error is due to the values we feed to the conversion method (values other than latlng).
If all three returns same value, it means the error is due to parenting/object hierarchy.
I think this is the easiest and fastest way to start debugging.


Also a few irrelevant suggestions;
- you might want to uncheck `Use Relative Height`, it shouldn't have any effect in your case and might simplify some stuff.
- you might want to disable `add collider` and use one huge flat plane for mouse clicks etc. At the moment you are spawning a collider for each tile and probably don't need that. might help with performance.
- you are loading way way too many tiles. 357 to be exact. I guess you aren't having too much trouble since map looks static that's bad for performance either way, especially the memory usage. I would highly suggest exploring lower tile count options and do it if quality doesn't drop too much.
- also just noticed you have elevation enabled, are you using that? it means you are using 2x imagery if you are not using to, so disabling it would help immensely.

**Comment by liquidbuddha** [comment]
Thank you for these excellent suggestions, especially regarding performance. 

regarding :"you are loading way way too many tiles. 357 to be exact. I guess you aren't having too much trouble since map looks static that's bad for performance either way, especially the memory usage. I would highly suggest exploring lower tile count options and do it if quality doesn't drop too much." 
... I'm down to do this to increase performance, but how... I'm thinking increase the Unity Tile Size and then decrease the Range Around Transform... is this correct? Any suggested tile size?  Grid count to try to keep under?

Also, in the beginning I was having a bugger of a time finding the right lat/lon to x/y function.. I finally found it and essentially recreated it inside my scripts... here's the exact function I'm using for this, as it matches the Conversions.GeoToWorldPosition() .

        public static Vector2d GeoToWorldPositionGC(double lat, double lon, Vector2d refPoint, float scale = 1)
        {
            var posx = lon * Conversions.OriginShift / 180;
            var posy = Math.Log(Math.Tan((90 + lat) * Math.PI / 360)) / (Math.PI / 180);
            posy = posy * Conversions.OriginShift / 180;
            return new Vector2d((posx - refPoint.x) * scale, (posy - refPoint.y) * scale);
        }

Here's an example of the call to the above..

  var worldPosition = GeoToWorldPositionGC(
                         (double)Lat - dataController.playerSettings.playerLat,
                         (double)Lon - dataController.playerSettings.playerLon,
                         new Vector2d(0, 0),
                         (float)goMap.WorldRelativeScale);

goMap is the abstract map.  Lat and Lon are the target's information, playerLat/Lon are the home location.. so I'm getting the offset for 0,0, as the map and UI are thus.

**Comment by liquidbuddha** [comment]
Perhaps this helps.. another way to create this anomaly is when I home far south, like in Argentina in this example.. the traffic locations seems to skew more and more as you move north. The traffic in the far distance should be over the EU region.  
![SkyGlass_220120-120535](https://user-images.githubusercontent.com/5150330/150387207-466bdc4b-293d-4a37-adea-9aae505fb418.png)

**Comment by liquidbuddha** [comment]
Hey @brnkhy .. I hope I interpreted your instructions...

  " I would create a small script that calls AbstractMap.GeoToWorldPositionXZ for a fixed position, let's say around the center of USA. then run app three times with those different center locations and run that script for each. Then check how the math goes line by line. We expect all three to return different values at this point.
If all three returns different point for same input, that means error is due to the values we feed to the conversion method (values other than latlng).
If all three returns same value, it means the error is due to parenting/object hierarchy."...

 correctly.  Are we moving in the right direction?

Here's the test script I created... 

```
using System.Collections;
using UnityEngine;
using Mapbox.Unity.Map;
using Mapbox.Utils;

public class MapDriftBugHunt : MonoBehaviour
{
    public AbstractMap abstractMap;
    public Vector2d latlng1;
    public Vector2d latlng2;
    public Vector2d latlng3;
    public Vector2d testLatLng;
    public Vector3 resultV3;

    void Start()
    {
        StartCoroutine(MapTest());
    }

    public IEnumerator MapTest()
    {
        abstractMap = FindObjectOfType<AbstractMap>();

        latlng1 = new Vector2d      (37.62, -122.38);   // SFO
        latlng2 = new Vector2d      (32.90, -97.04);    // DFW
        latlng3 = new Vector2d      (17.22, -88.69);    // Belize
        testLatLng = new Vector2d   (39.38, -97.92); // USA Ctr

        // location 1
        abstractMap.UpdateMap(latlng1, 3f);
        resultV3 = abstractMap.GeoToWorldPositionXZ(testLatLng);
        Debug.Log("location 1: " + resultV3.ToString());

        // location 2
        abstractMap.UpdateMap(latlng2, 3f);
        resultV3 = abstractMap.GeoToWorldPositionXZ(testLatLng);
        Debug.Log("location 2: " + resultV3.ToString());

        // location 3
        abstractMap.UpdateMap(latlng3, 3f);
        resultV3 = abstractMap.GeoToWorldPositionXZ(testLatLng);
        Debug.Log("location 3: " + resultV3.ToString());

        yield return null;
    }
}
```

Here are the results ...
![Screen Shot 2022-01-29 at 9 39 33 AM](https://user-images.githubusercontent.com/5150330/151665176-b42a487d-ff26-465b-a44f-806e94f4f3ac.png)

**Comment by brnkhy** [comment]
rereading what I suggested earlier.... I'm afraid it doesn't make sense to me now. I guess I was a little confused back then (or now).

reading old messages, I noticed I missed some stuff though;
![msedge_rQ3LV2RgUK](https://user-images.githubusercontent.com/1465390/151667000-d6e8928b-1fbc-46e6-ab63-26f23c2fb9a7.png)
this call looks wrong. It should look more like;

GeoToWorldPosition(
planeLat,
planeLon,
Conversion.LatLonToMeters(playerLat, playerLon),
scale);

shortly, that reference point parameter (3rd one) is the map center location (base in your case) in meters.
can you give this a shot?

**Comment by brnkhy** [comment]
@liquidbuddha ☝️

**Comment by liquidbuddha** [comment]
@brnkhy ... This did it!!!

Early indicators are this is the fix. I will continue testing for edge cases but I think this works!

THANK YOU!

![SkyGlass_220129-112420](https://user-images.githubusercontent.com/5150330/151668722-a2af81c4-f69f-4a0a-89d1-80d786207e7d.png)
![SkyGlass_220129-112412](https://user-images.githubusercontent.com/5150330/151668730-1da1304e-797c-42b3-a6a4-a901d5c4a9d6.png)
![SkyGlass_220129-112402](https://user-images.githubusercontent.com/5150330/151668732-ea9cee9e-b4aa-4b04-bcc4-2e3c24da66da.png)

**Comment by brnkhy** [comment]
@liquidbuddha ah awesome! I'm super distracted these days so guess I missed that last week.
can you please let me know how your app is doing time to time? you can DM on twitter (twitter: brnkhy). would love to know how it's doing!
closing this ticket but feel free to open a new one if there's any other issues.

**Comment by liquidbuddha** [comment]
@brnkhy you bet. Do y'all have a discord channel?

**Comment by brnkhy** [comment]
@liquidbuddha we don't use discord, I think fastest way to reach me are mail (baran.kahyaoglu@mapbox.com), Twitter DM and/or tickets here.
