### ISSUE TITLE
StackOverflowException - ConstraintMesher

### ISSUE THREAD

**Issue by gsommers** [mapbox/mapbox-unity-sdk#187]
I'm working on an interactive map in Unity, which I originally based off of the Slippy map example. It's working as intended, but I'm worried about performance.

Some background: In addition to having a `TerrainFactory` and `MapImageFactory`, my `MapVisualizer` has about 15 mesh factories. Each `MeshFactory` corresponds to a different tileset  (different `MapId`), but all of the `VectorLayerVisualizers` refer to the same default stack. The default stack has three modifiers. Most importantly, I added `ColliderModifier` so that when a user clicks on the map, a panel displays all the tilesets that were clicked on. I also attached a `LayerModifier` for layermasking, and a `PolygonMeshModifier` because I couldn't get the collider to respond without it.

The `PolygonMeshModifier` is where I run into trouble, I think. I often get the following error message:

`StackOverflowException: The requested operation caused a stack overflow.
TriangleNet.Meshing.ConstraintMesher.ScoutSegment (TriangleNet.Topology.Otri& searchtri, TriangleNet.Geometry.Vertex endpoint2, Int32 newmark) (at Assets/Mapbox/Core/Plugins/ThirdParty/Triangle.NET/Meshing/ConstraintMesher.cs:834)`

This error doesn't really seem to interfere with how my program runs - maybe there's a bit of lag, but I don't really notice it - but the idea of a stack overflow has me concerned. What exactly is the class `ConstraintMesher`, and where is this method being called, anyway? Is there a relationship between `ConstraintMesher` and `PolygonMeshModifier`, or is something else at fault? My best guess is that because I have a lot of meshes (which aren't being rendered, but do need mesh colliders), there are too many vertices to calculate. However, I don't see how how I can reduce the number of meshes; I'm actually about to add in more tilesets, which I'm afraid will only worsen the problem.

One more note: I checked out the performance in the Profiler Window, and it looks like when the stack overflow occurs, most of the time and memory is taken up by something called `Runnable.Routine() [Coroutine: moveNext].` I looked at the `Runnable` script, but I'm not entirely sure what `moveNext` does.

Thanks for reading this super long post! Any help is appreciated. :)

**Comment by david-rhodes** [comment]
@gsommers Hey, thanks for the ticket!

First of all: 
> In addition to having a TerrainFactory and MapImageFactory, my MapVisualizer has about 15 mesh factories

You can actually composite your tiles on our servers by string concatenating (with a `,`) your Map Ids. So long as your layers do not collide with each other, the operation will be additive. This will alleviate the need for so many mesh factories (which also need to make new web requests, etc).

Second, as for this crash, I suspect there is possibly some bad geometry in your source data that our (3rd party) library does not support. That said, if possible, please use `develop` rather than `v1.0.0`. We've removed `Triangle.NET` in favor of our own solution `Earcut`. This may work for you.

Lastly:
> One more note: I checked out the performance in the Profiler Window, and it looks like when the stack overflow occurs, most of the time and memory is taken up by something called Runnable.Routine() [Coroutine: moveNext].

This is a red herring. Essentially everything gets processed from this main call (this makes the initial web requests, which then proceeds to process the data and generate geometry, etc. I think this is in part because it's a coroutine. You may have better luck if you `deep profile`.

**Comment by gsommers** [comment]
Thanks for the reply! Sorry if this is obvious, but how do I go about getting the `develop` version?

**Comment by david-rhodes** [comment]
@gsommers Clone or download from here: https://github.com/mapbox/mapbox-unity-sdk. You can either drag and drop the `Mapbox` folder in `Assets` or create your own Unity package from the `sdkproject`.

**Comment by gsommers** [comment]
Thanks! I'll close this thread now.
