### ISSUE TITLE
is it possibile to display other player on the map?

### ISSUE THREAD

**Issue by lorenzoMezza** [mapbox/mapbox-unity-sdk#1892]
Hi, I've recently started exploring the mapbox unity sdk, and before I get completely hands on with it to make my project (a multiplayer location based game), I need to know if it is possible to make the following things:

is it possible to show on the map the location of other players in real time using their coordinates?

how far is it possible to customize the map?
can i make it so that streets , buildings and street names are not pixelated/blurry as in screenshot below (screen 1)?
can i make the street name look like and acting like in the mapbox studio editor (screen 2) ?

i often come across outdated documentation, am i looking wrong or is it to be fixed ?

thanks in advance if i was not clear in my questions please ask me.

Screen 1
![Screenshot_2022-12-07-16-45-26-552_com DefaultCompany p](https://user-images.githubusercontent.com/76961588/206240117-658dfe24-2802-4352-8cc0-8d600cb63685.jpg)

Screen 2
![capture](https://user-images.githubusercontent.com/76961588/206240150-2db7e496-21cb-4d75-bbec-8fc4972a1652.PNG)

**Comment by Frixs** [comment]
Hello @mezzaphilo.

1-Yes, 2-Yes, and 3-Not sure.

1. Simply said, you can spawn your own prefab and make it move based on the coordinate data from other players.

2. By default, the map is using rasterized styles that you can customize in Mapbox studio to your needs.
But, you can make your map based on vector graphics you can make on your own.

3. I'm not fully sure, but I don't think you can make street names float, but you can spawn prefabs that hold the texts, but I'm not sure if you can take the position of the street labels from the map data.

The thing with old documentation is a real thing to talk about. The Mapbox SDK for Unity didn't get any update for quite a long time. If you aren't looking for AR, you can work with the newest Unity editor without any issues. But even tho, the latest version of Mapbox is not properly optimized as you might expect. If you are planning to build with Mapbox, you will probably end up touching the Mapbox code very soon. And because of that and quite a poor optimization, documentation, etc. It's quite a steep learning curve to get into Mapbox SDK.  
At the end of the day, if you are not planning to write your own SDK for maps, there are not many SDKs out there to choose from.
Anyway, it seems the work on this project is still going on... and hopefully, we get some major improvements as soon as possible.

There are some links that might help you with further development:
[http://barankahyaoglu.com/](http://barankahyaoglu.com/)
[https://github.com/mapbox/mapbox-unity-sdk/issues/1886](https://github.com/mapbox/mapbox-unity-sdk/issues/1886)

If you are planning to use URP, you can convert Mapbox SDK into it, BUT not everything works as expected. Texturized buildings are not convertible as easily. Thankfully, ShaderGraph is available in the built-in renderer from newer versions of Unity so I wasn't really forced to go for URP.
