### ISSUE TITLE
Best way to change map zoom level at run time. 

### ISSUE THREAD

**Issue by xinleng** [mapbox/mapbox-unity-sdk#202]
I am not sure this is the right place to ask the questions, as this is not really a bug. Maybe I am missing something - How would one change map zoom level at run time ?  Changing the "Zoom" currently messes up the map tiles .

**Comment by xinleng** [comment]
Looks like this - [http://www.evernote.com/l/AByXfOjixjdL7Kgfjzcp2l6GmsI9_ZzgV9c/](url)

**Comment by david-rhodes** [comment]
@xinleng The short answer is that this is technically a bug/missing expected feature (see: https://github.com/mapbox/mapbox-unity-sdk/issues/121). 

We are working on a solution! You can work around this in the meantime. The steps to fix would be:
1. Ensure that you recompute `IMap` CenterMercator and WorldRelativeScale every time zoom changes.
2. Offset your map root transform so that the previous screen center lat/lon is still the screen center.
2. Ensure that your `TileProvider` removes all tiles that are not at the current zoom level.
3. Add the newly requested tiles in `TileProvider`.

**Comment by ahokinson** [comment]
It takes a bit of reworking the AbstractMap.cs class as well as the AbstractTileProvider.cs class, but using the CameraBoundsTileProvider, I am able to reset the zoom level using the following:

```
private void ResetMapZoom(int zoomLevel)
{
	_tileMap.Zoom = zoomLevel;
			
	_tileMap.SetReferenceTile();
	_tileMap.TileProvider.ActiveTiles = new List<UnwrappedTileId>();
	_tileMap.GetComponentsInChildren<UnityTile>().ToList().ForEach(ut => Destroy(ut.gameObject));
}
```

Great advice, @david-rhodes.

**Comment by ahokinson** [comment]
Should quickly mention that using this method, I am noticing that some tiles do not update their textures. Any advice on how to debug this?

[Old Map Textures Remain](https://streamable.com/vsxnx)

**Comment by david-rhodes** [comment]
@ahokinson You shouldn't need to destroy anything in `ResetZoom`. Rather, just call `RemoveTile` for each of those tiles. This will cause those objects to go back into an object pool in `MapVisualizer`. This is faster and easier on the GC. It may also fix this bug where old map textures remain. Another thing to consider is that the tile request may have failed for some reason, and that's why you see the old texture. You should try to log that in the `MapImageFactory`.

**Comment by ahokinson** [comment]
I replaced that line with this as suggested,
```
_tileMap.GetComponentsInChildren<UnityTile>().ToList().ForEach(ut => _tileMap.TileProvider.RemoveTile(ut.UnwrappedTileId));
```
but as you can see here,
![screen shot 2017-09-14 at 6 09 14 pm](https://user-images.githubusercontent.com/1762048/30458069-f78d0db4-9977-11e7-8e1d-88e6dc55d535.png)
the tiles from zoom level 10 remain.

Any advice?

**Comment by david-rhodes** [comment]
@ahokinson Any reason you are using get component instead of just using a reference to those tiles directly in your tile provider implementation? 

I also suspect this line will break things: `_tileMap.TileProvider.ActiveTiles = new List<UnwrappedTileId>();` because it will clear the MapVisualizer's object pool and no longer knows how to recycle those existing tiles.

**Comment by david-rhodes** [comment]
This is now in develop. Please see both DynamicZoom and MapReload scenes!
