### ISSUE TITLE
Camera Bounds Tile Provider freezes camera movement when loading

### ISSUE THREAD

**Issue by Itemshopp** [mapbox/mapbox-unity-sdk#226]
Now that I have a map loading Roads and Buildings perfectly, I want to make sure it could generate other tiles when I move the camera in every direction.
So I need to add the CameraBoundsTileProvider script to the Map Object. Everything is fine except one thing : 

Everytime the camera needs new tiles to be generated, it takes 1 second to generate it and it freezes the camera movement, so we get a lag making my application not usable. 
I can understand that it has to take 1 second to create the tiles to generate, but what I think could improve the user experience is to let the camera move despite the slow tile generation without any lag. The camera could go into empty spaces but it won't stop it.

Do you think this is possible ? And how can I improve it ?

**Comment by david-rhodes** [comment]
@Itemshopp Your best bet would be to thread all that mesh generation (easier said than done, unfortunately). Alternatives are to process everything in the factory structure inside coroutines to prevent locking the main thread.

**Comment by thefoofighter** [comment]
@david-rhodes Is threading something that will be coming to the SDK? If so have you a rough ETA?
Thanks :)

**Comment by david-rhodes** [comment]
@thefoofighter Honestly, this is something we tried before. It's a bit difficult because (final) Unity mesh creation must be on the main thread. We would likely have to overhaul the map factory framework to support additional threading. At least web requests and decoding should already be threaded behind the scenes (thanks to `UnityWebRequest`). 

We will probably wait until Unity releases the C# job system before attempting this again, but I'm not holding my breath that that will be a magic bullet.

In the meantime, coroutines would at least alleviate the blocking mesh generation (something like a load balancer).

**Comment by david-rhodes** [comment]
Closing in favor of #262
