### ISSUE TITLE
Snap Map Height to Zero does not appear to be working . . . 

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#255]
After vertex scaling branch was merged. I suspect the y value is not scaled properly?

To replicate:
1. Make sure you clear you cache to avoid this issue: https://github.com/mapbox/mapbox-unity-sdk/issues/194
2. Load a map (slippy usually works great) in a region with very high elevation (Mt. Fuji) and high zoom (17).
3. Notice map is not visible in camera (but above camera).

**Comment by brnkhy** [comment]
@david-rhodes found the problem; a basic mistake with scaling. 
After this new scaling system, we are scaling height query in the query method itself. but abstract map was scaling it again after the query.
After removing that, fuji looks like this;
![unity_2017-09-26_16-26-28](https://user-images.githubusercontent.com/1465390/30862658-7c71d10a-a2d7-11e7-8388-43d860868188.png)
you can see map gizmo is way above world origin (white line corner). That's because height fix uses first loaded tile and camera tile bounds provider loads the corner tile first (bottom right in that shot). I remember fixing tile range provider to load center tile first to prevent this for example. Not a big issue but wanted to clear that out.

PR here; https://github.com/mapbox/mapbox-unity-sdk/pull/257

**Comment by brnkhy** [comment]
@david-rhodes I thought marking ticket number in commit log like "fixes #256" automatically closes issue when it's merged. Aaah it's because we haven't merged to master right? Anyway closing this as it's merged to dev
