### ISSUE TITLE
Memory Leaking when discarding tiles with meshes

### ISSUE THREAD

**Issue by ErikBehar** [mapbox/mapbox-unity-sdk#275]
1) change any of the mesh generation examples tile provider to a CameraBoundsTileProvider
2) move camera around enough so that tiles are discarded
3) look in profiler > memory section > detailed > Take Sample 
See Scene Memory slowly climb up, look at number of meshes with no references.
Memory can be freed by running Resources.UnloadUnusedAssets but calling it
causes large hiccup.

**Comment by brnkhy** [comment]
@ericdeveloper I've been looking into performance and memory issues lately and posted about it a little here; https://github.com/mapbox/mapbox-unity-sdk/issues/262
From what I understand, Unity doesn't GC meshes even if there are no references to it. We used "UnloadUnusedAssets" in a few demos for a quick fix. As you noted it'll cause an hiccup. It's not noticable for "location change" type of stuff but surely won't work for slippy map movement.
I believe the solution here is to create a pooling system for vector layer that'll reuse gameobjects and its monobehaviours like mesh filter and mesh renderer so that we'll never end up with those no-ref meshes in the first place.
I think I'll be looking into this next few days, will post here again if I can get something going. Thanks for the step-by-step report @ericdeveloper !

**Comment by brnkhy** [comment]
@ericdeveloper I did some tests with a basic pooling system and 
went from this;
![2017-10-04_18-31-56](https://user-images.githubusercontent.com/1465390/31184628-9a30e99a-a932-11e7-9288-2560a1206ec1.png)
to this;
![2017-10-04_18-32-50](https://user-images.githubusercontent.com/1465390/31184633-9f2c61a4-a932-11e7-91db-d87fa2bbbe58.png)

What I did was a just a hack though (had to spent most of my time debugging some side effects) and doesn't use pooling to full strength. Still it saved around 10mb in an extremely small scene. I'll look more into this next few days and try to get a proper test branch out.

**Comment by david-rhodes** [comment]
@ErikBehar Thanks for the note! We'll investigate.

**Comment by brnkhy** [comment]
@ErikBehar  pushed object pooling and memory improvements here; https://github.com/mapbox/mapbox-unity-sdk/tree/ModuleInitialize
should fix the mesh memory leak and reduce memory usage quite a bit as well.

**Comment by ErikBehar** [comment]
@brnkhy thanks looks good !

**Comment by brnkhy** [comment]
all memory fixes and improvements merged into dev branch, closing this for now and we can have new tickets if we ever have leaks/issues.
