### ISSUE TITLE
Inclusion of the north and south poles within Globe

### ISSUE THREAD

**Issue by zachyale** [mapbox/mapbox-unity-sdk#298]
Hey guys,
Are there any plans on adding tiles for the north and south poles to the Globe? Any advice for me if I wish to implement them? Thanks!

**Comment by david-rhodes** [comment]
Web mercator projection is usually limited to extents of -85 to 85 degrees latitude. This is because the amount of area described by a tile at extreme latitudes would quickly approach infinite.

So, to "solve" this problem, there are a few possibilities:
1. Model and texture the missing caps in a 3D modeling software--include these in your scene
2. Procedurally generate cap meshes and use surrounding texture information to "blend" the caps
3. Generate extra edge loops for the final tile rows (approaching the poles) and use those to generate the caps. Stretch the textures used for those tiles.

My personal preference would be option 3. I imagine this would offer a nice blend of quality and ease of use.

**Comment by david-rhodes** [comment]
cc @brnkhy Any other suggestions?

**Comment by zachyale** [comment]
Is this feature still in the pipeline?

**Comment by david-rhodes** [comment]
@zachyale At this point, we don't have this feature on our roadmap. But, I firmly believe the best approach would be to subdivide and stretch the final rows of tiles (approaching the poles). This could likely be done in `FlatSphereTerrainFactory`. 

As an alternative, is there any reason you need this poles? Can you perhaps clamp the camera so that it is not possible to see the gaps?
