### ISSUE TITLE
Ensure SDK works if asset is nested in Unity project

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#327]
**Context:** Developers often move external plugins inside their projects for organization purposes or to decrease compile times.

**Problem:** Apparently, moving the Mapbox asset will cause iOS builds to fail due to some "hardcoded" paths. Reference: https://github.com/mapbox/mapbox-unity-sdk/issues/301#issuecomment-339650769

**Solution:**  Let's ensure iOS dependencies do not have hardcoded paths or that the paths can be found procedurally as part of a build step. Perhaps inside https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/Editor/Build/Mapbox_iOS_build.cs?

**Next Steps**
- [ ] Investigate and reproduce the issue
- [ ] Procedurally identify location of required libraries in build scripts

**Comment by LastMonopoly** [comment]
This bug happens to me as well, move `Mapbox` folder directly under `Assets` folder solves it.

**Comment by apavani** [comment]
I discovered that this error occured for me because I had the `Symlink Unity Libraries` checkbox turned on while building for iOS.
Please make sure this is unchecked before building
![33154796-e62110da-cf9f-11e7-8010-c7e488e81b6b](https://user-images.githubusercontent.com/8422708/33285979-dbd53dc8-d368-11e7-857f-3b3a5634654a.png)
