### ISSUE TITLE
Enable simple placement of objects on maps with elevation

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#330]
**Context:** Developers would often like to place custom markers (prefabs) on maps. 

**Problem:** Placing objects on a map outside the Map Factory Framework (with custom modifier and `SnapTerrain`) is a bit cumbersome and requires access to a `UnityTile` or a `MeshCollider` on the terrain mesh.

**Solution:**  We should wrap the complexities in a simple method call, similar to `Conversions.GeoToWorldPosition`, but taking elevation into account. Note that this is possible with raycast, but only if terrain is using a `MeshCollider`. Therefore, I propose two method overloads: one that uses raycasting (and optional `LayerMask`) and another that uses elevation data (currently residing in `UnityTile`). This lookup should be performant.

**Next Steps**
- [ ] Discuss implementation details with team
- [ ] Determine where these methods should be implemented (and what references are needed)
- [ ] Refactor code necessary to enable functionality

**Comment by brnkhy** [comment]
We discussed this earlier but I think this is relevant to the idea of keeng track of things in map visualizer. So for example if we keep track of unity tiles and features in Map Visualizer, you can query which tile contains a certain point and get point height from that tile. That would also be extremely fast, in constant time, O(n).
This enables some other nice stuff as well, like keeping track of all buildings in a quad tree and query for "buildings in x meter range" extremely fast.

**Comment by mdepak** [comment]
Could you provide the options available now to find elevation of the building at specified unity coordinate? I looked in the couple of issues where you guys suggested to use UnityTile's queryheightdata method to find elevation. But my basic question is how do i access to the tile object at specified location from the code.

**Comment by david-rhodes** [comment]
@mdepak The suggested method is to "query" height using the `SnapTerrainModfier` as part of the Map Factory Framework. In other words, placing objects on your map is much simpler if using factories, stacks, and modifiers (as seen in our examples). This is because tile data is known and implicitly queried at generation time. That said, you can also just create a mesh collider for your terrain and do a simple raycast from camera to get the height (post-generation).

Lastly, you could raycast to `GetComponent<UnityTile>()` and then directly query it's height.

**Comment by mdepak** [comment]
@david-rhodes I tried adding mesh collider to terrain factory by checking "Add colliders" checkbox but mesh colliders are not added for the buildings. So I modified the private variable `private bool _addCollider = false;` to true and then mesh colliders were added. Then casted ray from height 50 to downward direction. All the rays are hitting the ground even thought the buildings have mesh collider added. 
`		RaycastHit hit;
		float distance = 100f;
		position.y = 50;
		Vector3 targetLocation;


		if (Physics.Raycast(position, Vector3.down, out hit, distance)) {
			targetLocation = hit.point;
			int height = targetLocation.y;}` 

Am I doing something wrong with casting ray on the buildings. First problem is colliders are not added on checking checkbox and then even after manually adding the colliders ray hits the ground instead of buildings. Thanks

**Comment by david-rhodes** [comment]
@mdepak You can add colliders to the buildings by using a `ColliderModifier` in the building's modifier stack and selecting which type of collider you want.

When are you performing the raycast? If during map generation, it may be that the buildings don't yet have their colliders. Also, check that layer masks are not being used (and you are not ignoring building layer in your raycast).

What is your ultimate goal? Perhaps we can suggest the best approach?

**Comment by mdepak** [comment]
Objective is to place the prefabs in the top of the buildings of the mapbox. Since different buildings are of different height, I would like to find a way to query the height of building at particular position(unity coordinate). I am calling the code to plot markers in the Map.OnInitialized().

**Comment by david-rhodes** [comment]
I suggest that you add collider and layer modifiers to your building stack. Then, create a custom modifier or factory that spawns your desired objects and use a `SnapTerrainRaycastModifier` in it's stack (and choose the matching layer mask to coincide with your building layer). Just make sure this layer is processed after buildings and everything should work.

Please see the example project outlined here for reference: https://blog.mapbox.com/building-a-location-based-game-in-20-minutes-7ae94e9affd1.

**Comment by LastMonopoly** [comment]
@david-rhodes 
Hi david, the example project from the link above have a serious SnapTerrainRaycastModifier bug after upgrading to mapbox-unity-sdk 1.2.0, please take a look at my minimal bug report here: https://drive.google.com/file/d/0BxSVxZzIRMHIMVlyeGo1Y0JnenM/view?usp=sharing

The layers in "Part_05_Terrain" and "Part_05_BuildingSnapRaycast" are supposed to be exact; however, after upgrading to sdk 1.2.0, you have to set them different in order to display properly.

It drives me crazy, please take a look, thanks a lot!

**Comment by david-rhodes** [comment]
@LastMonopoly We've seen similar issues in the past. I suspect this is a Unity bug, and not an issue with Mapbox code. One thing you can try is to delete layers and add them again, then set the layers manually for each modifier (and the terrain factory).
