### ISSUE TITLE
Add serialized string field to height modifiers to support data-driven extrusions

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#344]
Current `HeightModifiers` (including chamfer) use hardcoded property names ("height"). But, to enable even more flexibility, we can allow that key to be user defined (eg. extrude polygon based on population density).

Same approach could be used for any modifiers that we may want to consume custom data.

**Comment by brnkhy** [comment]
I wasn't sure about this when I wrote that mainly because it would complicate the inspector for a property won't change 99% of the time.
"classification key" in layer visualizer is different for example, you have to change it for roads, traffic etc. 
but height modifier (it is called height modifier to being with) has only one different case I can think of; "ele" property in contour layer.
I'm not against this either, it's just a design choice I guess but I feel like at that point you can should just change code.

Also another point; this field will be a string field, as we can't make it an enum for obvious reasons. String fields are hard to control, if user deletes it by mistake, they'll have to go look for default value.  Or we'll need a reset button for that as well etc etc.

Considering all that, I think I would prefer not doing this and having a custom elevation modifier for contour lines.

**Comment by david-rhodes** [comment]
We can easily default the string to `height`. 

> but height modifier (it is called height modifier to being with) has only one different case I can think of; "ele" property in contour layer.

How about for population density? :trollface: The general idea is that we should strive to make this a data-driven visualizer so developers don't necessarily need to create their own modifiers. This is just one example.

**Comment by brnkhy** [comment]
I agree on data driven UI, I just don't like the text boxes in inspector for stuff like this. Maybe we can have a better UX for this, like a dropbox for three options; 
custom float height (forcing height on stuff), 
default height property,
custom property name (this shows an empty textbox)
