### ISSUE TITLE
Exception with cached tiles.

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#345]
So I've been getting this weird exception sometimes, and I think it's because I'm running two maps in one scene (man map & a minimap), but I might be wrong here.

The exception is:
```
[Exception] ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[Mapbox.Unity.MeshGeneration.Data.UnityTile,Mapbox.Map.VectorTile].Add()    /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404

VectorTileFactory+<OnRegistered>c__AnonStorey0.<>m__0()    Assets/Addons/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:72
70:   }
-->72:   _cachedData.Add(tile, vectorTile);
74:   // FIXME: we can make the request BEFORE getting a response from these!

Tile.HandleTileResponse()    Assets/Addons/Mapbox/Core/mapbox-sdk-cs/Map/Tile.cs:226
224:           _state = State.Loaded;
225:       }
-->226:       _callback();
227:   }

CachingWebFileSource+<Request>c__AnonStorey0.<>m__0()    Assets/Addons/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/CachingWebFileSource.cs:159
157:                   }
158:               }
-->159:               callback(r);
160:           }, timeout);
161:   }

HTTPRequest+<DoRequest>c__Iterator0.MoveNext()    Assets/Addons/Mapbox/Unity/Utilities/HTTPRequest.cs:87
85:   }
-->87:   _callback(response);
88:   _request.Dispose();
89:   _request = null;

Runnable+Routine.MoveNext()    Assets/Addons/Mapbox/Unity/Utilities/Runnable.cs:130
128:   public bool MoveNext()
129:   {
-->130:       m_bMoveNext = m_Enumerator.MoveNext();
131:       if (m_bMoveNext && Stop)
132:           m_bMoveNext = false;

SetupCoroutine.InvokeMoveNext()    C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17
```

Any ideas?

**Comment by BergWerkGIS** [comment]
@mihakrajnc thanks for reporting, that shouldn't happen.
Will look into that during the next weeks.

**Comment by david-rhodes** [comment]
@mihakrajnc Are you using the same `MapVisualizer` or `VectorTileFactory` asset? If so, this is likely the culprit. The reason is because each asset tracks knowledge of its tiles. If one asset is responsible for the same tile through different maps, then there will be duplicates.

If it's not that, then what type of `TileProvider` are you using? You need to be careful about when you request and dispose tiles.

**Comment by BergWerkGIS** [comment]
@david-rhodes might be, but that should never happen anyways.

Cache checks if tile exists or not before trying to insert:
https://github.com/mapbox/mapbox-unity-sdk/blob/f0bf532549f302c33f3b7b2f23b7e2810c078ddb/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/MbTilesCache.cs#L85

I suspect some race condition (or other bug), as we are not locking between checking and inserting (performance).

Nevertheless, some more information from @mihakrajnc when and how he observed the error will be helpful.

**Comment by david-rhodes** [comment]
```VectorTileFactory+<OnRegistered>c__AnonStorey0.<>m__0()    Assets/Addons/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs:72```

This line seems to suggest that the duplicate is a problem inside `VectorTileFactory`. The `_cachedData` dictionary in this class is not related to our file cache.

**Comment by mihakrajnc** [comment]
@david-rhodes That's what I'm thinking. Not using any common assets between the maps. The structure of the main map is pretty big, but the other one (the minimap) only has one custom factory (that places the tiles on the uGUI - basically a copy of MapImageFactory with a few modifications.) and nothing else.

The tile provider is also a modified version of `RangeAroundTransformTileProvider` but instead of a transform it hooks into our location service.

Reproducing it is tricky, as it seems to happen randomly, but when it starts I usually get a lot of exceptions in a short amount of time (40+).

**Comment by david-rhodes** [comment]
Yeah. I've seen this with the CameraBoundsTileProvider before. It's more prevalent the faster the tiles are requested and disposed. My guess is that there's some temporal coupling between tile provider and map visualizer. 

Ohhh.... are you using an update frequency in your tile provider, like our `update interval`? Because if so, I am 90% sure that's the problem.

**Comment by mihakrajnc** [comment]
@david-rhodes Hmm, not really using an update frequency directly, but it does have one.

The tile provider is basically this:
```csharp
internal override void OnInitialized()
{
    base.OnInitialized();
    initialized = true;
    telemetryService.Provider.OnLocation += OnLocationUpdated;
}

private void OnLocationUpdated(Vector2d location)
{
    if (initialized) // Not sure what the point of this check was... ¯\_(ツ)_/¯
    {
        UpdateTiles(location);
    }
}

private void UpdateTiles(Vector2d location)
{
    currentTile = TileCover.CoordinateToTileId(location, _map.Zoom);

    // Same as RangeAroundTransformTileProvider
}
```

The `OnLocationUpdated` callback gets called whenever the location is updated, which can vary, but it's generally around 1 second.

**Comment by BergWerkGIS** [comment]
> class is not related to our file cache.

oops, thanks for pointing that out @david-rhodes - just read `cached tiles` and thought it was about the file cache.

**Comment by whilesoftware** [comment]
I'm seeing the same exception, using a custom tileprovider with an update frequency of 0.2s.

I have only one map in my scene.

@david-rhodes you mentioned that using an update frequency is likely the problem. You also mentioned we need to be careful requesting and disposing tiles.

Can you elaborate? What does it mean to "be careful"? :)

**Comment by david-rhodes** [comment]
@whilesoftware Hah, great question! There needs to be a mechanism to prevent duplicate tiles from being requested, since objects down the chain (`MapVisualizer`) keep an internal dictionary of which tiles are "active."

I would assume this case is covered here: https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Unity/Map/AbstractTileProvider.cs#L28, but somehow duplicates are being added, still. 

My guess is that the internal `active tiles` in `AbstractTileProvider` and `AbstractMapVisualizer` are going out of sync somewhere. 

I'm having a hard time reproducing this, so sample code or help debugging would be awesome!

**Comment by whilesoftware** [comment]
Poking around in VectorTileFactory... seems like the bug is that OnUnregistered does not remove pending tiles from _cachedData. The event handlers are dropped, but for pending tiles that means _cachedData.Remove(tile) never gets called.

After making the following change, i cannot reproduce the issue:

```
	internal override void OnUnregistered(UnityTile tile)
	{
		// We are no longer interested in this tile's notifications.
		tile.OnHeightDataChanged -= DataChangedHandler;
		tile.OnRasterDataChanged -= DataChangedHandler;

		// clean up any pending request for this tile
		if (_cachedData.ContainsKey(tile)) {
			Progress--;
			_cachedData.Remove(tile);
		}
	}
```

**Comment by david-rhodes** [comment]
Thank you @whilesoftware! PR for this fix is now active.

**Comment by david-rhodes** [comment]
#400
