### ISSUE TITLE
Mapbox for Unity: How to make a map only for a specific place?

### ISSUE THREAD

**Issue by AkaneMikazuki** [mapbox/mapbox-unity-sdk#351]
Hi! I've been working on a project in Unity which uses mapbox to produce a real-time map by getting the player's GPS information. I only want the map to focus on a specific area and not on the whole world, though. Can this be set on Mapbox Studio? Thank you in advance.

**Comment by david-rhodes** [comment]
Set your map's latitude/longitude using the player's GPS information, and then adjust the map's zoom level accordingly. The higher the zoom, the less physical area represented in each tile.

**Comment by AkaneMikazuki** [comment]
Thank you. But the player would still be able to reach areas that are beyond the scope of my game. I would want to forbid them from doing that. Could it be coded or something?

**Comment by david-rhodes** [comment]
@AkaneMikazuki I'm not sure I fully understand. If you use a `RangeTileProvider`, only tiles around a specific location will be fetched. But really, what is the use case outside the scope of your game? What would you expect players to see in the event they are outside your bounds? There are likely many ways to achieve what you are trying to do, but having more information will help us to assist you better.

**Comment by AkaneMikazuki** [comment]
Hello, Mr. David. I am creating a game where the player's GPS is fetched and that would be his location on the map I have created. The player (character in the game) would move as the player moves (Like in Pokemon Go). So my problem is that I'm not creating a world-wide game, only focusing on a certain area, and I want to detect when the player's GPS is not on that area, so the map wouldn't display and the player would be prompted by a message. 
Thank you so much for answering.

**Comment by david-rhodes** [comment]
Yes, I recommend you just make a separate component (script) that takes the latitude/longitude from the `DeviceLocationProvider` and checks if it is inside a specific geographical bounds object. If you need more precise bounds checks, you can use a more advanced "point in polygon" algorithm to test if the player is inside the complex geometry (your region).

If you can use tiles for your region (rather than a geo bounds or complex geometry), then you can check if the player is outside all known loaded tiles by using `Conversions.LatitudeLongitudeToTileId()` to see what tile the player is in. If this tile does not exist in the game, then they have left the map area.

**Comment by AkaneMikazuki** [comment]
I'm not sure I get it completely, but I'm currently working on it and will post soon for updates. Thank you, sir!

**Comment by david-rhodes** [comment]
Closing for now--let us know if you still need help.
