### ISSUE TITLE
MapEditor Unity Window High CPU

### ISSUE THREAD

**Issue by Crashthatch** [mapbox/mapbox-unity-sdk#392]
When I have the "Map Editor" tree-view open, my CPU sits at ~40% when the window has focus and ~10% when it doesn't have focus. This makes my laptop fans run loudly. Very low priority, but a bug nevertheless.

![image](https://user-images.githubusercontent.com/186067/33209194-aa93a30c-d10c-11e7-87bb-823c18d30b4c.png)

Weirdly, recording my screen causes the "doesn't have focus" cpu to drop from ~10% to ~4% which is why you see that in the video.

Video: https://www.dropbox.com/s/i31my9ijqg17s7x/unity-high-cpu-bug.mp4?dl=0

(Also, it was days before I even found the map editor window - and it's so much nicer than editing through the inspector and hand-drawing the trees so I can make sense of it - might be worth signposting it in the tutorial / documentation a bit more!)

![20171124_114028](https://user-images.githubusercontent.com/186067/33209254-e48b131a-d10c-11e7-9796-358e61ffd292.jpg)

**Comment by david-rhodes** [comment]
Thank you for the feedback!

**Comment by brnkhy** [comment]
I tried to look into this today but couldn't do much I'm afraid. 
I'm still not good at editor stuff so I might be missing something. And node editor classes are quite heavy as it does lots of unnecessary allocations and stuff but when I look at the profiler, it looks like there's simply too many nodes and basic calls like `GUILayout.BeginArea`.
No doubt cleaning stuff would help a bit but I feel like it won't be noticable at all. Node editor needs a total rewriting/refactoring soon anyway so we probably can look into a better (probably flat instead of nested) structure to render nodes.
