### ISSUE TITLE
Improve precision of lat/lon that Unity reports

### ISSUE THREAD

**Issue by david-rhodes** [mapbox/mapbox-unity-sdk#425]
Unity should have fixed by now, but alas: https://feedback.unity3d.com/suggestions/gps-accuracy-double.

😢

**Comment by edwardpotter** [comment]
I get that unity has defined it as a float - but when I define say playerLat as a double, then populate it with Input.location.lastData.latitude - I end up storing what certainly seems to be a true, accurate double representation of the Lat.  I'd have thought it would just be a float (7digit) with the remaining precision to 16 digits as all zeros.

Where should I be looking for the impact of Unity's handling?  Since I've got a heavy-GPS based game, I want to make sure I'm looking under the right stones...

**Comment by david-rhodes** [comment]
I'm not sure I follow. How can a float being casted into a double still represent full precision?

I have a feeling that the data you are seeing is just trash floating around in memory (random data). I don't recommend trusting it.

Until Unity gets their act together, the best approach would be to write your own native location adapters for Unity.

**Comment by YayBeards** [comment]
There's a somewhat ridiculous workaround to the issue:
https://forum.unity.com/threads/gps-float-precision-issue.275180/
https://forum.unity.com/threads/precision-of-location-longitude-is-worse-when-longitude-is-beyond-100-degrees.133192/

**Comment by david-rhodes** [comment]
Ridiculous indeed. 😆

**Comment by BergWerkGIS** [comment]
Solved for Android via a custom native location provider plugin: https://github.com/mapbox/mapbox-unity-sdk/pull/724

**Comment by Spirit30** [comment]
[Accura GPS for Unity](https://www.assetstore.unity3d.com/#!/content/122437) is designed to Resolve this problem.
