### ISSUE TITLE
Speed Calculation Location provider

### ISSUE THREAD

**Issue by tahoorpirzada** [mapbox/mapbox-unity-sdk#450]
I am making an app in which while I am using location provider I want to check whether the user is static, running, walking or driving. Is there a way I can calculate the speed?

**Comment by BergWerkGIS** [comment]
Static might be determined by *not* getting udates because of movement is less than `updateDistanceInMeters `.
See https://docs.unity3d.com/ScriptReference/LocationService.Start.html

For other modes of movement:
[this work-in-progress branch](https://github.com/mapbox/mapbox-unity-sdk/tree/probe-extractor) has a port of the JavaScript [cheap-ruler](https://github.com/mapbox/cheap-ruler) module, which you can use to calculate the distance between points.
And based on the distance and the timestamps of the last two GPS locations calculate speed and then determine mode of movement.
