### ISSUE TITLE
MapboxConvenience - bad Monobehaviour Singleton implementation

### ISSUE THREAD

**Issue by Naphier** [mapbox/mapbox-unity-sdk#46]
The current destruction of the only MapboxConvenience instance was happening after I built for a standalone exe. I've addressed this with the following changes:

```
public override void Awake()
		{
			/*
			if (s_instance != null)
			{
				Destroy(gameObject);
				return;
			}
			*/
			base.Awake();

			if (s_instance != this)
			{
				Destroy(gameObject);
				return;
			}

			if (string.IsNullOrEmpty(_token))
			{
				throw new InvalidTokenException("Please get a token from mapbox.com");
			}

			if (_fileSource == null)
			{
				_fileSource = new FileSource(this);
				_fileSource.AccessToken = _token;
			}
		}
```

**Comment by david-rhodes** [comment]
@Naphier Thank you for the report and solution. We noticed this too, which is [why we changed our token access paradigm](https://github.com/mapbox/mapbox-unity-sdk/blob/e7d9de2c33088295e8fb953ac9a1b0816b470f9d/sdkproject/Assets/Mapbox/Core/Unity/MapboxAccess.cs). Gameobjects are no longer required to make API calls.

**Comment by binakot** [comment]
May be this will helpful http://wiki.unity3d.com/index.php/Singleton
Because in SDK I see the Singleton implementation which not inherits MonoBehaviour.
And you should do something like that https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Core/Unity/Utilities/Singleton.cs and https://github.com/mapbox/mapbox-unity-sdk/blob/develop/sdkproject/Assets/Mapbox/Core/Unity/Utilities/Runnable.cs
Not Unity way 😎

**Comment by david-rhodes** [comment]
@binakot Can you elaborate, please? We intentionally removed the need to have a persistent object in the scene. Are you experiencing issues with the current `MapboxAccess` paradigm?

**Comment by binakot** [comment]
@david-rhodes No, I have no issue with the current MapboxAccess paradigm. Everyting works. I saw previous implementation of Singleton, when I was using earlier version of SDK. I just thought that this information would be useful if you have a package with utils in the project.
