### ISSUE TITLE
Latitude/longitude string not centered on load

### ISSUE THREAD

**Issue by MitchEff** [mapbox/mapbox-unity-sdk#471]
***EDIT: please disregard this, it just randomly started working for whatever reason.

Hey there,

Apologies if this is covered elsewhere, I've searched high and low and can't find any documentation or a tutorial covering this. 

I'm just trying to get some sort of meaningful value out of CenterLatitudeLongitude, but it's just always zero. 

I have a GameObject called 'map', which has a 'BasicMap' script attached to it, which is rendering just fine. I also have another GameObject with the following script on it:

```
public GameObject map;

void Start () {
    BasicMap _map = _map.GetComponent<BasicMap>();
    Debug.Log(_map.CenterLatitudeLongitude);
}
```

The 'map' instance is set to the 'map' GameObject and that all seems fine, but it only ever returns 0.00000, 0.0000. Am I doing that right? Does anyone know of any examples they can send over? I'm sort of just stabbing in the dark here. 

Cheers,

**Comment by atripathi-mb** [comment]
@MitchEff  You need to wait until the map is initialized in order to get meaningful values from CenterLatitudeLongitude (or any map properties). I would recommend adding a listener to the `OnInitialized` call on the map. 

Also, look at `MapAtSpecificLocation` for a map centered at the Lat/long specified by you.

**Comment by atripathi-mb** [comment]
@MitchEff Let us know if you still have issues with lat/long strings.
