### ISSUE TITLE
mapbox unity sdk v1.2 missing material modifier!!!!

### ISSUE THREAD

**Issue by l3iwin** [mapbox/mapbox-unity-sdk#476]
I'm trying to fix it!!! I don't have the MaterialModifier.cs on the unity package!!
Can someone help me please?? Thank you

**Comment by jordy-isaac** [comment]
Hi @l3iwin, 

On 1.2 you can use `Texture Modifier` instead of `Material Modifier`. Also, you can install the latest version by [cloning](https://github.com/mapbox/mapbox-unity-sdk#from-this-repository-advanced-latest-development) the repo instead of the download page. The download page will be updated soon, but the latest available here.

**Comment by brnkhy** [comment]
@l3iwin just for the clarification, I think this is because we updated the docs for v1.3 but couldn't release it in time, so yeah docs are going ahead :)
We'll release v1.3 soon, meanwhile you can get the latest from develop branch or use rather similar texture modifier for the v1.2 as @jordy-isaac suggested.

**Comment by jordy-isaac** [comment]
1.3 has been released and is available on the [download page](https://www.mapbox.com/install/unity/). Closing this out.

**Comment by banmeel** [comment]
## Hi.. i have the same problem, when i click on  Submesh 0 Material. I cant 
Change the Size to 1.Also i cant add a material to it . any suggestions ?
thanks
