### ISSUE TITLE
Getting None(Mono Script)  issue while creating TerrainFactoryWithSideWalls factory at version 1.3

### ISSUE THREAD

**Issue by ufktvfk** [mapbox/mapbox-unity-sdk#479]
At Version 1.3, I tried to build TerrainFactoryWithSideWalls factory but after creating the factory, its script seems to be absent. 
![ekran alintisi](https://user-images.githubusercontent.com/23186662/34409688-fe555abc-ebd3-11e7-8c66-c44850791667.PNG)

However, when  I implement this in my mapbox object it works but after restarting Unity project, terrain factory is missing:  
![ekran alintisi3](https://user-images.githubusercontent.com/23186662/34409776-adc52fc2-ebd4-11e7-9967-2a045f8d699f.PNG)

How can be fixed or is this something I make wrong?

**Comment by ufktvfk** [comment]
After restarting Unity project, I can not even reuse my  TerrainFactoryWithSideWalls factory. I compare TerrainFactoryWithSideWalls factory script with other terrain factory's scripts but couldn't determine the issue.

**Comment by brnkhy** [comment]
@ufktvfk I believe that's because class name and file name doesn't match for "TerrainWithSideWallsFactory" class. Renaming cs file to "TerrainWithSideWallsFactory" as well should fix this problem. I thought we fixed this for 1.3 actually but I'll recheck. Meanwhile can you try and verify that fixes it please?

**Comment by ufktvfk** [comment]
@brnkhy Yeah I tried it and it fixed the problem. Thank you:-)
