### ISSUE TITLE
TileProviders need a better performance !

### ISSUE THREAD

**Issue by genaray** [mapbox/mapbox-unity-sdk#537]
Im currently developing an little 2D mobile game using mapbox. Due to the huge amount of prefabs im using in my game, im trying to increase the performance. Today i profiled my game and i noticed that RangeAroundTransformTileProvider creates some lags, when moving the camera around. Those lag spikes look like this : https://imgur.com/a/NnTGx

Is it somehow possible to increase the performance of the TileProviders even more ? Is mapbox running on the main thread, or does it use background threads too ?

**Comment by brnkhy** [comment]
@genaray I think this isn't really about tile providers because they don't do anything other than returning tile coordinates.
but abstract map actually registers to tile request event from tile provider so I believe everything you do goes under a Tile Provider method in the profiler. If you do deep profile and check what's under that, you'll most likely see your actual generation (probably game object creation if you have too many of that) taking majority of it.
Please let me know when you check it!

**Comment by MiroMuse** [comment]
Closing this for now, let us know if you need anything else.
