### ISSUE TITLE
How do I know if a tile contains a certain latitude longitude coordinate?

### ISSUE THREAD

**Issue by utkarshdwivedi3997** [mapbox/mapbox-unity-sdk#538]
I'm trying to see whether a certain lat/lon coordinate is contained by an UnwrappedTileID, and I'm not really sure how to approach this. Should I use tile.Rect.Contains() ?

**Comment by brnkhy** [comment]
@utkarshdwivedi3997 
you can do a few different things but I think the simplest one would be using the Conversions.LatitudeLongitudeToTileId method. It returns a Vector2d (which is a mistake if I remember correct, should have fixed this already 🤦‍♂️ ) but you can comparet that to the UnwrappedTileID you have.
You can convert your lat/lng to meters and then use tile.Rect.Contains as well. Be careful though, Contains can be tricky sometimes with inverted y axis and wrong min/max values because of that.

**Comment by utkarshdwivedi3997** [comment]
@brnkhy Thanks! I already did try the tile.Rect.Contains method but that usually gives me one tile off the lat/lon containing tile, for some reason.
Thanks for the tip on using TileId, it really helps!

**Comment by brnkhy** [comment]
@utkarshdwivedi3997 so the `LatitudeLongitudeToTileId` solved your problem right? I'm closing the ticket assuming it did, feel free to open it again.
I'm not sure what's the issue you're having but as I said Contains can get little tricky.
