### ISSUE TITLE
Setting POIs and detecting location update.

### ISSUE THREAD

**Issue by UlisesPereida** [mapbox/mapbox-unity-sdk#546]
Unity Version: 2017.3.1
MapBox Version: 1.3.0
Platform: Unity Android

I'm trying to display POI objects in the map from a series of lat and long coordinates that I receive from a web service, I just can't seem to find quality documentation or examples on how to achieve this. I already have the list of coordinates but I can't seem to find how to create the POI.

Also I'm trying to make an animation transition for a character, based on if the location is updating or not, to switch from Idle to Walk and vice versa, but it seems that the script is always reporting movement so the character is always stuck in the walk animation, if I'm using the location example provided in the package which script should I be checking to see the character or map movement?

**Comment by jordy-isaac** [comment]
@UlisesPereida 

For spawning a prefab please take a look at the `SpawnOnMap` script. There’s an example and documentation for that [here](https://www.mapbox.com/unity-sdk/overview/zoomable-map/#place-custom-markers)

As for your 2nd question about movement. My advice would be to define a threshold for the change in distance to determine if the animation should be walking or idle. If you’re finding that the walking animation is always playing the threshold would need to be higher. If your walking/idle logic is based on location updates then this would cause your issue because it happens at a fixed interval.

**Comment by sumitsingh47** [comment]
> @UlisesPereida
> 
> For spawning a prefab please take a look at the `SpawnOnMap` script. There’s an example and documentation for that [here](https://www.mapbox.com/unity-sdk/overview/zoomable-map/#place-custom-markers)
> 
> As for your 2nd question about movement. My advice would be to define a threshold for the change in distance to determine if the animation should be walking or idle. If you’re finding that the walking animation is always playing the threshold would need to be higher. If your walking/idle logic is based on location updates then this would cause your issue because it happens at a fixed interval.

What are you talking about threshold? i'm not getting ! can you please elaborate more.
