### ISSUE TITLE
Use compass for initial alignment

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#559]
continued from https://github.com/mapbox/mapbox-ar-unity/issues/27

**Comment by briancalvium** [comment]
Is this different from changing the ARKit world alignment mode to use  ARWorldAlignmentGravityAndHeading instead of just gravity? I changed the mode and it does seem to align decently initially (at least on iOS...)

![screen shot 2018-05-04 at 15 38 40](https://user-images.githubusercontent.com/19731838/39633979-74300782-4fb1-11e8-9326-727cb7fdff90.png)

```
 m_SessionConfig = new ARKitWorldTrackingSessionConfiguration(
				settings.enableHeading ? UnityARAlignment.UnityARAlignmentGravityAndHeading : UnityARAlignment.UnityARAlignmentGravity,
```

after the initial alignment it still moves around quite a bit as GPS updates come in with the default settings. Trying changing the bias and min accuracy now.
