### ISSUE TITLE
Smooth Zooming Example

### ISSUE THREAD

**Issue by lukacat10** [mapbox/mapbox-unity-sdk#584]
_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version:  Unity 2017.3.1f1
* Mapbox SDK version: 1.3.0
* The platform you're building to: PC, Android, IOS
* A description of what you're trying to do: Smooth zooming like in gl js mapbox version
* Steps to recreate the bug if appropriate:
* Links to your logs are also helpful: 

Have a look at this example: https://www.mapbox.com/mapbox-gl-js/example/simple-map/
I tried to create the same smooth transition effect in unity, but with no luck. Does anyone know how can such a thing be achieved? Thanks!

**Comment by jordy-isaac** [comment]
Hi @lukacat10 Have you checked out the `ZoomableMap` example in the SDK? You can find it in the `Examples` folder in the SDK. You can also read more about it [here](https://www.mapbox.com/unity-sdk/overview/zoomable-map/)

**Comment by lukacat10** [comment]
Hi @jordy-isaac of course! Thats the reason I cant get a smooth zoom. In the example, when zooming in the tiles turn black while they load new imagery. It also happens with non-satelite imagery. What I want to so is have an effect of "sharpening" tiles, where they turn from their blury zoomed out state into high detail zoomed in state without turning black while loading.

**Comment by jordy-isaac** [comment]
Smoother zoom is something we will work on improving in the future.

**Comment by brianchasalow** [comment]
Hey there- curious if this has seen any recent improvement or if there are plans on your roadmap. Looks like there are several issues that need addressing.
1) Loading tiles are really bad, and obvious. You need to blend between the loaded tile and the next tile to be loaded. 
2) The QuadTreeCameraMovement.cs script should be using the Canvas UI instead of Input.mousePosition and Input.touches, so that input plays nicely with UI objects. It should use the IDragHandler/IEventSystemHandler callbacks.
3) Zooming with a scrollwheel should center on the mouse position. (i.e., the zoom center should a selectable target)
4) Similarly, pinch to zoom should center on the midpoint between the two fingers.
5) Zoom should smoothly lerp between zoom levels as you zoom in/out. This should be internal to the script, with a flag if you want to disable it, but default should be lerp = on. 
6) Double tap on the map should zoom in a level and focus on where you clicked, similar to how it does in Mapbox JS.

I thought about implementing parts of this, but this is really core to the Mapbox product so you guys should do it (and it would take a lot less time for someone who deeply understands the API)
Thanks.
