### ISSUE TITLE
Mapbox build failing permanently on iOS

### ISSUE THREAD

**Issue by dblatner** [mapbox/mapbox-unity-sdk#589]
Mapbox Unity SDK is a incredible good solution but...

I have a compiler Error 'MapboxMobileEvents/MapboxMobileEvents.h' file not found (Symlink Unity libraries doesn't matter), when building a simple project in unity.

I think there is more than a incompatibility problem between FacebookSDK and MapboxSDK. They should both check for available libraries before using its own shipped ones in the SDK. And why even Mapbox needs to include plugins for Android/iOS instead of just using Unity's built-in cross-platform libs for both platforms?

Any help with this issue is very appreciated!

_Note: If this is a bug or support ticket, please provide the following information:_
* Unity version: 2017.3.1f1
* Mapbox SDK version: 1.3.0
* The platform you're building to: building on MacOSX 10.13.3 for target iOS
* A description of what you're trying to do: Building a small unity project using both Mapbox SDK and Facebook SDK, using PlayServiceResolver for resolving library conflicts on Android/iOS
* Steps to recreate the bug if appropriate:
  * Build the project with this SDKs on Unity
    * Symlink Unity libraries is true, it does not matter to turn it off, since the linker then reports the error
  * Mapbox is directly imported under "Assets" folder, i.e. the original place to be installed without modifications
  * FacebookSDK is also imported with no modifications
  * You can optional use the PlayServiceResolver for resolving the Android libraries, for iOS it should work without this asset

**Comment by dblatner** [comment]
I tried this, but it did not help...

**Comment by atripathi-mb** [comment]
@dblatner Could you post a screenshot of the settings you are using, please?

**Comment by dblatner** [comment]
Update: It seems, that the problem ist _NOT_ related to the Facebook Unity SDK, since I created a new project without it and without the PlayServiceResolver asset.

@atripathi-mb : I attached two screenshots, one for the problem description in Xcode, and one for the unity settings.

![mapboxerrorscreenshot](https://user-images.githubusercontent.com/3613737/37571130-d97f411c-2af8-11e8-9ad1-8956c00b64b4.jpg)

<img width="378" alt="unitysettingios" src="https://user-images.githubusercontent.com/3613737/37571080-3d186e20-2af8-11e8-9f90-01eaa6bd367f.png">

**Comment by BergWerkGIS** [comment]
@dblatner could you try if this helps: https://github.com/mapbox/mapbox-unity-sdk/issues/566#issuecomment-370490376

**Comment by campeezjesse** [comment]
Please Help. I have the same problem. I have deleted and reinstalled SDK. Added to header search path, tried to build every possible example etc.
 Everything works fine in editor but will not build to Xcode. I have updated to latest version of Mapbox, Unity, and Xcode. No change.

**Comment by atripathi-mb** [comment]
@campeezjesse Try with target version of 8.0 and above. Also, I have seen this issue go away if I compile the second time, and try things mentioned in #566

**Comment by campeezjesse** [comment]
I tried with 7.0 8.0 and 9.0
I downloaded the SDK 4 separate times
3 New Unity projects with only the Mapbox SDK in Assets and attempting to run a demo.

 In Xcode i have used a new bundle ID for each attempt.

Jesse Holt
Jesse@campeez.com<mailto:Jesse@campeez.com>
Www.campeez.com<http://Www.campeez.com>

On Apr 2, 2018, at 1:00 PM, Abhishek Tripathi <notifications@github.com<mailto:notifications@github.com>> wrote:


@campeezjesse<https://github.com/campeezjesse> Try with target version of 8.0 and above. Also, I have seen this issue go away if I compile the second time, and try things mentioned in #566<https://github.com/mapbox/mapbox-unity-sdk/issues/566>

**Comment by campeezjesse** [comment]
I have even gone as far as creating all 3 new accounts ( Mapbox Unity and Xcode )
 The SDK will not work. I have spent 3 days on this already.

Jesse Holt
Jesse@campeez.com<mailto:Jesse@campeez.com>
Www.campeez.com<http://Www.campeez.com>

On Apr 2, 2018, at 1:00 PM, Abhishek Tripathi <notifications@github.com<mailto:notifications@github.com>> wrote:


@campeezjesse<https://github.com/campeezjesse> Try with target version of 8.0 and above. Also, I have seen this issue go away if I compile the second time, and try things mentioned in #566<https://github.com/mapbox/mapbox-unity-sdk/issues/566>

**Comment by atripathi-mb** [comment]
@campeezjesse Apologies for all the trouble you had to go through. Could you give us some more details to reproduce this issue on our end. Screenshot of your Unity Player settings, device version, device type, xcode version and settings would be really helpful. 

As far as I know, this issue is not related to accounts on Mapbox or Unity. We have not been able to consistently reproduce the issue, seems like a Unity -> Xcode issue which throws an error on one of our modules. 

Again, appreciate your patience & apologies for the trouble.

**Comment by campeezjesse** [comment]
I completely understand. I wish i could build something with as few issues as all of you at Mapbox have built!

 What current settings would you like? I have changed so many now I do not even know where to begin.

 The current screen I’m using:
[image1.jpeg]
Not sure if you can see this or not. But it is just a new project in a new unity. Only change is to the target min as 8.0.

Jesse Holt
Jesse@campeez.com<mailto:Jesse@campeez.com>
Www.campeez.com<http://Www.campeez.com>

On Apr 2, 2018, at 2:22 PM, Abhishek Tripathi <notifications@github.com<mailto:notifications@github.com>> wrote:


@campeezjesse<https://github.com/campeezjesse> Apologies for all the trouble you had to go through. Could you give us some more details to reproduce this issue on our end. Screenshot of your Unity Player settings, device version, device type, xcode version and settings would be really helpful.

As far as I know, this issue is not related to accounts on Mapbox or Unity. We have not been able to consistently reproduce the issue, seems like a Unity -> Xcode issue which throws an error on one of our modules.

Again, appreciate your patience & apologies for the trouble.

**Comment by campeezjesse** [comment]
Just as a last attempt, i tried to install Xcode on a different Mac, with a new account. Then used a new Mapbox account. Same result. I throws the error

Jesse Holt
Jesse@campeez.com<mailto:Jesse@campeez.com>
Www.campeez.com<http://Www.campeez.com>

On Apr 2, 2018, at 2:22 PM, Abhishek Tripathi <notifications@github.com<mailto:notifications@github.com>> wrote:


@campeezjesse<https://github.com/campeezjesse> Apologies for all the trouble you had to go through. Could you give us some more details to reproduce this issue on our end. Screenshot of your Unity Player settings, device version, device type, xcode version and settings would be really helpful.

As far as I know, this issue is not related to accounts on Mapbox or Unity. We have not been able to consistently reproduce the issue, seems like a Unity -> Xcode issue which throws an error on one of our modules.

Again, appreciate your patience & apologies for the trouble.

**Comment by leonmak** [comment]
I have this problem, used `8.0` and `iPhone Only` in player settings, and 
`$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include` in `Header Search Paths` in `Build Settings` in Xcode

**Comment by karsnen** [comment]
## Had the same issue


Xcode Version - Version 9.3.1 (9E501)
Unity Version - 2017.4.3f1
Mapbox Version - 1.4.2, as of May 14th, 2018 

### Issue:
While trying to run the Xcode build on my phone, got the following message. 
'MapboxMobileEvents/MapboxMobileEvents.h' file not found

### Solution:
1. Set minimum target iOS version in Player Settings (within Unity) to 8.0
then 
2. Set proper paths `$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include` in `Header Search Paths` in `Build Settings` in Xcode. 

[
<img width="1195" alt="header file search path resolve" src="https://user-images.githubusercontent.com/32938838/40582159-7e042730-6121-11e8-9f5e-686ac7030161.png">
](url)

Cheers 👍

**Comment by karsnen** [comment]
Hope you guys fix it, so that we don't have to manually add this every time. Thanks.

**Comment by mdunkley** [comment]
fwiw just to follow up on karsnen's post - i seemed to be getting this issue thanks a space in my path.  When i changed my Mapbox sdk actual folder name from "Mapbox SDK" to MapboxSDK in the Unity assets directory, the error went away.  Xcode was interpreting "$(SRCROOT)/Libraries/MapBox SDK/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include" as 2 lines broken at the space between "Mapbox" and "SDK"

**Comment by Atuljust11** [comment]
solution is change import statement paths 
In xcode
Check you mapbox folder inside library it should have these files check attached screenshot
![image](https://user-images.githubusercontent.com/13001143/195106039-f8f5a647-8094-4ca9-a632-4bd13f53ecb6.png)
Open MapboxMetricsClient.m  change import to these #import <MapboxMobileEvents.h>

Open MapboxMobileEvents.h change imports to
#import <MMEConstants.h>
#import <MMEConstants.h>
#import <MMEEvent.h>
#import <MMETypes.h>
#import <MMEEventsManager.h>

**Comment by xavier-dc** [comment]
I was finally able to get my game to build on iOS by updating Mapbox via their website: https://www.mapbox.com/install/unity
And deleting any packages I wasn't using (some of the AR ones were causing build issues for me and my game doesn't utilize AR). I tried all of the other steps including building using cocoapods and pod init pod install etc. which had just led to more errors. Hopefully this helps.

**Comment by xementor** [comment]
> solution is change import statement paths In xcode Check you mapbox folder inside library it should have these files check attached screenshot ![image](https://user-images.githubusercontent.com/13001143/195106039-f8f5a647-8094-4ca9-a632-4bd13f53ecb6.png) Open MapboxMetricsClient.m change import to these #import <MapboxMobileEvents.h>
> 
> Open MapboxMobileEvents.h change imports to #import <MMEConstants.h> #import <MMEConstants.h> #import <MMEEvent.h> #import <MMETypes.h> #import <MMEEventsManager.h>

This help me to solve this problem. thank  you.

**Comment by tomCarnevale** [comment]
> solution is change import statement paths In xcode Check you mapbox folder inside library it should have these files check attached screenshot ![image](https://user-images.githubusercontent.com/13001143/195106039-f8f5a647-8094-4ca9-a632-4bd13f53ecb6.png) Open MapboxMetricsClient.m change import to these #import <MapboxMobileEvents.h>
> 
> Open MapboxMobileEvents.h change imports to #import <MMEConstants.h> #import <MMEConstants.h> #import <MMEEvent.h> #import <MMETypes.h> #import <MMEEventsManager.h>

This was the solution for me on Unity 6000.0
