### ISSUE TITLE
how to load Map at same location independent of player lcoation

### ISSUE THREAD

**Issue by Jersshhh** [mapbox/mapbox-unity-sdk#602]
Have to recreate this issue sorry

The problem I'm having is that the mapbox map is dynamically loaded in on the app start and places the player at the centre of the screen and generates the map around him.
I'm looking to create a location game set only in a small area and don't want the game(or map) to work if the player isn't near the games location.

I have created my own custom map which I'd like to use in conjunction with Mapbox to show the player location and to unlock different things based on the player location, but I'm having trouble making sure both maps are always aligned.

![capture](https://user-images.githubusercontent.com/9066356/37399836-ad141008-27ce-11e8-948b-914512531181.PNG)

I imagine this is achievable I'm just not seeing the solution!
Thanks for any help

**Comment by jordy-isaac** [comment]
@Jersshhh Have you tried checking out the LocationBasedGame example in version 1.4 of the SDK? I would start there. You can also edit the range displayed on the `AbstractMap.cs` in the `ExtentOptions` instead of the default camera bounds.

![screen shot 2018-04-03 at 10 42 34 am](https://user-images.githubusercontent.com/33474236/38265900-0a56ded2-372c-11e8-8444-d43f490fe2f4.png)
