### ISSUE TITLE
v1.4 buffer problem? 

### ISSUE THREAD

**Issue by dingfengboo** [mapbox/mapbox-unity-sdk#604]
when panning the map, some buildings disappear too early.

![1](https://user-images.githubusercontent.com/34928957/37756559-e71c4934-2de4-11e8-8afd-f1fc7fc26729.png)
![2](https://user-images.githubusercontent.com/34928957/37756560-e767986c-2de4-11e8-813d-0d27d6a9b5a6.png)
![3](https://user-images.githubusercontent.com/34928957/37756562-e81b0ad2-2de4-11e8-9e98-a9bfbf266c6e.png)

**Comment by atripathi-mb** [comment]
@greglemonmapbox @brnkhy Could you take a look at this issue please.

**Comment by brnkhy** [comment]
@dingfengboo 
It's a happening because of the overzooming. Buildings start to appear outside their parent tiles, then sometimes tile goes out of screen and gets disabled with its children still on screen. We just look at feaure clamping in overzooming situations.
You shouldn't get this at zoom levels smaller than or equal to 16.

**Comment by brnkhy** [comment]
cc @atripathi-mb

**Comment by greglemonmapbox** [comment]
@brnkhy Have we resolved this issue?
@jordy-isaac This was initially assigned to me, but I believe it falls into @brnkhy 's current knowledge scope more than mine
