### ISSUE TITLE
How to change Vector map style at runtime - V1.4

### ISSUE THREAD

**Issue by Vinita18** [mapbox/mapbox-unity-sdk#606]
<img width="545" alt="screen shot 2018-03-22 at 4 44 46 pm" src="https://user-images.githubusercontent.com/34370705/37767564-883a1f16-2df0-11e8-8270-23a96116fc1f.png">

I want to change the map id under Vector data to change my 3d map to 2d.
Basically I want to empty the map id there so I think it will render a 2d map if I reload. 
Also I have given the style name to "Custom". 

Or is there any other way to change my map to 3D to 2D at runtime??

**Comment by dingfengboo** [comment]
At Vector Factory.
Map id is responsible for defining the data source, not presentation.
If you want to change 3D to 2D, you must change the visualizers layer by layer.
(my understanding, hope not wrong)

**Comment by jordy-isaac** [comment]
@Vinita18 Can you let us know a bit more about what you're trying to build so that we can get you the best info? If you change the field to custom you'll need a Map ID from your Mapbox Studio account in the tilesets section.

If you're looking for a good starting point for a 2D map I would have a look at the `LocationBasedGame` in the examples folder.

**Comment by atripathi-mb** [comment]
@Vinita18 
> I want to change the map id under Vector data to change my 3d map to 2d.

I am assuming you want to turn off 3d buildings/roads to be turned off? If that is the case, you need to set `StyleName` to `None` .

**Comment by jordy-isaac** [comment]
@Vinita18 Please open this ticket again if you need some additional help.
