### ISSUE TITLE
What's your development setup?

### ISSUE THREAD

**Issue by Spaxe** [mapbox/mapbox-unity-sdk#61]
Hello,

I've been using the beta version since 0.4.0. Today I updated to 0.5.1, updated my code to match the new API, and I wanted to setup my codebase properly so I can (in practice) do a `git pull`, check out `develop` or a version number, and have Unity import that version. I'm familiar with the technology layer in isolation, but I'm new to working with Unity and a third-party module.

What's your development setup like? This is what I imagine on how to set up a development fork:

 * Fork mapbox/mapbox-unity-sdk and check out a local copy to `develop` branch
 * Check out a new branch, maybe called `feature-xxx`
 * Symlink or copy (?) `sdkproject/Assets` into a Unity Project
 * Open Unity and work from there

Another question is that I'm using MacOS primary to work, but the `UnityPackager.exe` is a Windows-only binary. Do I need to run that and import to Unity as I develop with it? Ideally, I'd like to be able to work with the source code directly, modify it, and submit pull requests.

**Comment by BergWerkGIS** [comment]
@Spaxe thanks for the reminder, we have to update the readme.

`UnityPackager.exe` is not needed locally, it runs on AppVeyor only.

You have to execute
```
./update-mapbox-unity-sdk-core.sh
```

This takes care of updating submodules and copying files into `sdkproject`.

**Comment by david-rhodes** [comment]
Hey @Spaxe, glad to see here! This is an excellent question and we need to clarify the process for contributors. That said, one challenge I hadn't considered until now is developers wanting to contribute while also working within the constraints of their own projects (rather than our "working" Unity project, `sdkproject`).

> Symlink or copy (?) sdkproject/Assets into a Unity Project

A symlink may be your best option if you want to develop within your own project. However, if you just want to fix bugs or add features, you can easily do so from the existing Unity project (`sdkproject`--the directory itself is the "project").

Does this answer some of your questions?

**Comment by Spaxe** [comment]
Great, thanks for your help @BergWerkGIS, @david-rhodes.

This is what I did:

 * Check out mapbox/mapbox-unity-sdk
 * In the repo, switch to a version. I'm developing with `tags/release-v05.10`.
 * Run `./update-mapbox-unity-sdk-core.sh`
 * Symlink `sdkproject/Assets/Mapbox` into my Unity project `Assets/Mapbox`

Could be useful to have in the `CONTRIBUTING.md`.

**Comment by Spaxe** [comment]
I'm sure someone is going to beat me to write the doco for forking and following all that, but for now I need to work with more 'stable' versions. :)
