### ISSUE TITLE
Poor performance with "Group Features" disabled

### ISSUE THREAD

**Issue by CedricVandelaer** [mapbox/mapbox-unity-sdk#657]
Hi, for my thesis I'm trying to create an application using Mapbox and the HTC Vive. I was first using Mapbox SDK version 1.2 but have now upgraded to 1.4. My Unity version is 2017.3.1.

After the upgrade I'm getting really bad performance when trying to render the building meshes using an AbstractMap and the Streets tileset. I've found the problem to only occur when I disable "Group Features" in the inspector. The zoom level I use is 16 and I use a simple TileRangeProvider of ( 2, 2, 2, 2).

Enabling group features is not an option however since I'm trying to create a pointer in VR to a building which then should show me a tooltip with the type of building. I'm currently achieving this through a custom GameObjectModifier that queries a Singleton with a Dictionary of <GameObject, BuildingType> . When I enable "Group Features", I don't get any feature data about the building types.

Am I approaching this the wrong way? Any help would be greatly appreciated.

**Comment by brnkhy** [comment]
@CedricVandelaer just a little background of that option; as you noticed when you uncheck that, it creates a gameobject for each feature (building in this case) and when you check it, it merged features into one mesh (up to 65k vertices).
You're loading 5x5=25 tiles and if it's a big and populated city, like New York for example, that means probably thousands of buildings and gameobjects in the scene. When you group them, it'll go down to something around 40-50.
Unfortunately we don't have a sound and complete solution for individual building selection in such populated scenes. We experimented bunch of stuff, like having grouped buildings but detecting building with mouse click position, but nothing released yet.
I don't know much about VR stuff myself but I believe VR headsets render everything twice for each eye so it's getting much much worse in your case.

I would suggest trying to load smaller area but using Quad Tree tile provider or Range around transform tile provider. Idea is to have a smaller region but load other areas dynamically as you move there. You can also try to use z15 with less tiles but feature count shouldn't change in total so that probably won't improve too much.

Advance solution, if you're a developer or cs student would be, having grouped features, then using a quad tree or something to find the building you clicked (find clicked point, find closest building etc). I think you can find something like that in this branch; 
https://github.com/mapbox/mapbox-unity-sdk/tree/lauriBuildingSelection
or this branch;
https://github.com/mapbox/mapbox-unity-sdk/tree/painting
Again they probably won't work out of box but idea is there. (especially the first one)

**Comment by brnkhy** [comment]
@CedricVandelaer I believe you can filter them using Optimized Style for vector factory. Which means creating a style in mapbox studio with only the layers you want and using that style in the SDK. 
We generally use that to filter out whole layers so I'm not sure if that'll work for just a certain type of buildings for example.
Also you can just filter during visualization and not render them at all. Data is cached anyway so this will probably be just as good as first option. You can find filtering options under "Layer Visualizer -> Advanced -> Filters" in Absract Map inspector.
