### ISSUE TITLE
Mapbox Disk caching / offline mode

### ISSUE THREAD

**Issue by Digas17** [mapbox/mapbox-unity-sdk#702]
I would like to ask if somebody could help me by explaining me how to implement disk caching on Unity SDK so that my app can work offline. Is it possible that my app works with Mapbox 100% offline?

Thanks for your time

**Comment by atripathi-mb** [comment]
@Digas17 Unity Sdk comes with ambient disk caching built in. What that means is the first time the users loads map for a specific area, tiles are cached on device. Next time the tiles will be loaded from the cache.

The cache has to be built on the device and you cannot ship with pre built cache in your app.

If you can tell us your specific use case we can discuss in detail

**Comment by Digas17** [comment]
I am doing a cultural guide about my country and i would like my app to work with Mapbox 100% without internet connection. is this possible?

**Comment by jordy-isaac** [comment]
Hi @Digas17 It is possible. However, as mentioned above you users would be required to download the tiles initially as the tiles can't be shipped with your app. I hope this helps!

**Comment by Digas17** [comment]
Sorry for the persistence, but how is that download done? Does the user have to use the map online for the first time,and each time he goes through a tile,it saves it locally? Or in the beggining of the app, the user can download it from some online source?
Thanks in advance!

**Comment by jordy-isaac** [comment]
Hi @Digas17 It would have to be initially one time the first time they launch the app or need the tiles.

**Comment by mukhitabdinazarov** [comment]
Hi,I have a route and I want to load the map in a small radius from the route so that the data is not large. I used open source MapBox but there loads the whole visible area into the cache. If I have a route from Paris to Moscow, downloading the entire map will take a lot of memory. Is it possible to download only the route and with small radius. Sorry my English

**Comment by BergWerkGIS** [comment]
@mukhitabdinazarov the SDK does not provide such functionality out of the box, you would have to write code to do that by yourself.

Also be aware that according to our terms of service you are not allowed to bundle and redistribute pre-downloaded tiles with an app.

**Comment by nilsk123** [comment]
Okay, I have the same question as this user and it doesn't appear to be answered yet.

Upon starting the app, I want to download maptiles for a certain boundingbox and zoomlevels, so that after that the app can operate offline and loadingtimes will be decreased.

There is documentation on how to do this for iOS and Android:

https://www.mapbox.com/ios-sdk/maps/examples/offline-pack/
https://www.mapbox.com/android-docs/maps/overview/offline/

But I can't find it in the Unit docs, and also can't seem to find an example of it. I'm not asking about ambient caching or distributing predownloaded tiles with an app. I want to download all tiles of a region in a splaschreen like setting.

**Comment by dorukeker** [comment]
I asked in a new issue the same.
Here is the number #1312
