### ISSUE TITLE
AR world scale object at coordinate orientation problem

### ISSUE THREAD

**Issue by xeppex** [mapbox/mapbox-unity-sdk#710]
[SUPPORT]

* Unity version: 2017.3.1.f1
* Mapbox SDK version: 1.4.1
* The platform you're building to: iOS

Hi,

I'm making a world scale AR application. And I have a problem with the orientation of my placed objects in the world.
I can place objects using my own code based on SpawnOnMap. When I watch the map view
in the editor I can see the objects are placed on the correct position on the map. 
But everytime I open the AR view on the device the orientation is always way off.
It seems like when I hold my device to the north and spawn them it seems to be ok.
But when I change my phone direction and spawn them the orientation is always different.
Someone has an idea what I might be doing wrong?

Friendly regards

**Comment by jordy-isaac** [comment]
@xeppex Thanks for reaching out. Which of the example scenes are you using? We have two ways of aligning: Manual and Automatic. I would suggest that you try both to see which works best. With the manual alignment you might achieve better results. For example, if you are in an urban area where there can be poor GPS, the manual synchronization might be better. 

Localization is also something that we are focusing on and improving. Expect it to be better moving forward.

**Comment by xeppex** [comment]
Hi @jordy-isaac,

I really need Automatic and I use WorldAlignmentMap prefab. The app will always be used in the open with good gps accuracy.
There is just one thing that I can't really understand. If you open an app like google maps or apple maps, the direction always seems to be correct +-. Why isn't it with AR?
I actually need to make an app to view different objects on coordinates. I don't really need the maps data. Maybe Mapbox is just overkill for my needs?

**Comment by jordy-isaac** [comment]
Orientation and localization are the big challenges with AR now. Our team is working improve AR localization as you mention. #559 is related and one of the ways we are looking to make improvements. The benefit if Mapbox is that we can provide you with location data, but if you don't need localization you might be able to get by just using the ARkit/Core plugins for Unity.

**Comment by devrajn-hexaware** [comment]
Hello @xeppex  Any updates on the issue?? I have the same issue. Did you manage to fix this?? Or is it still open for you??

**Comment by kakashysen** [comment]
Hi @jordy-isaac I have the same problem that @sepperousseau, do you have updates about this issue?

**Comment by DanieleSuppo73** [comment]
I suggest you to write your piece of code to get the right orientation directly from the Compass. It seem that at Mapbox they don't understand the question

**Comment by kakashysen** [comment]
Yes thanks @DanieleSuppo73 
Yes, I found a solution, I leave it here in case it could useful for someone
Add the following script to `MapHolder` and set the rotation Y to 180 as default
```
void Update ()
{
        if (!isAlignedMap)
        {
            float mapRotationY = transform.rotation.y + -Input.compass.trueHeading;
            transform.rotation = Quaternion.Euler(0f, mapRotationY , 0f);
            isAlignedMap = true;
        }
  }
```

**Comment by ommmid** [comment]
@sepperousseau same problem here. Did you find a good solution for it?

**Comment by Snppls** [comment]
Hi @ommmid,

I worked with @sepperousseau on this issue. We ended up customising the WorldAlignmentKit sample quite a bit for our use case, which is why we didn't issue a pull request for this. This won’t be a copy-paste type solution, but here’s the [gist](https://gist.github.com/novemberfiveco-gists/25e1092aaf56ef498067f86c68a599d2) of it.

Whatever you do, never mess with the transforms of the AR Root or the AR camera directly (the camera that is linked in the AR Controller component, the Main Camera in the WorldAlignmentKit sample).  Instead you should play with the rotation and scale properties in the AR Controller component, attached to the AR Root. This was stated in the Unite 2017 talk about the ARKit sample. You also can’t change the rotation every time the compass orientation changes because then you’ll mess up the internal rotation used by ARKit/ARCore.
For this reason we also did not use the Rotate with Location Provider component. 

We ended up creating our own compass alignment component and added that to the AR Root GameObject. When the script is first loaded, we perform an initial (one time) alignment between the AR Controller rotation and the compass. 
From then on we let ARKit/ARCore do its thing, which is typically more accurate than the compass anyway. However there are a few moments when we need to do a realignment, by rotating the ARController by the difference between the camera rotation and the current compass orientation.
Each update we check whether or not a realign is necessary, which can be the the case if:
* the scene was paused because the app went to the background
* the new compass reading is more accurate than the previous one
* the difference between the current rotation according to ARKit/ARCore and the compass orientation is too high, meaning something has gone out of sync (you can play with these values)

You can find the script for this component [here](https://gist.github.com/novemberfiveco-gists/25e1092aaf56ef498067f86c68a599d2). You'll still have to disable or remove the rotation from Mapbox's alignment script if you want to use this.

**Comment by ommmid** [comment]
Hi @Snppls , thanks so much for sharing your solution. I am trying to use your script there was an error where it could not find DeviceOrientationAccuracy in currentlocation for compassaccuracy section. I changed "this.locationProvider.CurrentLocation.DeviceOrientationAccuracy" to this "this.locationProvider.CurrentLocation.Accuracy". Is that OK. One more question: what script exactly do you mean by"Mapbox's alignment script"?

**Comment by Snppls** [comment]
@ommmid As far as I can tell, DeviceOrientationAccuracy should be a property in Location.cs. Maybe you have a different version of the Mapbox SDK, I used 1.4.2. Anyway, if you can't access the compass accuracy, I guess you can simply remove it from the if statement in the script.
By the Mapbox alignment script, I mean those AbstractAlignmentStrategy subclasses, such as AverageHeadingAlignmentStrategy, which internally perform a rotation as well.

**Comment by dhruvmodhapp** [comment]
@DanieleSuppo73 : have you got any solution?

**Comment by dhruvmodhapp** [comment]
@DavidDeBels : Your alignment script perfectly works with the iOS device. But I have an issue in Samsung Galaxy S8, because it's compass is on device upper side.... When I want to hit object by taking S8 device upside, it's compass value has been changed. how to solve this problem for samsung galaxy s8?

**Comment by ibrews** [comment]
I also couldn't get @DavidDeBels script to work. I'm guessing there are additional scripts that need to be turned off besides the ones he mentioned.

**Comment by bugracoskun** [comment]
Hello, I have the same issue. Is there any solution for this problem?
