### ISSUE TITLE
 get_streamingAssetsPath is not allowed to be called

### ISSUE THREAD

**Issue by einstyle** [mapbox/mapbox-unity-sdk#72]
**MeshGenerationPois:**

get_streamingAssetsPath is not allowed to be called from a ScriptableObject constructor (or instance field initializer), call it in OnEnable instead. Called from ScriptableObject 'MapboxConfigurationWindow'.

UnityException: get_streamingAssetsPath is not allowed to be called from a ScriptableObject constructor (or instance field initializer), call it in OnEnable instead. Called from ScriptableObject 'MapboxConfigurationWindow'.

How to solve?

**Comment by david-rhodes** [comment]
@einstyle Can you provide reproduction steps, please? We've seen this on rare occasions, and I suspect the culprit is having the configuration window open when code is recompiling. Please close the configuration window, wait for all compiling to finish, then try this process again: https://www.mapbox.com/mapbox-unity-sdk/docs/01-mapbox-api-token.html.

If you still experience issues, restart Unity and try again. Thanks!

**Comment by einstyle** [comment]
1. import MapBox package in unity
2. add key to configuration
3. open scene 
4. run
After play run it stops with the errors above

**Comment by david-rhodes** [comment]
@einstyle you literally just need to close the window once it says the token is valid. In any case, the token is saving correctly and your maps should load properly.

I'll look into a proper fix, though.

**Comment by david-rhodes** [comment]
Fixed.
