### ISSUE TITLE
Water Vector Layer with 3DPoiMarker?

### ISSUE THREAD

**Issue by emorling** [mapbox/mapbox-unity-sdk#720]
Water vector layers seem to come with a 3DPoiMarker (big blue circle) although I never indicated that I wanted anything else besides water? Are you aware of this issue?

**Comment by brnkhy** [comment]
@emorling 
we're aware of this issue. Label layers (water label in your case) in Explorer scene have wrong game object modifiers at the moment. We're tacking this issue here; https://github.com/mapbox/mapbox-unity-sdk/issues/711 and it'll be fixed soon.
Thanks for the ticket! I'm closing this as we're tracking it in other ticket already.
