### ISSUE TITLE
[Bug] IndexOutOfRangeException when zooming in/out on terrain with elevation 

### ISSUE THREAD

**Issue by atripathi-mb** [mapbox/mapbox-unity-sdk#785]
With v1.4.2, when zooming in/out on the `Zoomable Map` example, there are continuous errors with the following call stack 

IndexOutOfRangeException: Array index is out of range.
Mapbox.Unity.MeshGeneration.Data.UnityTile.SetHeightData (System.Byte[] data, Single heightMultiplier, Boolean useRelative) (at Assets/Mapbox/Unity/MeshGeneration/Data/UnityTile.cs:185)
Mapbox.Unity.MeshGeneration.Factories.TerrainFactoryBase.OnTerrainRecieved (Mapbox.Unity.MeshGeneration.Data.UnityTile tile, Mapbox.Map.RawPngRasterTile pngRasterTile) (at Assets/Mapbox/Unity/MeshGeneration/Factories/TerrainFactoryBase.cs:74)
TerrainDataFetcher+<FetchTerrain>c__AnonStorey0.<>m__0 () (at Assets/Mapbox/Unity/MeshGeneration/Factories/TerrainDataFetcher.cs:35)
Mapbox.Map.Tile.HandleTileResponse (Mapbox.Platform.Response response) (at Assets/Mapbox/Core/mapbox-sdk-cs/Map/Tile.cs:244)
Mapbox.Platform.Cache.CachingWebFileSource+<requestTileAndCache>c__AnonStorey1.<>m__0 (Mapbox.Platform.Response r) (at Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Cache/CachingWebFileSource.cs:274)
Mapbox.Unity.Utilities.HTTPRequest+<DoRequest>c__Iterator0.MoveNext () (at Assets/Mapbox/Unity/Utilities/HTTPRequest.cs:96)
Mapbox.Unity.Utilities.Runnable+Routine.MoveNext () (at Assets/Mapbox/Unity/Utilities/Runnable.cs:130)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by brnkhy** [comment]
@atripathi-mb found the error. Turns out terrain data fetcher was calling "process" on failed web calls as well. Fixed that, changed same section in all data fetchers to be more readable. 
pushed it here; https://github.com/mapbox/mapbox-unity-sdk/tree/dataFetcherErrorFix

I'm not sure if that's normal to have so many failure though. I think we're getting 404 on cancelled tiles but still might worth checking that separately.
