### ISSUE TITLE
Moving camera / stationary world design for zoom and pan

### ISSUE THREAD

**Issue by MrMallIronmaker** [mapbox/mapbox-unity-sdk#792]
I'm having a hard time digging through the information available here, so I feel the best way to ask is a Github issue.

I'm developing a location-based game, and I'm looking to add zooming and panning features to the LocationBasedGame example. I'm choosing a design of a stationary world with a camera moving over that world at different positions and heights. Panning is the XZ direction, and zoom would be controlled by the Y dimention. The dynamic loading for content within the camera's view is great, and I want to make use of that. However, this design is different from both the original LocationBasedGame and ZoomableMap examples.

I was hoping that I could map between the Y height and the value for 'zoom'. I first tried just dragging the slider for the 'zoom' factor [this is under AbstractMap > General > Zoom] to see what would happen. I hoped it provide the right zoom level and spacing and everything, but that's not the case it seems. [I can describe more and provide screenshots if necessary, but I don't think it's a bug, just something it's not designed to do.]

**Is a moving camera and a stationary world map a reasonable design, one that with a little bit of coding on my end, Mapbox can support?** Or is it nigh-impossible to break the design of stationary-camera-and-moving-map? Can someone point me in the right direction for solving this problem?

**Comment by jordy-isaac** [comment]
Hi @MrMallIronmaker. Thanks for the ticket. The Maps SDK for Unity would be great for an app like this. I actually made a [demo game](https://twitter.com/Jordy_Webb/status/981913239746297856) using the same concept with a stationary map and a scrolling camera. You can do so by placing a script on the camera that moves it. Something like the code below will give you what is shown in the gif. 

```
public float cameraSpeed = 10f;

    void Update()
    {
        transform.Translate(Vector3.up * Time.deltaTime * cameraSpeed);

    }
}
```

![camera-scroll](https://user-images.githubusercontent.com/33474236/40326815-7a7827b8-5cf5-11e8-800d-ee9c6766207c.gif)

As for zooming, one other thing to check out would be the [zoomable map](https://www.mapbox.com/unity-sdk/overview/zoomable-map/) example in the SDK. Zooming might be a little trickier since you'll have to consider scale. The zoomable map example takes care of the tile scaling and map scaling for you so you can easily look at a map at different zoom levels. It also decouples the camera from the map for zooming. You could adjust the axis of the camera or game object to have the effect of elevation change, but it won't change the zoom level of the map. However, the shadow effect is something that you can get out of the box for showing elevation in relation to the terrain. Hope this helps!

![elevation](https://user-images.githubusercontent.com/33474236/40327777-fb8220b8-5cf8-11e8-8ccd-c20b9428ee79.gif)

**Comment by jordy-isaac** [comment]
Closing this one for now. Please reopen if you need some more help.

**Comment by MrMallIronmaker** [comment]
Got it - I wrote some simple methods that reset the scale to 1,1,1 after updating the zoom with `updateMap()`. Turns out that's all I needed. Thanks for the tips!
