### ISSUE TITLE
Road meshes look bad at junctions

### ISSUE THREAD

**Issue by heath3n** [mapbox/mapbox-unity-sdk#801]
Unity version: 2018.1.0f2
Mapbox SDK version: v1.4.2

This is near the Blue Hills Bank Pavilion in Boston, MA. The left image is in Unity and the right is in Mapbox Studio. This awful tapering happens regardless of the line width. I understand the difficulty of getting neighbouring line segments to match up nicely but is there any work being done on making roads look better (or anything I can change to fix this)?

![bad_roads](https://user-images.githubusercontent.com/8888204/40339874-637cdfb8-5d4a-11e8-8d1f-0bcc1aa905a1.png)

**Comment by jordy-isaac** [comment]
Hi @heath3n, thanks for the ticket. Can you send in a screenshot of your AbstractMap settings including the lat/lon? It might work to try and apply filters, making each road type a layer.

**Comment by heath3n** [comment]
Lat/long: `42.347646, -71.036203`

![road](https://user-images.githubusercontent.com/8888204/40579269-9ea85fcc-60f1-11e8-9f38-01cbe2d77224.PNG)

I checked on Studio and both the pointy roads and the one they merge into are part of the same `road-secondary-tertiary` layer so I'm not sure filters would help.

**Comment by brnkhy** [comment]
@heath3n Sorry I only now had chance to look into this. Unfortunately this looks like an unexpected (bad?) data case. Interestingly, those two short road segments creating a big V are defined as one road segment. Road segments like V are hard because of that sharp turn and current line mesh modifier cannot handle that properly. In most cases, such intersections (V) are defined as two short road segments so we aren't getting this more.
LineMeshModifier is one of the oldest scripts though and can definitely use a rework. I'm afraid I can't thing of a quick/short solution though.

**Comment by brnkhy** [comment]
@heath3n I have some time today to give this a shot; first results looks pretty good I think;
![unity_2018-08-31_04-54-55](https://user-images.githubusercontent.com/1465390/44888478-1762d080-acda-11e8-82d2-d6cb8bcfd64c.png)
there's still some work to do but after that I'll put the new line mesh script here (or somewhere).

**Comment by brnkhy** [comment]
@heath3n You can find and test the fix on this PR; https://github.com/mapbox/mapbox-unity-sdk/pull/992
It's pretty much a single file change so you can simply copy&paste that into your existing project as well. I just PR'ed it so haven't tested thoroughly though.
