### ISSUE TITLE
Verify fallback is working when disabling native Android location plugin

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/mapbox-unity-sdk#834]
* Unity version: all
* Mapbox SDK version: +1.4
* The platform you're building to: Android
* A description of what you're trying to do:

refs #831 

The native Android location plugin has min API level requirement of `24` aka `Nougat` aka `Android 7` which is the same as ARCore.

To build to lower API levels the plugin can be disabled either via
1. unchecking `Android` in the inspector properties of the `aar`
2. deleting its folder `Assets/Mapbox/Unity/Location/Plugins/Android/`

**TODO:**
- [ ] @BergWerkGIS Verify everything works as expected (fallback to default Unity location provider) in case the native plugin has been disabled via one of the methods outlined above.
- [ ] @jordy-isaac update docs

**Comment by nilsk123** [comment]
@BergWerkGIS @jordy-isaac If I override the min sdk version in the manifest and deploy to android 4.4, will it default to unitys built in location provider because it finds an incompatible library (android native provider)? I want to build an APK which uses the native plugin when possible, but otherwise defaults to unitys plugins.
