### ISSUE TITLE
Should we use the development version or the release?

### ISSUE THREAD

**Issue by mihakrajnc** [mapbox/mapbox-unity-sdk#85]
So, I're preparing a demo project which is centered heavily around Mapbox for which I'm currently using the 0.5.1 release.

Looking at the repository, a lot has changed since then, and i'm not sure if I should be using the release or the development version... As mine is a demo project (which might go into production some day) 100% stability isn't required yet, so I'm inclined to use the development version of Mapbox.

My reasoning is that I'll have less work porting the current version of our project to the new API then a seasoned project later on.

So my question is (and I know we all hate these questions), when is the next release estimated to be published? Are we looking at days, weeks, or months?

And a followup, should I use the development branch here, or the 0.5.1 release (and wait for an official release), to minimize my overall effort of porting the project?

Thanks!

**Comment by david-rhodes** [comment]
@mihakrajnc My recommendation for this stage of your project is to stay as current as possible with `develop`. We're making very fast iterations at this stage, some of which are huge performance or feature gains. I think the cost of making these large improvements yourself is greater than fixing SDK calls on your end because of a breaking change. However, that depends on what your project's needs are, as well.

That said, a new release should be imminent.

**Comment by mihakrajnc** [comment]
@david-rhodes Lightning fast response 🥇 
I'll take your advice and go with the latest `develop`, thanks for the recommendation!

**Comment by david-rhodes** [comment]
@mihakrajnc No problem! As a note, we try to keep develop as stable as possible.
