### ISSUE TITLE
Increase building rendering range

### ISSUE THREAD

**Issue by tetreum** [mapbox/mapbox-unity-sdk#870]
* Unity version:  2017.4.f01
* Mapbox SDK version: 1.4.3
* The platform you're building to: Web

Building rendering range looks to be really short, as buildings disappear while they are still on camera:
![https://i.imgur.com/JvHbN4w.png](https://i.imgur.com/JvHbN4w.png)
![https://i.imgur.com/tfcWDZU.png](https://i.imgur.com/tfcWDZU.png)

Notice the left bottom building how some parts have disappeared.

How can i increase the rendered map size so this doesnt happen?

**Comment by jordy-isaac** [comment]
Have you tried changing the `Extent Options` on the `AbstractMap` script?

**Comment by tetreum** [comment]
Yes, switching from camera bound to transform has a result like... better have a view:
![https://i.imgur.com/575gPNO.png](https://i.imgur.com/575gPNO.png)

**Comment by jordy-isaac** [comment]
Can you let us know a bit more about your use case and what you're trying to achieve in the end.

**Comment by tetreum** [comment]
Oh yes!
Like this, but with building collisions and "GPS path":
https://framesynthesis.com/drivingsimulator/maps/

**Comment by brnkhy** [comment]
@tetreum I think it might be a known issue regarding the zoom level & camera bound tile provider. 
Can you try decreasing zoom level down to 16 and try it again (with everything else same)? 
I'm afraid I won't have any quick fix suggestions on top of my head if that fixes it.

Wait, actually I might have one; the only difference between z16 and z18 is the imagery and I guess you went z18 because you want higher quality textures. One thing you can do is to clone the abstract map script (and have two of them in one scene). then change them such that;
- first one will load terrain and imagery at z18 with unity tile size settings at `x`   (`x` is anything you choose really, can be default values 100)
- second will only load vector data in z16 with unity tile size setting at `4x`   (so like 100&400)

this should craete two aligned maps. you might have some side effects but I think it should work.

**Comment by tetreum** [comment]
It's strange, the first meters was going pretty well, every building was fully rendered, but then:
![https://i.imgur.com/szTMI8D.png](https://i.imgur.com/szTMI8D.png)

I will keep going, maybe this zone is as it looks

**Comment by brnkhy** [comment]
@tetreum I checked the location and look like that part of the city is missing data in general. But I think there's also an issue with the new building tileset so your first shot even missing a few buildings that should be there. This is what I get when I switched to streets tileset;
![unity_2018-06-26_14-44-49](https://user-images.githubusercontent.com/1465390/41909356-7f054830-794f-11e8-8921-9e1b1a049f86.jpg)
You can change data source from; Abstract Map -> Map Layers -> Data Source

second shot is probably another bug regarding that tileset and again should be fixed with streets tileset. If you're not planning to use building replacement feature or do building selection/highlighting in your app, streets tileset will be enough anyway.
Meanwhile we'll look into the issues with other tileset. thanks for the detailed report and shots! 🙏

**Comment by tetreum** [comment]
I need the buildings to have 3d collisions :)
And no problem! Your product has the most updated info. I've tested others like WRLD and they lack most parts of the world + their existing data is outdated.

I also tried to point to an OpenMapTiles server for data source, but looks like sdk is not ready to point to non `mapbox://` urls

**Comment by atripathi-mb** [comment]
@tetreum Could you also share with us a screenshot of all the settings you have for the building visualizer layer?

**Comment by tetreum** [comment]
There it goes:
![https://i.imgur.com/esK8YN4.png](https://i.imgur.com/esK8YN4.png)

**Comment by jordy-isaac** [comment]
@tetreum Please try again without unique ID checked. Also, if you're data is missing you can add it to OSM.

Mapbox maps rely on data from OpenStreetMap, a global volunteer project that everyone can contribute to. If you are familiar with this area, I encourage you to go to openstreetmap.org, create an account, and make improvements directly. You'll have the option to go through an interactive tutorial to get you started. The Mapbox Streets tileset is updated regularly as features are edited or added to the map, which means that if you edit OpenStreetMap, you will eventually see your changes reflected on your Mapbox map.
