### ISSUE TITLE
AR Examples don't work in Android 7 on a Galaxy S7

### ISSUE THREAD

**Issue by ibesora** [mapbox/mapbox-unity-sdk#876]
Hi, 
I'm using your amazing SDK to implement something in AR but I can't get it to work. After thinking it might be something with my code, I tried to load all your AR examples and none of them work, just get a black screen after the Unity logo. All the other examples work great.

Some data about my rig:
Unity version: 2018.1.5f1
Mapbox SDK version: 1.4.3
Building to Android 7.0 (API level 24) on a Samsung Galaxy S7

The Mapbox Augmented Reality SDK for React Native works great on the same device and computer

Any idea what might be wrong? Can't see anything wrong in the logs

**Comment by BergWerkGIS** [comment]
>  just get a black screen after the Unity logo.

Hm, that's weird. Don't think I've seen that before.

Cannot offer a solution but maybe check these:

* your app's permissions on the device in case you accidentally denied the camera permission
* in Unity if `ARCore Supported` is checked (`Player Settings -> XR Settings`)
* maybe reinstall ARCore although I suppose you have it already because you tried the React SDK.
  * either from the PlayStore
  * or here https://github.com/google-ar/arcore-android-sdk/releases

**Comment by ibesora** [comment]
ARCore Supported was not checked. Sorry about that. 
You should add that to the Getting Started instructions on the Mapbox Unity SDK so people like me, who had never used ARCore before know that.
Is that documentation on github? I can do a PR request adding that.
Thanks for your help!

**Comment by Alvarden15** [comment]
I can understand that. I had that problem too. When builiding and testing the example, it didn't work. Turns out you have to check ARCore Supported in the player settings and that fixed it.
Clearly the sdk's documentation needs some work.
