### ISSUE TITLE
Direction will ignore footprint

### ISSUE THREAD

**Issue by willychang21** [mapbox/mapbox-unity-sdk#885]
Mapbox SDK version: latest version
I'm trying to do a walking nevigation app ,but It seems that `directionfactory`only support the road for car.
`direction waypoint  entity` will ignore the footprint and choose the longer path to reach the destination
![image](https://user-images.githubusercontent.com/38349902/41949645-e8b4f7c6-79f4-11e8-9bc0-75ded5357fb0.png)

**Comment by atripathi-mb** [comment]
@willychang21 Since this is an example, directions factory is setup to show driving directions. 
you can change it to `walking` or `cycling` by choosing the routing profile here https://github.com/mapbox/mapbox-unity-sdk/blob/a49e19dc5e24c90989fe14e8262cb23d9c309450/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Factories/DirectionsFactory.cs#L82

**Comment by willychang21** [comment]
Thx,Iwill try it

**Comment by willychang21** [comment]
Thank you!! I will try it.
