### ISSUE TITLE
Support: Trouble with Abstract map. 

### ISSUE THREAD

**Issue by jarrettblumRT** [mapbox/mapbox-unity-sdk#898]
2018.1.3f1:
Scripting Runtime Version: 4.x
Scripting Backend: Visual Studio
Api Compatibility Level: .NET 4.x
Mapbox SDK version: v1.4.3
The platform you're building to: Android

So, I am trying to spawn a prefab and have it follow a nav mesh at a specific location only. 

Currently It will spawn the prefab and that will follow the navmesh, but this seems to happen where ever the player is even if I specify the map location in the abstract map and the location provider. 

Just looking for some advice on only having the experience work if the player is in a specific location. 

Thanks.

**Comment by jordy-isaac** [comment]
@jarrettblumRT Runtime navmesh with the SDK is a bit tricky from my understanding. @brnkhy might have some good ideas of how you can implement this.

**Comment by brnkhy** [comment]
@jarrettblumRT I'm afraid I don't understand the issue.
You generate the map and player prefab. But nav mesh isn't on top of the city but under the player? Isn't the player in the city environment? You should be able to change nav mesh boundaries in nav mesh settings so that shouldn't be a problem I guess? Sorry but I need more info on that.
