### ISSUE TITLE
Factories Menu problem

### ISSUE THREAD

**Issue by bonvalletRomain** [mapbox/mapbox-unity-sdk#909]
Hello,
I want to create a vector tile factory but in Factories menu i have just "Image Factory" item.
![capture d ecran 2018-07-11 a 18 21 54](https://user-images.githubusercontent.com/1614643/42586004-51334832-8537-11e8-91c6-708c3d49a86d.png)
 

_______
Unity version: 2018.1.6f1 Personal
Mapbox SDK version: v 1.4.3
on Mac 10.13.6

**Comment by thomue00** [comment]
Same for me :/ 

Unity: 2017.4.5f1
SDK: v1.4.3
Windows 10

**Comment by jordy-isaac** [comment]
@bonvalletRomain, @thomue00  Were you following the tutorial here: https://www.mapbox.com/help/unity-mesh-pt-2/ or were you needing to create a vector tile factory for another reason.

If you're following the tutorial, I would suggest using this one: https://www.mapbox.com/help/create-a-map-in-unity/ as we've made it a lot easier to visualize vector layers.

We've made changes since the first tutorial but have left it up for users to see how the SDK and factory system is set up.
