### ISSUE TITLE
Loading visualisers in sequence or having one visualiser dependent on another.

### ISSUE THREAD

**Issue by Gzbx** [mapbox/mapbox-unity-sdk#910]
**Unity version:**
2017.3.1f1

**Mapbox SDK version:**
1.4.3

**The platform you're building to:**
PC

**A description of what you're trying to do:**
At a high level, I am trying to add prefabs on the roadside, like street lights and other objects.
I am using the road line data with an offset to determine the position I need and I can successfully place the objects. I also have some logic which checks to see that the object will not be placed on a road layer - this avoids street lights appearing inside intersections where the road line data segments intersect.

I suspect that the issue I am experiencing has to do with the fact that the Vector Layer Visualizers are not loaded sequentially, hence the colliders I am creating to represent the roads are not all present when my game object modifier runs to perform the "is not on road test" test.

In the debug example below, the blue raycasts pass a test that there is no road layer under them and as such a prefab can be placed. The black raycasts fail and no prefab is placed. however you can see I have highlighted with a red square some lights appearing in the intersection.

I suspect that the road running horizontally was loaded first and the road running vertically was loaded second. I am wandering if there is a way to force one visualizer to complete before another runs.

I am also happy for other suggestions of how to achieve the result I need.

![image](https://user-images.githubusercontent.com/35828779/42612728-42d41038-85e0-11e8-9d72-2dadeecb9828.png)

Here are the 2 vector layer visualisers
the first creates the road line mesh and colliders and adds them to the road layer
![image](https://user-images.githubusercontent.com/35828779/42612324-12d8bed0-85de-11e8-9cf4-8fe5e198ad5d.png)

here is the second visualiser that places the prefabs
![image](https://user-images.githubusercontent.com/35828779/42612780-9535f5a8-85e0-11e8-8a20-65a2eff09a61.png)

My custom game object modifier is defined as:
public class GameObjectModifierAddRoadsidePrefabs : GameObjectModifier

And implements

public override void Run(VectorEntity ve, UnityTile tile)

**Comment by Gzbx** [comment]
If I may also ask a follow up question, my Game Object Modifier above adds a roadside prefab as a child of the tile/visualiser. I am using the range around transform option of the abstract map and I have noticed that after the tiles get recycled when panning the scene, my roadside prefabs for the recycled tiles do not get set to inactive or/and do not get destroyed - hence they appear incorrectly on the new tile. 
Here is a view of the hierarchy:
![image](https://user-images.githubusercontent.com/35828779/42815899-300cb4e8-8a0c-11e8-899d-311949d5b517.png)

How do I signal to the recycler to clean these up? Is there a way to deactivate or destroy them when the tile is recycled?

Your help is appreciated.

**Comment by brnkhy** [comment]
@Gzbx I think you're running into this because of the coroutines in the layer visualizers. It only process a fixed amount of features every frame, not to block the whole system, but I think there's nothing stopping system to start next layer visualizer while previous is still running. 
Of course this is not a bad thing, technically you can remove coroutines inside the visualizers easily but that wouldn't be a good solution.

I think a better solution would be;
- creating your own scriptable object for stashing roads
- create a new game object modifier to add road features to this stash and add it at the end of the road layer visualizer modifier list
- create a monobehaviour in scene, give it abstract map and that stach scriptable object
- this monobehaviour will listen map events and when map state changes to finished, it'll go through all roads in the SO and create your prefabs.

This should work, although it might be a little tricky with moving maps (map states might not be very stable at current version, we're working on that).

For the second question, if I remember corrent, you can override `OnPoolItem` method in the game object modifier to remove the game object.

Hope that helps!

**Comment by Gzbx** [comment]
thanks @brnkhy , I will give your suggestions a try.

**Comment by Gzbx** [comment]
For those who read this later, the SpawnInsideModifier.cs class has an example of how to pool items as per @brnkhy 's suggestion.
