### ISSUE TITLE
[Support/Bug]The results from different distance measuring methods comes out with very inconsistent results, please come take a look?

### ISSUE THREAD

**Issue by zxcvb7653** [mapbox/mapbox-unity-sdk#929]
I have been using the` CheapRuler.cs` and `Vector2d.Distance` to experiment with measuring distance in MapBox.

<img width="1119" alt="screen shot 2018-07-26 at 11 09 13 am" src="https://user-images.githubusercontent.com/39035665/43256365-62d9820c-90c4-11e8-95f0-dcace6ab004c.png">

This is the code I used to come up with the results. 
And here are the results measured from Elephant Castle in London in comparison to Google Map's measured distance. 

<img width="1077" alt="screen shot 2018-07-26 at 11 06 18 am" src="https://user-images.githubusercontent.com/39035665/43256431-8e689fa2-90c4-11e8-9cb0-e22fdc2d55f2.png">

I am aware the unit is not correct.
However, if you look closely, the measurements don't scale proportionally.
e.g. the distance to King's Cross and Buckingham Palace, are very different from the results I made with Google Map.

https://www.mapbox.com/mapbox-unity-sdk/api/mapbox-sdk-cs/Mapbox.Utils.Vector2d.html#Mapbox_Utils_Vector2d_Distance_Mapbox_Utils_Vector2d_Mapbox_Utils_Vector2d_
https://github.com/mapbox/cheap-ruler
https://github.com/mapbox/cheap-ruler-cpp
https://github.com/mapbox/mapbox-unity-sdk/issues/562

Here are some links I referenced when coding this build. I could not find any other documents for CheapRuler in C# nor any related tutorial. 

If I am doing this incorrectly, what would be the most accurate way to find distance between two points?
Please, any help would be much appreciated :)

**Comment by atripathi-mb** [comment]
@zxcvb7653 
Vector2d.Distance is the vector distance for two vectors. It should be used only to calculate linear distances in 3D spaces. 

CheapRuler available in our SDK is a C# port of the original library.  
This test class is a great reference for how to use cheap ruler https://github.com/mapbox/mapbox-unity-sdk/blob/5d0dbf1e861377eb384b187a666141b7981878c7/sdkproject/Assets/Mapbox/Core/cheap-ruler-cs/Tests/Editor/MapboxUnitTests_CheapRulerCs.cs#L55

Which units are you using in the table above?

**Comment by BergWerkGIS** [comment]
Some more information about `CheapRuler` to know what it can be used (and not used) for:

* as @atripathi-mb pointed out it's a minimal port of the JavaScript version: https://github.com/mapbox/cheap-ruler
* it's intended to be fast, no complex math or fancy features
* it's intended to be "good enough" (no complex math)
* it's intended for local scale only and not for measurements around the globe
  * because: again, no complex math or fancy features
  * that's why you have to pass a latitude to the constructor. that it knows how to adjust for longitude distances at the specified latitude

That said, measuring `London -> Hong Kong` is expected to be way off.
Whereas the other examples should work just fine.

I suppose you need to flip the lat/lng values you pass to CheapRuler.

For me
```c#
	double[] elephantCastle = new double[] { -0.10053, 51.49520 };
	double[] bigBen = new double[] { -0.12458, 51.50069 };
	CheapRuler cr = new CheapRuler(elephantCastle[1], CheapRulerUnits.Kilometers);
	Debug.Log(cr.Distance(elephantCastle, bigBen));
```

prints
```
1.77845691659714
```

which is perfectly in sync with your Google results.

**Comment by BergWerkGIS** [comment]
Approximate precision you can expect to get from `CheapRuler` depending on the distance you intend to measure:

https://github.com/mapbox/cheap-ruler#precision

![image](https://user-images.githubusercontent.com/4549888/43312520-dd330f4a-918d-11e8-8c1a-bf03b55f2f67.png)

**Comment by zxcvb7653** [comment]
Thank you so much for everyone's help I really appreciate it! I will go give it a shot! <3

**Comment by TiborUdvari** [comment]
For people coming here after google, make sure you import the namespace before trying to use in Unity `using Mapbox.CheapRulerCs;`
