### ISSUE TITLE
Missing features when trying to render indoor map

### ISSUE THREAD

**Issue by Mowalle** [mapbox/mapbox-unity-sdk#940]
Greetings,

Unity 2018.1.1f1, C#
Mapbox 1.4.4

I am trying to display an indoor map by extruding the walls of a custom dataset, similar to the examples [here](https://www.mapbox.com/mapbox-gl-js/example/3d-extrusion-floorplan/) and [here](http://www-personal.umich.edu/~yonghah/rooms3d/). However, I am using the Mapbox Unity SDK instead. My problem is that the walls are not visualized correctly and sometimes even display artifacts.

I started by georeferencing the floor plan of the building in QGIS and exporting the data as a .geojson. I successfully uploaded the data to a dataset and exported a corresponding tileset from it.

Here you can see the georeferenced layers in QGIS. The thin grey polygon features have an attribute `type` with the value `wall`. The blue features are `room` features that are ignored for now.
![mapbox_indoor_imprecision_qgis](https://user-images.githubusercontent.com/6223042/43583090-b58402da-965e-11e8-9146-25e0577288bd.png)

The resulting dataset looks like this:
![mapbox_indoor_imprecision_dataset](https://user-images.githubusercontent.com/6223042/43583089-b56891f8-965e-11e8-97ea-88efd0a7651f.png)
and the corresponding tileset can be found [here](https://www.mapbox.com/studio/tilesets/mowalle.cjk17nzpf5un231phirmmwd8v-2rusy/).

So far so good. I changed my `AbstracMap`'s settings to access the custom tileset and set a filter to only extrude the walls. For the extrusion, I'm choosing a set value of `10` for now:
![mapbox_indoor_imprecision_settings](https://user-images.githubusercontent.com/6223042/43583091-b5acae7e-965e-11e8-92af-81981b1b12db.png)

However, what I get is a lot of missing walls and/or artifacts, depending on the `zoom` of the `AbstractMap`.

With `zoom = 15` (missing walls):
![mapbox_indoor_imprecision_1](https://user-images.githubusercontent.com/6223042/43583086-b509289e-965e-11e8-834f-4dcc45ed2a16.png)

With `zoom = 18` (note the strange diagonal walls, I assume this comes from the tile border?):
![mapbox_indoor_imprecision_2](https://user-images.githubusercontent.com/6223042/43583087-b530e3f2-965e-11e8-8b1f-4f88df6341c6.png)

With `zoom = 20` (some inverted normals on the backside):
![mapbox_indoor_imprecision_3](https://user-images.githubusercontent.com/6223042/43583088-b54ccc2a-965e-11e8-88d6-a1ca42d2d97b.png)

My first thought was that the reason for this could be some kind of floating-point error and that the walls are too thin/too close to each other (I also found this: https://blog.mapbox.com/wgs84-precision-in-unity-world-space-687c7d574bb3). Since I already tried different zoom-levels/scalings, do you have any idea how to fix this and display the walls properly?

Thanks in advance!

**Comment by jordy-isaac** [comment]
Hi @Mowalle 

This is likely happening because of the zoom level. When you zoom to a level like 15 three are alot of meters of data packed into a pixel and the precision is lost. I would suggest creating the footprint at a lower zoom level.

**Comment by Mowalle** [comment]
Hi,
thanks for taking the time to help!
>  I would suggest creating the footprint at a lower zoom level.

I don't quite understand what you mean by that. Maybe I'm just misunderstanding you, but I already tried different zoom levels as seen above. And QGIS, which I used for *creating* the floorplan, does not have a setting for zoom level as far as I know.

**Comment by BergWerkGIS** [comment]
@Mowalle the missing features your are _not_ 😏 seeing are due to automatic simplification that takes place during upload of your GeoJSON and conversion to a tileset.
The lower the zoom level the higher the simplification - and sometimes even removal of features.
That's why the data looks better at z20 than at z15.

Two ideas:

### lines instead of polygons
You could try digitizing the walls as lines instead of polygons, although I'm pretty sure automatic simplification will kick in here as well.

### tippecanoe

Instead of uploading the GeoJSON create a tileset (MBTiles file) locally (taking control over simplification) and upload that.
https://github.com/mapbox/tippecanoe would be the tool of choice.

Tippecanoe has a plethora of parameters but I suppose these https://github.com/mapbox/tippecanoe#line-and-polygon-simplification and the ones below that might be a good starting point.

Unfortunately I cannot help with the exact parameters as you'll have to play around with them and find the best combination for your use case.

Tippecanoe should be easy to get running on Linux/OSX but there's no native Windows version.
However it runs fine on the Windows Subsystem for Linux (WSL)
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by chiranjivbudhe** [comment]
@Mowalle Hi, I am facing the same issue, where you able to resolve yours?

**Comment by Mowalle** [comment]
Hi @chiranjivbudhe, unfortunately not really. I tried playing around with tippecanoe a bit as suggested by @BergWerkGIS. However, I couldn't find a set of parameters that worked consistently for all zoom levels. In the end the requirements for my project changed so now I'm using hand-made models of the buildings instead.
