### ISSUE TITLE
[support] Spawn prefab & persist 

### ISSUE THREAD

**Issue by pplcf** [mapbox/mapbox-unity-sdk#961]
Hello. 
What is a best approach to dynamically spawn prefabs(preferably avoiding building layer) and persist its position for the next map reload? 

Should I make my own modifier(based on SpawnInsideModifier) with persist/load logic? Or should I just keep SpawnOnMap example approach and basically do everything on top of mapbox? Is there is a more cleaner & right way to do it?

Thank you.

**Comment by DennyLindberg** [comment]
While it might not be *the best approach™*, we have implemented our own approach on top of Mapbox and it has worked fine. (apart from #867, #896 and #897) I believe one advantage for doing so is that you become less dependent on how the SDK is designed and can focus on your own implementation. Spend some time on building a good interface to the SDK and you are good to go. (with interface I mean that you create your own class that wraps the functionality of the SDK so that the rest of your code never touches it directly)

If you are placing stationary prefabs that does not update every frame you will stumble upon an issue however. There is no clear moment in the SDK when there is tile data available so that your prefabs will snap properly to the terrain. The trickiest part is knowing when the tiles have finished loading their height data. The SDK is currently using event propagation for generating content (after the tiles have loaded) and there is no clean way to connect to that process at the moment from "outside".

Note that the `SpawnOnMap.cs` example circumvents this issue by re-placing the prefabs every frame, which means that the prefab will snap to its proper height as soon as the data is available. If you have hundreds or even thousands of prefabs, this might not be a good idea.

We solved this issue by keeping track of some events, such as when tiles load their data. I'm leaving a few snippets below to give you an idea.

```
map.TileProvider.OnTileAdded += ProcessNewTile

protected void ProcessNewTile(UnwrappedTileId tileId)
{
	UnityTile tile = map.MapVisualizer.GetUnityTileFromUnwrappedTileId(tileId);

	tile.OnHeightDataChanged += OnTileLoaded;

        // Execute callback right away as we don't know if the tile has loaded cached content or is
        // running a coroutine (which delays data to another frame)
	OnTileLoaded(tile);
}

protected void OnTileLoaded(UnityTile unityTile)
{
	if (unityTile.HeightDataState != TilePropertyState.Loading)
	{
             // Height data is available, do whatever you need with your prefabs from here on
        }
}
```

There are methods for assigning your prefab to a specific tile id (see Conversions.cs). You can use this knowledge to map your prefabs to a specific tile and update that set of prefabs as soon as the tile changes. You will also need to keep track of changing zoom levels, which generates a new set of tiles, which in turn means you must re-map all your prefabs to the new tiles.

I believe most of the stuff you need is in `AbstractMap.cs`, `AbstractMap.MapVisualizer (AbstractMapVisualizer.cs)`, `UnityTile.cs` and `Conversions.cs`.

**Comment by pplcf** [comment]
Thank you for your suggestion. I think I will stick with your approach.
