### ISSUE TITLE
Differeny collider types in TileProvider according to Terrain Elevation

### ISSUE THREAD

**Issue by m3rt32** [mapbox/mapbox-unity-sdk#989]
* Unity version: 2018.1.8f
* Mapbox SDK version: 1.4.5
* The platform you're building to: Android&Ios
* A description of what you're trying to do:
We've been using v1.3 with **FlatTerrainFactory**, now because of they've depricated and colliders are added from **TileProvider** script (instead of seperate factories), we only have **Mesh collider** option. Before, we could choose **FlatTerrainFactory** and go forward with **Box Collider** but know despite the Terrain Elevation options, all collider types are same and adding a **Mesh Collider** component. For the sake of performance cost and the other scripts that we've made, this feature is needed. 

In the other hand, in the beginning we tried to use Flat Terrain elevation type to be able to have the same functionality as we had before. but it is not even adding a collider. Even "Add Collider" checkbox is checked. We think this is a bug.
![image](https://user-images.githubusercontent.com/3215742/44928167-025f5f00-ad25-11e8-94db-404cf964ef0d.png)

**Comment by atripathi-mb** [comment]
@m3rt32 Thanks for the ticket, this issue is on our list to be fixed for next release. In the meantime, you can modify this line of code to add a different type of Collider for terrain meshes. 

https://github.com/mapbox/mapbox-unity-sdk/blob/488cf9330880a7930467bab46a9b2ce255561b96/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Data/UnityTile.cs#L247
